create or replace force editionable view dirkspzm32.isi_v_res_mag_find_artikel (
    res_id_res,
    res_name,
    mag_params,
    mag_name,
    sid,
    firma_nr,
    lam_id,
    artikel_id,
    lgr_platz,
    lte_id,
    lhm_id,
    charge_id,
    serie_id,
    leitzahl,
    fa_ag,
    fa_upos,
    abnr,
    best_nr,
    best_pos,
    res_id,
    prod_datum,
    zug_datum,
    ls_login_id,
    menge,
    lam_kg,
    lam_text,
    labor_status,
    labor_text,
    lam_mhd,
    kunden_nr,
    kd_art_nr,
    lieferant_nr,
    lam_mhd_ausgabe,
    menge_basis,
    mengeneinheit_basis,
    order_pos_auf_id,
    zeichnung,
    zeichnung_index,
    li_nr_lief,
    lte_id_lieferant,
    sonst_id_lieferant,
    akt_inventur_id,
    letzte_inventur_id,
    letzte_inventur_datum,
    letzte_inventur_login_id,
    lam_p1,
    lam_p2,
    lam_p3,
    lam_p4,
    lam_p5,
    lam_p6,
    lam_p7,
    lam_p8,
    lam_p9,
    lam_p10,
    res_menge,
    res_ziel_lte_id,
    res_login_id,
    check_ware_transp_id,
    fae_id,
    fae_id_position,
    qs_status,
    waren_typ,
    lhm_lfd_nr,
    packschema_kopf_id,
    packschema_lfdn,
    lhm_c_lfd_nr,
    owner_address_id,
    lam_sel1,
    lam_sel2,
    lam_sel3,
    lam_sel4,
    lam_sel5,
    lam_sel6,
    lam_sel7,
    lam_sel8,
    lam_sel9,
    lam_sel10,
    hersteller_kuerzel_liste
) as
    select
        r.res_id     res_id_res,
        r.res_name,
        rmc.mag_params,
        rml.res_name mag_name,
        lam.sid,
        lam.firma_nr,
        lam.lam_id,
        lam.artikel_id,
        lam.lgr_platz,
        lam.lte_id,
        lam.lhm_id,
        lam.charge_id,
        lam.serie_id,
        lam.leitzahl,
        lam.fa_ag,
        lam.fa_upos,
        lam.abnr,
        lam.best_nr,
        lam.best_pos,
        lam.res_id,
        lam.prod_datum,
        lam.zug_datum,
        lam.ls_login_id,
        lam.menge,
        lam.lam_kg,
        lam.lam_text,
        lam.labor_status,
        lam.labor_text,
        lam.lam_mhd,
        lam.kunden_nr,
        lam.kd_art_nr,
        lam.lieferant_nr,
        lam.lam_mhd_ausgabe,
        lam.menge_basis,
        lam.mengeneinheit_basis,
        lam.order_pos_auf_id,
        lam.zeichnung,
        lam.zeichnung_index,
        lam.li_nr_lief,
        lam.lte_id_lieferant,
        lam.sonst_id_lieferant,
        lam.akt_inventur_id,
        lam.letzte_inventur_id,
        lam.letzte_inventur_datum,
        lam.letzte_inventur_login_id,
        lam.lam_p1,
        lam.lam_p2,
        lam.lam_p3,
        lam.lam_p4,
        lam.lam_p5,
        lam.lam_p6,
        lam.lam_p7,
        lam.lam_p8,
        lam.lam_p9,
        lam.lam_p10,
        lam.res_menge,
        lam.res_ziel_lte_id,
        lam.res_login_id,
        lam.check_ware_transp_id,
        lam.fae_id,
        lam.fae_id_position,
        lam.qs_status,
        lam.waren_typ,
        lam.lhm_lfd_nr,
        lam.packschema_kopf_id,
        lam.packschema_lfdn,
        lam.lhm_c_lfd_nr,
        lam.owner_address_id,
        lam.lam_sel1,
        lam.lam_sel2,
        lam.lam_sel3,
        lam.lam_sel4,
        lam.lam_sel5,
        lam.lam_sel6,
        lam.lam_sel7,
        lam.lam_sel8,
        lam.lam_sel9,
        lam.lam_sel10,
        lam.hersteller_kuerzel_liste
    from
        isi_resource    r,
        isi_res_magazin rm,
        isi_res_mag_cfg rmc,
        isi_resource    rml,
        lvs_lam         lam
    where
            rm.res_id = r.res_id
        and rmc.res_id = rm.ma_res_id
        and rml.res_id = rm.ma_res_id
        and lam.lgr_platz = rml.lager_roh
        and lam.menge > 0
        and lam.labor_status = 'F'
    order by
        lam.lam_mhd;


-- sqlcl_snapshot {"hash":"1c1044e01825786b4020910cc83875c6da4056d1","type":"VIEW","name":"ISI_V_RES_MAG_FIND_ARTIKEL","schemaName":"DIRKSPZM32","sxml":""}