create or replace force editionable view dirkspzm32.lvs_v_lam_bh_lam (
    sid,
    firma_nr,
    vorg_id,
    vorg_typ,
    lam_bh_id,
    lam_id,
    artikel_id,
    bus,
    buch_datum,
    ls_login_id,
    lgr_platz,
    lte_id,
    lhm_id,
    charge_id,
    serie_id,
    abnr,
    menge,
    lam_bh_kg,
    lam_bh_kg_einheit,
    res_id,
    leitzahl,
    fa_ag,
    fa_upos,
    abnr_extern,
    vorgang_id,
    lam_charge_id,
    lam_serie_id,
    lam_leitzahl,
    lam_fa_ag,
    lam_fa_upos,
    lam_abnr,
    lam_best_nr,
    lam_best_pos,
    lam_res_id,
    lam_prod_datum,
    lam_zug_datum,
    lam_ls_login_id,
    lam_menge,
    lam_lam_kg,
    lam_lam_text,
    lam_labor_status,
    lam_labor_text,
    lam_lam_mhd,
    lam_kunden_nr,
    lam_kd_art_nr,
    lam_lieferant_nr,
    lam_lam_mhd_ausgabe,
    lam_menge_basis,
    lam_mengeneinheit_basis,
    lam_order_pos_auf_id,
    lam_zeichnung,
    lam_zeichnung_index,
    lam_li_nr_lief,
    lam_lte_id_lieferant,
    lam_sonst_id_lieferant
) as
    select
        lam_bh.sid,
        lam_bh.firma_nr,
        lam_bh.vorg_id,
        lam_bh.vorg_typ,
        lam_bh.lam_bh_id,
        lam_bh.lam_id,
        lam_bh.artikel_id,
        lam_bh.bus,
        lam_bh.buch_datum,
        lam_bh.ls_login_id,
        lam_bh.lgr_platz,
        lam_bh.lte_id,
        lam_bh.lhm_id,
        lam_bh.charge_id,
        lam_bh.serie_id,
        lam_bh.abnr,
        lam_bh.menge,
        lam_bh.lam_bh_kg,
        lam_bh.lam_bh_kg_einheit,
        lam_bh.res_id,
        lam_bh.leitzahl,
        lam_bh.fa_ag,
        lam_bh.fa_upos,
        lam_bh.abnr_extern,
        lam_bh.vorgang_id,
        lam.charge_id           lam_charge_id,
        lam.serie_id            lam_serie_id,
        lam.leitzahl            lam_leitzahl,
        lam.fa_ag               lam_fa_ag,
        lam.fa_upos             lam_fa_upos,
        lam.abnr                lam_abnr,
        lam.best_nr             lam_best_nr,
        lam.best_pos            lam_best_pos,
        lam.res_id              lam_res_id,
        lam.prod_datum          lam_prod_datum,
        lam.zug_datum           lam_zug_datum,
        lam.ls_login_id         lam_ls_login_id,
        lam.menge               lam_menge,
        lam.lam_kg              lam_lam_kg,
        lam.lam_text            lam_lam_text,
        lam.labor_status        lam_labor_status,
        lam.labor_text          lam_labor_text,
        lam.lam_mhd             lam_lam_mhd,
        lam.kunden_nr           lam_kunden_nr,
        lam.kd_art_nr           lam_kd_art_nr,
        lam.lieferant_nr        lam_lieferant_nr,
        lam.lam_mhd_ausgabe     lam_lam_mhd_ausgabe,
        lam.menge_basis         lam_menge_basis,
        lam.mengeneinheit_basis lam_mengeneinheit_basis,
        lam.order_pos_auf_id    lam_order_pos_auf_id,
        lam.zeichnung           lam_zeichnung,
        lam.zeichnung_index     lam_zeichnung_index,
        lam.li_nr_lief          lam_li_nr_lief,
        lam.lte_id_lieferant    lam_lte_id_lieferant,
        lam.sonst_id_lieferant  lam_sonst_id_lieferant
    from
        lvs_lam_bh lam_bh,
        lvs_lam    lam
    where
            lam_bh.sid = lam.sid
        and lam_bh.firma_nr = lam.firma_nr
        and lam_bh.lam_id = lam.lam_id
    union
    select
        lam_bh_hist.sid,
        lam_bh_hist.firma_nr,
        lam_bh_hist.vorg_id,
        lam_bh_hist.vorg_typ,
        lam_bh_hist.lam_bh_id,
        lam_bh_hist.lam_id,
        lam_bh_hist.artikel_id,
        lam_bh_hist.bus,
        lam_bh_hist.buch_datum,
        lam_bh_hist.ls_login_id,
        lam_bh_hist.lgr_platz,
        lam_bh_hist.lte_id,
        lam_bh_hist.lhm_id,
        lam_bh_hist.charge_id,
        lam_bh_hist.serie_id,
        lam_bh_hist.abnr,
        lam_bh_hist.menge,
        lam_bh_hist.lam_bh_kg,
        lam_bh_hist.lam_bh_kg_einheit,
        lam_bh_hist.res_id,
        lam_bh_hist.leitzahl,
        lam_bh_hist.fa_ag,
        lam_bh_hist.fa_upos,
        lam_bh_hist.abnr_extern,
        lam_bh_hist.vorgang_id,
        lam_hist.charge_id           lam_charge_id,
        lam_hist.serie_id            lam_serie_id,
        lam_hist.leitzahl            lam_leitzahl,
        lam_hist.fa_ag               lam_fa_ag,
        lam_hist.fa_upos             lam_fa_upos,
        lam_hist.abnr                lam_abnr,
        lam_hist.best_nr             lam_best_nr,
        lam_hist.best_pos            lam_best_pos,
        lam_hist.res_id              lam_res_id,
        lam_hist.prod_datum          lam_prod_datum,
        lam_hist.zug_datum           lam_zug_datum,
        lam_hist.ls_login_id         lam_ls_login_id,
        lam_hist.menge               lam_menge,
        lam_hist.lam_kg              lam_lam_kg,
        lam_hist.lam_text            lam_lam_text,
        lam_hist.labor_status        lam_labor_status,
        lam_hist.labor_text          lam_labor_text,
        lam_hist.lam_mhd             lam_lam_mhd,
        lam_hist.kunden_nr           lam_kunden_nr,
        lam_hist.kd_art_nr           lam_kd_art_nr,
        lam_hist.lieferant_nr        lam_lieferant_nr,
        lam_hist.lam_mhd_ausgabe     lam_lam_mhd_ausgabe,
        lam_hist.menge_basis         lam_menge_basis,
        lam_hist.mengeneinheit_basis lam_mengeneinheit_basis,
        lam_hist.order_pos_auf_id    lam_order_pos_auf_id,
        lam_hist.zeichnung           lam_zeichnung,
        lam_hist.zeichnung_index     lam_zeichnung_index,
        lam_hist.li_nr_lief          lam_li_nr_lief,
        lam_hist.lte_id_lieferant    lam_lte_id_lieferant,
        lam_hist.sonst_id_lieferant  lam_sonst_id_lieferant
    from
        lvs_lam_bh_hist lam_bh_hist,
        lvs_lam         lam_hist
    where
            lam_bh_hist.sid = lam_hist.sid
        and lam_bh_hist.firma_nr = lam_hist.firma_nr
        and lam_bh_hist.lam_id = lam_hist.lam_id;


-- sqlcl_snapshot {"hash":"5c87fad27c74415ebc9acc03cb76c6d404032a65","type":"VIEW","name":"LVS_V_LAM_BH_LAM","schemaName":"DIRKSPZM32","sxml":""}