
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DIRKSPZM32"."V_RES_MAGAZIN_BOUND_LTE" ("LTE_ID", "RES_NAME", "LAGER_ROH", "SID", "FIRMA_NR", "RES_ID", "CREATED_DATE", "CREATED_LOGIN_ID", "LAST_CHANGE_DATE", "LAST_CHANGE_LOGIN_ID", "USAGE", "ENABLED", "STATUS", "MAG_PARAMS", "MENGE_MAX", "MENGE_MIN", "ARTIKEL_ID", "ZEICHNUNG", "ZEICHNUNG_INDEX", "CHARGE", "MENGE_IST", "MAG_TYPE", "MODUL_BEARBEITER", "LTE_NAME", "LHM_NAME") AS 
  select lte.lte_id, r.res_name, r.lager_roh, t."SID",t."FIRMA_NR",t."RES_ID",t."CREATED_DATE",t."CREATED_LOGIN_ID",t."LAST_CHANGE_DATE",t."LAST_CHANGE_LOGIN_ID",t."USAGE",t."ENABLED",t."STATUS",t."MAG_PARAMS",t."MENGE_MAX",t."MENGE_MIN",t."ARTIKEL_ID",t."ZEICHNUNG",t."ZEICHNUNG_INDEX",t."CHARGE",t."MENGE_IST",t."MAG_TYPE",t."MODUL_BEARBEITER",t."LTE_NAME",t."LHM_NAME"
  from ISI_RES_MAG_CFG t,
       isi_resource r,
       lvs_lte lte
 where r.res_id = t.res_id
   and lte.lgr_platz(+) = r.lager_roh
;


-- sqlcl_snapshot {"hash":"0febf22228ed8ddec7ad4a0dc707de25b69833f0","type":"VIEW","name":"V_RES_MAGAZIN_BOUND_LTE","schemaName":"DIRKSPZM32","sxml":""}