
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DIRKSPZM32"."Z_PZM_PBI_BDE" ("ZE_BDE_PERS_NR", "ZE_BDE_DATUM", "ZE_BDE_DAY_IST_START", "ZE_BDE_DAY_IST_ENDE", "ZE_BDE_SA_KURZNAME", "ZE_BDE_LEITZAHL", "ZE_BDE_FA_AG", "ZE_BDE_FA_UPOS", "ZE_BDE_ZEIT_MIN", "ZE_BDE_VERBUCHT_DATUM", "ZE_BDE_VERBUCHT_STATUS", "ZE_BDE_RET_CODE", "ZE_BDE_STATUS_TEXT", "CREATED_DATE", "CREATED_LOGIN_ID", "LAST_CHANGE_DATE", "LAST_CHANGE_LOGIN_ID", "ZE_BDE_BASIS", "ZE_BDE_PERSONALTEILBER") AS 
  select t."ZE_BDE_PERS_NR",t."ZE_BDE_DATUM",t."ZE_BDE_DAY_IST_START",t."ZE_BDE_DAY_IST_ENDE",t."ZE_BDE_SA_KURZNAME",t."ZE_BDE_LEITZAHL",t."ZE_BDE_FA_AG",t."ZE_BDE_FA_UPOS",t."ZE_BDE_ZEIT_MIN",t."ZE_BDE_VERBUCHT_DATUM",t."ZE_BDE_VERBUCHT_STATUS",t."ZE_BDE_RET_CODE",t."ZE_BDE_STATUS_TEXT",t."CREATED_DATE",t."CREATED_LOGIN_ID",t."LAST_CHANGE_DATE",t."LAST_CHANGE_LOGIN_ID",t."ZE_BDE_BASIS",t."ZE_BDE_PERSONALTEILBER" from PZM_ZE_BDE_ZEITEN t
   where t.ze_bde_basis = 'BDE'
     and t.ze_bde_verbucht_status = 'UE'
 order by t.last_change_date, t.ZE_BDE_PERS_NR, t.ZE_BDE_DAY_IST_START desc, t.ZE_BDE_BASIS, t.ZE_BDE_DATUM
;


-- sqlcl_snapshot {"hash":"d204cb2bfcc88739dc1a532175759ade5978ed24","type":"VIEW","name":"Z_PZM_PBI_BDE","schemaName":"DIRKSPZM32","sxml":""}