
  ALTER TABLE "DIRKSPZM32"."REP_SECURITY_CFG" ADD CONSTRAINT "FK2_REP_SECURITY_CFG" FOREIGN KEY ("LOGIN_ID")
	  REFERENCES "DIRKSPZM32"."ISI_USER" ("LOGIN_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"f9583747ce13299fcfa2036b45afe70d0fb0c9a7","type":"REF_CONSTRAINT","name":"FK2_REP_SECURITY_CFG","schemaName":"DIRKSPZM32","sxml":""}