
  ALTER TABLE "REP_SECURITY_CFG" ADD CONSTRAINT "FK2_REP_SECURITY_CFG" FOREIGN KEY ("LOGIN_ID")
	  REFERENCES "ISI_USER" ("LOGIN_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"396ce8d80a6801d8c486f3ccaa2c1ade882a2f5f","type":"REF_CONSTRAINT","name":"FK2_REP_SECURITY_CFG","schemaName":"DIRKSPZM32","sxml":""}