
  ALTER TABLE "REP_SECURITY_CFG" ADD CONSTRAINT "FK3_REP_SECURITY_CFG" FOREIGN KEY ("REP_ID")
	  REFERENCES "REP_ABFRAGEN" ("REP_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"1805fa54481bfb83a8d90ff1c379a60a0cca7686","type":"REF_CONSTRAINT","name":"FK3_REP_SECURITY_CFG","schemaName":"DIRKSPZM32","sxml":""}