
  ALTER TABLE "PZM_ABT_LEITUNG" ADD CONSTRAINT "FK_ABT_L_PERS_NR" FOREIGN KEY ("ABT_L_PERS_NR")
	  REFERENCES "PZM_PERSONAL" ("PERS_NR") ON DELETE CASCADE DISABLE;


-- sqlcl_snapshot {"hash":"a67c4b4cd594ce4a76c6d0ce55ada2c84d917234","type":"REF_CONSTRAINT","name":"FK_ABT_L_PERS_NR","schemaName":"DIRKSPZM32","sxml":""}