
  ALTER TABLE "DIRKSPZM32"."PZM_ABWESENHEITSARTEN" ADD CONSTRAINT "FK_AA_LZ_ID" FOREIGN KEY ("LZ_ID")
	  REFERENCES "DIRKSPZM32"."PZM_LOHNARTEN" ("LZ_ID") ON DELETE SET NULL DISABLE;


-- sqlcl_snapshot {"hash":"62e6078fd605125c34adf5d0f7cd10a27a28908f","type":"REF_CONSTRAINT","name":"FK_AA_LZ_ID","schemaName":"DIRKSPZM32","sxml":""}