
  ALTER TABLE "PZM_AZUBI_DATEN" ADD CONSTRAINT "FK_AD_PERS_NR" FOREIGN KEY ("AD_PERS_NR")
	  REFERENCES "PZM_PERSONAL" ("PERS_NR") ON DELETE CASCADE DISABLE;


-- sqlcl_snapshot {"hash":"e5705eb30b87fa72dc8131c52d04cb298b40e2f5","type":"REF_CONSTRAINT","name":"FK_AD_PERS_NR","schemaName":"DIRKSPZM32","sxml":""}