
  ALTER TABLE "ISI_ARBEITSPLATZ" ADD CONSTRAINT "FK_ARBEITSPLATZ_ADRESSE" FOREIGN KEY ("ADRESS_ID")
	  REFERENCES "ISI_ADRESSEN" ("ADRESS_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"7cebb25b02b3347c0680d993c891f9f696e503ea","type":"REF_CONSTRAINT","name":"FK_ARBEITSPLATZ_ADRESSE","schemaName":"DIRKSPZM32","sxml":""}