
  ALTER TABLE "PZM_ABWESENHEITSARTEN" ADD CONSTRAINT "FK_AA_LZ_ID" FOREIGN KEY ("LZ_ID")
	  REFERENCES "PZM_LOHNARTEN" ("LZ_ID") ON DELETE SET NULL DISABLE;


-- sqlcl_snapshot {"hash":"85f3c23f8ecb79f21502949c2d5a94a10e20565e","type":"REF_CONSTRAINT","name":"FK_AA_LZ_ID","schemaName":"DIRKSPZM32","sxml":""}