
  ALTER TABLE "DIRKSPZM32"."ACS_USER_PERMISSIONS" ADD CONSTRAINT "FK_ACS_USER_PERMISSIONS_1" FOREIGN KEY ("ACCESS_POINT_DEVICE_ID")
	  REFERENCES "DIRKSPZM32"."ACS_ACCESS_POINTS_DEVICES" ("ACCESS_POINT_DEVICE_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"f82208028f02a1af7ca7ffc1de5d2a26ec8445b9","type":"REF_CONSTRAINT","name":"FK_ACS_USER_PERMISSIONS_1","schemaName":"DIRKSPZM32","sxml":""}