
  ALTER TABLE "DIRKSPZM32"."PZM_ABTEILUNGEN" ADD CONSTRAINT "FK_ABT_PB_ID" FOREIGN KEY ("ABT_PB_ID")
	  REFERENCES "DIRKSPZM32"."PZM_PRODUKTIONSBEREICHE" ("PB_ID") DISABLE;


-- sqlcl_snapshot {"hash":"32da75fee1a9b7df0e1331ab5e685b71fe96acfb","type":"REF_CONSTRAINT","name":"FK_ABT_PB_ID","schemaName":"DIRKSPZM32","sxml":""}