
  ALTER TABLE "DIRKSPZM32"."ISI_ARTIKEL" ADD CONSTRAINT "FK_ARTIKEL_LEG_ZUS_ARTIKEL" FOREIGN KEY ("LEG_ZUSCHLAG_ARTIKEL_ID")
	  REFERENCES "DIRKSPZM32"."ISI_ARTIKEL" ("ARTIKEL_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"61c33eabcf215340a9d159ba57ef268ddce40f53","type":"REF_CONSTRAINT","name":"FK_ARTIKEL_LEG_ZUS_ARTIKEL","schemaName":"DIRKSPZM32","sxml":""}