
  ALTER TABLE "DIRKSPZM32"."PZM_ABTEILUNGEN" ADD CONSTRAINT "FK_ABT_KST_ID" FOREIGN KEY ("ABT_KST_ID")
	  REFERENCES "DIRKSPZM32"."ISI_KOSTENSTELLEN" ("KST_NR") DISABLE;


-- sqlcl_snapshot {"hash":"e72f300203f6b3345d0cfd746328cfd20de5f57f","type":"REF_CONSTRAINT","name":"FK_ABT_KST_ID","schemaName":"DIRKSPZM32","sxml":""}