
  ALTER TABLE "PZM_ABWESENHEITS_ANTR" ADD CONSTRAINT "FK_AU_PRUEF_PERS_NR" FOREIGN KEY ("AU_PRUEF_PERS_NR")
	  REFERENCES "PZM_PERSONAL" ("PERS_NR") DISABLE;


-- sqlcl_snapshot {"hash":"410f1e7de7ae8c8024ba45231fe4b9d061b95188","type":"REF_CONSTRAINT","name":"FK_AU_PRUEF_PERS_NR","schemaName":"DIRKSPZM32","sxml":""}