
  ALTER TABLE "DIRKSPZM32"."PZM_ABT_LEITUNG" ADD CONSTRAINT "FK_ABT_L_PERS_NR" FOREIGN KEY ("ABT_L_PERS_NR")
	  REFERENCES "DIRKSPZM32"."PZM_PERSONAL" ("PERS_NR") ON DELETE CASCADE DISABLE;


-- sqlcl_snapshot {"hash":"e67cbfb90a1d3b1fb0583c686b966bf37f6eaf01","type":"REF_CONSTRAINT","name":"FK_ABT_L_PERS_NR","schemaName":"DIRKSPZM32","sxml":""}