
  ALTER TABLE "DIRKSPZM32"."PZM_ABWESENHEITS_ANTR" ADD CONSTRAINT "FK_AU_PRUEF_PERS_NR" FOREIGN KEY ("AU_PRUEF_PERS_NR")
	  REFERENCES "DIRKSPZM32"."PZM_PERSONAL" ("PERS_NR") DISABLE;


-- sqlcl_snapshot {"hash":"3e355dce818810e63e91fb0b1efff5412e9c46d9","type":"REF_CONSTRAINT","name":"FK_AU_PRUEF_PERS_NR","schemaName":"DIRKSPZM32","sxml":""}