
  ALTER TABLE "PZM_ABTEILUNGEN" ADD CONSTRAINT "FK_ABT_KST_ID" FOREIGN KEY ("ABT_KST_ID")
	  REFERENCES "ISI_KOSTENSTELLEN" ("KST_NR") DISABLE;


-- sqlcl_snapshot {"hash":"8da7f47e332daf6730fea0713adc9eda427c9bb6","type":"REF_CONSTRAINT","name":"FK_ABT_KST_ID","schemaName":"DIRKSPZM32","sxml":""}