
  ALTER TABLE "ISI_ARTIKEL" ADD CONSTRAINT "FK_ARTIKEL_LEG_ZUS_ARTIKEL" FOREIGN KEY ("LEG_ZUSCHLAG_ARTIKEL_ID")
	  REFERENCES "ISI_ARTIKEL" ("ARTIKEL_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"9fdf5cb3333f84e02e8a058e40e599091781988f","type":"REF_CONSTRAINT","name":"FK_ARTIKEL_LEG_ZUS_ARTIKEL","schemaName":"DIRKSPZM32","sxml":""}