
  ALTER TABLE "PZM_ABWESENHEITS_ANTR" ADD CONSTRAINT "FK_AU_PERS_NR" FOREIGN KEY ("AU_PERS_NR")
	  REFERENCES "PZM_PERSONAL" ("PERS_NR") DISABLE;


-- sqlcl_snapshot {"hash":"d288d0f4aaf86ec02f34652b74b4e4b5ee5ae4f8","type":"REF_CONSTRAINT","name":"FK_AU_PERS_NR","schemaName":"DIRKSPZM32","sxml":""}