
  ALTER TABLE "PZM_ABTEILUNGEN" ADD CONSTRAINT "FK_ABT_TARIF_NAME" FOREIGN KEY ("TARIF_NAME")
	  REFERENCES "PZM_TARIFMODELLE" ("TARIF_NAME") DISABLE;


-- sqlcl_snapshot {"hash":"8c0a8c8223b0a355ca48aac06df7ab856f1b9275","type":"REF_CONSTRAINT","name":"FK_ABT_TARIF_NAME","schemaName":"DIRKSPZM32","sxml":""}