
  ALTER TABLE "DIRKSPZM32"."ISI_LAND_REGION" ADD CONSTRAINT "FK_COUNTRY" FOREIGN KEY ("COUNTRY")
	  REFERENCES "DIRKSPZM32"."ISI_LAND" ("ISOCODE") ENABLE;


-- sqlcl_snapshot {"hash":"4e71153bcd87becf982d1e6ec62a08a2c019851b","type":"REF_CONSTRAINT","name":"FK_COUNTRY","schemaName":"DIRKSPZM32","sxml":""}