
  ALTER TABLE "DIRKSPZM32"."CAL_RES_APPOINTMENT_TYPES" ADD CONSTRAINT "FK_CAL_RESOURCE_ID" FOREIGN KEY ("CAL_RESOURCE_ID")
	  REFERENCES "DIRKSPZM32"."CAL_RESOURCES" ("ID") ENABLE;


-- sqlcl_snapshot {"hash":"aa74174836dc6b6d100b348947b9ca5c77be3a33","type":"REF_CONSTRAINT","name":"FK_CAL_RESOURCE_ID","schemaName":"DIRKSPZM32","sxml":""}