
  ALTER TABLE "CAL_APPOINTMENTS" ADD CONSTRAINT "FK_CAL_APPOINTMENTS1" FOREIGN KEY ("CALENDAR_ID")
	  REFERENCES "CAL_CFG" ("CALENDAR_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"cd57980df3237e47a2abf7321b5d54416543b152","type":"REF_CONSTRAINT","name":"FK_CAL_APPOINTMENTS1","schemaName":"DIRKSPZM32","sxml":""}