
  ALTER TABLE "CAL_RES_APPOINTMENT_TYPES" ADD CONSTRAINT "FK_CAL_APP_TYPE_ID" FOREIGN KEY ("CAL_APPOINTMENT_TYPE_ID")
	  REFERENCES "CAL_APPOINTMENT_TYPES" ("ID") ENABLE;


-- sqlcl_snapshot {"hash":"42f67003685a80e4f94ca64f9880dab96db79853","type":"REF_CONSTRAINT","name":"FK_CAL_APP_TYPE_ID","schemaName":"DIRKSPZM32","sxml":""}