
  ALTER TABLE "DIRKSPZM32"."ISI_HERSTELLER" ADD CONSTRAINT "FK_ISI_HERSTELLER_ADR" FOREIGN KEY ("ADRESS_ID")
	  REFERENCES "DIRKSPZM32"."ISI_ADRESSEN" ("ADRESS_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"97b223da2da6940b1cb0da5afaf5aa03631ac817","type":"REF_CONSTRAINT","name":"FK_ISI_HERSTELLER_ADR","schemaName":"DIRKSPZM32","sxml":""}