
  ALTER TABLE "ISI_RES_PLAN_DATA" ADD CONSTRAINT "FK_ISI_RES_PLAN_DATA_SM" FOREIGN KEY ("SM_NAME")
	  REFERENCES "PZM_SCHICHT_MODELLE" ("SM_NAME") ENABLE;


-- sqlcl_snapshot {"hash":"5b9a21949ba22a84a16794b3a90d8d9f0fcb2f0c","type":"REF_CONSTRAINT","name":"FK_ISI_RES_PLAN_DATA_SM","schemaName":"DIRKSPZM32","sxml":""}