
  ALTER TABLE "ISI_ARTIKEL_HERSTELLER_WERK" ADD CONSTRAINT "FK_ISI_ARTIKEL_HERST_WERK_ADR" FOREIGN KEY ("ADRESS_ID")
	  REFERENCES "ISI_ADRESSEN" ("ADRESS_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"ac3979e95b7a1ef563f7a8df29c097970e3855ef","type":"REF_CONSTRAINT","name":"FK_ISI_ARTIKEL_HERST_WERK_ADR","schemaName":"DIRKSPZM32","sxml":""}