
  ALTER TABLE "ISI_ARTIKEL_HERSTELLER_WERK" ADD CONSTRAINT "FK_ISI_ARTIKEL_HERST_WERK_ART" FOREIGN KEY ("ARTIKEL_ID")
	  REFERENCES "ISI_ARTIKEL" ("ARTIKEL_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"ec3716d1ae9f58015da01f0be574242dec7d8aef","type":"REF_CONSTRAINT","name":"FK_ISI_ARTIKEL_HERST_WERK_ART","schemaName":"DIRKSPZM32","sxml":""}