
  ALTER TABLE "DIRKSPZM32"."ISI_ARTIKEL_HERSTELLER_WERK" ADD CONSTRAINT "FK_ISI_ARTIKEL_HERST_WERK_ART" FOREIGN KEY ("ARTIKEL_ID")
	  REFERENCES "DIRKSPZM32"."ISI_ARTIKEL" ("ARTIKEL_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"37e3c0048e0cb704f749d2d28c07606da10d4e8c","type":"REF_CONSTRAINT","name":"FK_ISI_ARTIKEL_HERST_WERK_ART","schemaName":"DIRKSPZM32","sxml":""}