
  ALTER TABLE "ISI_ARTIKEL_HERSTELLER" ADD CONSTRAINT "FK_ISI_ARTIKEL_HERSTELLER_ADR" FOREIGN KEY ("ADRESS_ID")
	  REFERENCES "ISI_ADRESSEN" ("ADRESS_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"a30d189a347810c290acfbda2468ee8d45ea1d0f","type":"REF_CONSTRAINT","name":"FK_ISI_ARTIKEL_HERSTELLER_ADR","schemaName":"DIRKSPZM32","sxml":""}