
  ALTER TABLE "DIRKSPZM32"."ISI_RES_PLAN_DATA" ADD CONSTRAINT "FK_ISI_RES_PLAN_DATA_SM" FOREIGN KEY ("SM_NAME")
	  REFERENCES "DIRKSPZM32"."PZM_SCHICHT_MODELLE" ("SM_NAME") ENABLE;


-- sqlcl_snapshot {"hash":"2a63bba4cb69ed6d7427f8405ab4c1293e6fc0d2","type":"REF_CONSTRAINT","name":"FK_ISI_RES_PLAN_DATA_SM","schemaName":"DIRKSPZM32","sxml":""}