
  ALTER TABLE "ISI_HERSTELLER" ADD CONSTRAINT "FK_ISI_HERSTELLER_ADR" FOREIGN KEY ("ADRESS_ID")
	  REFERENCES "ISI_ADRESSEN" ("ADRESS_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"a79b9bd80bd027d7a624a1274b5ef8888f5a793c","type":"REF_CONSTRAINT","name":"FK_ISI_HERSTELLER_ADR","schemaName":"DIRKSPZM32","sxml":""}