
  ALTER TABLE "ISI_KOMM_WEGE_ZEIT" ADD CONSTRAINT "FK_ISI_KOMM_WEGE_ZEIT_LAGERORT" FOREIGN KEY ("LGR_ORT_QUELLE")
	  REFERENCES "LVS_LGR_ORT" ("LGR_ORT") ENABLE;


-- sqlcl_snapshot {"hash":"87d8c702fe651a713cdd4e60bd516e62744816a4","type":"REF_CONSTRAINT","name":"FK_ISI_KOMM_WEGE_ZEIT_LAGERORT","schemaName":"DIRKSPZM32","sxml":""}