
  ALTER TABLE "ISI_KPI" ADD CONSTRAINT "FK_ISI_KPI" FOREIGN KEY ("KPI_NAME", "FIRMA_NR", "SID")
	  REFERENCES "ISI_KPI_CFG" ("KPI_NAME", "FIRMA_NR", "SID") ENABLE;


-- sqlcl_snapshot {"hash":"59a373e4ef4a6e5031980354c0f8f3bfce783c1b","type":"REF_CONSTRAINT","name":"FK_ISI_KPI","schemaName":"DIRKSPZM32","sxml":""}