
  ALTER TABLE "DIRKSPZM32"."ISI_ARTIKEL_HERSTELLER" ADD CONSTRAINT "FK_ISI_ARTIKEL_HERSTELLER_ADR" FOREIGN KEY ("ADRESS_ID")
	  REFERENCES "DIRKSPZM32"."ISI_ADRESSEN" ("ADRESS_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"429d411ce466117dddb08041ce69d56df71cf21b","type":"REF_CONSTRAINT","name":"FK_ISI_ARTIKEL_HERSTELLER_ADR","schemaName":"DIRKSPZM32","sxml":""}