
  ALTER TABLE "ISI_ARTIKEL_HERSTELLER" ADD CONSTRAINT "FK_ISI_ARTIKEL_HERSTELLER_ART" FOREIGN KEY ("ARTIKEL_ID")
	  REFERENCES "ISI_ARTIKEL" ("ARTIKEL_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"e2494eddb402f4d02579cacc20d44480b809f604","type":"REF_CONSTRAINT","name":"FK_ISI_ARTIKEL_HERSTELLER_ART","schemaName":"DIRKSPZM32","sxml":""}