
  ALTER TABLE "DIRKSPZM32"."ISI_ARTIKEL_HERSTELLER_WERK" ADD CONSTRAINT "FK_ISI_ARTIKEL_HERST_WERK_ADR" FOREIGN KEY ("ADRESS_ID")
	  REFERENCES "DIRKSPZM32"."ISI_ADRESSEN" ("ADRESS_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"5261b77d753605e5c9fdc35ab9ef4a02543d8675","type":"REF_CONSTRAINT","name":"FK_ISI_ARTIKEL_HERST_WERK_ADR","schemaName":"DIRKSPZM32","sxml":""}