
  ALTER TABLE "ISI_KOSTENSTELLEN" ADD CONSTRAINT "FK_KST_STANDARD_SM_NAME" FOREIGN KEY ("KST_STANDARD_SM_NAME")
	  REFERENCES "PZM_SCHICHT_MODELLE" ("SM_NAME") ENABLE;


-- sqlcl_snapshot {"hash":"d46f85b5c0fcfcd39fa8e6d392e5b89b1191c9f7","type":"REF_CONSTRAINT","name":"FK_KST_STANDARD_SM_NAME","schemaName":"DIRKSPZM32","sxml":""}