
  ALTER TABLE "ISI_KOMM_CLIENT_PLATZ" ADD CONSTRAINT "FK_KOMM_CLIENT_NAME" FOREIGN KEY ("KOMM_CLIENT_NAME")
	  REFERENCES "ISI_KOMM_CLIENT" ("KOMM_CLIENT_NAME") ENABLE;


-- sqlcl_snapshot {"hash":"b60bedf0ce4bfbef145356f8a843e37845ab7a9e","type":"REF_CONSTRAINT","name":"FK_KOMM_CLIENT_NAME","schemaName":"DIRKSPZM32","sxml":""}