
  ALTER TABLE "DIRKSPZM32"."PZM_ABWESENHEITSMELDUNGEN" ADD CONSTRAINT "FK_KM_ERZ_PERS_NR" FOREIGN KEY ("ERZ_PERS_NR")
	  REFERENCES "DIRKSPZM32"."PZM_PERSONAL" ("PERS_NR") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"67de130450ac2fbe6518cbec04abb2de5c7d1b8e","type":"REF_CONSTRAINT","name":"FK_KM_ERZ_PERS_NR","schemaName":"DIRKSPZM32","sxml":""}