
  ALTER TABLE "ISI_KOMM_ZEIT" ADD CONSTRAINT "FK_KOMM_ZEIT_RES" FOREIGN KEY ("BEARB_RES_ID")
	  REFERENCES "ISI_RESOURCE" ("RES_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"1e0aca84c8965b404bb28a17d3e5e0d80975b4fb","type":"REF_CONSTRAINT","name":"FK_KOMM_ZEIT_RES","schemaName":"DIRKSPZM32","sxml":""}