
  ALTER TABLE "DIRKSPZM32"."ISI_KOSTENSTELLEN" ADD CONSTRAINT "FK_KST_STANDARD_SM_NAME" FOREIGN KEY ("KST_STANDARD_SM_NAME")
	  REFERENCES "DIRKSPZM32"."PZM_SCHICHT_MODELLE" ("SM_NAME") ENABLE;


-- sqlcl_snapshot {"hash":"a6722ec73430d46927cfd778803dd78a7667ab62","type":"REF_CONSTRAINT","name":"FK_KST_STANDARD_SM_NAME","schemaName":"DIRKSPZM32","sxml":""}