
  ALTER TABLE "PZM_ABWESENHEITSMELDUNGEN" ADD CONSTRAINT "FK_KM_SA_KURZNAME" FOREIGN KEY ("SA_KURZNAME")
	  REFERENCES "PZM_SCHICHTARTEN" ("SA_KURZNAME") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"f111fe589ae56f0a4420df02bc6be9bd814b0fef","type":"REF_CONSTRAINT","name":"FK_KM_SA_KURZNAME","schemaName":"DIRKSPZM32","sxml":""}