
  ALTER TABLE "PZM_ABWESENHEITSMELDUNGEN" ADD CONSTRAINT "FK_KM_AEND_PERS_NR" FOREIGN KEY ("AEND_PERS_NR")
	  REFERENCES "PZM_PERSONAL" ("PERS_NR") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"4d2f8fa24d02d94ac64d357b90fb312c2eafaf53","type":"REF_CONSTRAINT","name":"FK_KM_AEND_PERS_NR","schemaName":"DIRKSPZM32","sxml":""}