
  ALTER TABLE "DIRKSPZM32"."ISI_KOMM_CLIENT_PLATZ" ADD CONSTRAINT "FK_KOMM_CLIENT_NAME" FOREIGN KEY ("KOMM_CLIENT_NAME")
	  REFERENCES "DIRKSPZM32"."ISI_KOMM_CLIENT" ("KOMM_CLIENT_NAME") ENABLE;


-- sqlcl_snapshot {"hash":"b918054ab84872ca8e0e77888098e5dc92b7f723","type":"REF_CONSTRAINT","name":"FK_KOMM_CLIENT_NAME","schemaName":"DIRKSPZM32","sxml":""}