
  ALTER TABLE "DIRKSPZM32"."PZM_ABWESENHEITSMELDUNGEN" ADD CONSTRAINT "FK_KM_SA_KURZNAME" FOREIGN KEY ("SA_KURZNAME")
	  REFERENCES "DIRKSPZM32"."PZM_SCHICHTARTEN" ("SA_KURZNAME") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"bcbed26b45f8af2fa8c9e0a3f41c70bd34d6b567","type":"REF_CONSTRAINT","name":"FK_KM_SA_KURZNAME","schemaName":"DIRKSPZM32","sxml":""}