
  ALTER TABLE "PZM_KONTEN" ADD CONSTRAINT "FK_KONTO_PERS" FOREIGN KEY ("PERS_NR")
	  REFERENCES "PZM_PERSONAL" ("PERS_NR") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"e1bbb6dd9443b62573f7ea53941aa25ac8788d05","type":"REF_CONSTRAINT","name":"FK_KONTO_PERS","schemaName":"DIRKSPZM32","sxml":""}