
  ALTER TABLE "LVS_PACKSCHEMA_POS" ADD CONSTRAINT "FK_LVS_PACKSCHEMA_POS" FOREIGN KEY ("PACKSCHEMA_KOPF_ID", "FIRMA_NR", "SID")
	  REFERENCES "LVS_PACKSCHEMA_KOPF" ("PACKSCHEMA_KOPF_ID", "FIRMA_NR", "SID") ENABLE;


-- sqlcl_snapshot {"hash":"da6e0514fc21841c8fe0dddba064744678ec0277","type":"REF_CONSTRAINT","name":"FK_LVS_PACKSCHEMA_POS","schemaName":"DIRKSPZM32","sxml":""}