
  ALTER TABLE "DIRKSPZM32"."LVS_PACKSCHEMA_KOPF" ADD CONSTRAINT "FK_LVS_PACKSCHEMA_KOPF_LHMNAME" FOREIGN KEY ("LHM_NAME", "SID")
	  REFERENCES "DIRKSPZM32"."LVS_LHM_CFG" ("LHM_NAME", "SID") ENABLE;


-- sqlcl_snapshot {"hash":"4f70ed222ed18df264257d5089a63a7c61967e67","type":"REF_CONSTRAINT","name":"FK_LVS_PACKSCHEMA_KOPF_LHMNAME","schemaName":"DIRKSPZM32","sxml":""}