
  ALTER TABLE "ISI_PURCH_LIEF_PLAN_ABR_KAL" ADD CONSTRAINT "FK_LIEF_PLAN_ABR_KAL" FOREIGN KEY ("LIEF_PLAN_ABRUF_ID")
	  REFERENCES "ISI_PURCH_LIEF_PLAN_ABRUF" ("LIEF_PLAN_ABRUF_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"3d0df4841fedb65eafe2f1cc91cf139d023bb2fc","type":"REF_CONSTRAINT","name":"FK_LIEF_PLAN_ABR_KAL","schemaName":"DIRKSPZM32","sxml":""}