
  ALTER TABLE "LVS_PACKSCHEMA_AUFBAU" ADD CONSTRAINT "FK_LVS_PACKSCHEMA_AUFBAU" FOREIGN KEY ("PACKSCHEMA_KOPF_ID", "FIRMA_NR", "SID")
	  REFERENCES "LVS_PACKSCHEMA_KOPF" ("PACKSCHEMA_KOPF_ID", "FIRMA_NR", "SID") ENABLE;


-- sqlcl_snapshot {"hash":"293f47165f8094bc21a5b1aae8dec5cd3e373e3f","type":"REF_CONSTRAINT","name":"FK_LVS_PACKSCHEMA_AUFBAU","schemaName":"DIRKSPZM32","sxml":""}