
  ALTER TABLE "DIRKSPZM32"."ISI_LAND_SPRACHE" ADD CONSTRAINT "FK_LANGUAGE" FOREIGN KEY ("LANG_ID")
	  REFERENCES "DIRKSPZM32"."ISI_LANGUAGE" ("LANG_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"ad121675000f09b6dfde2b04cfc12013729e5aed","type":"REF_CONSTRAINT","name":"FK_LANGUAGE","schemaName":"DIRKSPZM32","sxml":""}