
  ALTER TABLE "BDE_FA_AUFTRAG_LOG" ADD CONSTRAINT "FK_LEITZAHL" FOREIGN KEY ("LEITZAHL", "FA_AG", "FA_UPOS")
	  REFERENCES "BDE_FA_AUFTRAG" ("LEITZAHL", "FA_AG", "FA_UPOS") ENABLE;


-- sqlcl_snapshot {"hash":"f63748b94caf4749a9f696e877145db91956aa12","type":"REF_CONSTRAINT","name":"FK_LEITZAHL","schemaName":"DIRKSPZM32","sxml":""}