
  ALTER TABLE "DIRKSPZM32"."LVS_PACKSCHEMA_POS" ADD CONSTRAINT "FK_LVS_PACKSCHEMA_POS" FOREIGN KEY ("PACKSCHEMA_KOPF_ID", "FIRMA_NR", "SID")
	  REFERENCES "DIRKSPZM32"."LVS_PACKSCHEMA_KOPF" ("PACKSCHEMA_KOPF_ID", "FIRMA_NR", "SID") ENABLE;


-- sqlcl_snapshot {"hash":"e141085a67664e8af81aeb394742051ecb6146d9","type":"REF_CONSTRAINT","name":"FK_LVS_PACKSCHEMA_POS","schemaName":"DIRKSPZM32","sxml":""}