
  ALTER TABLE "DIRKSPZM32"."ISI_PURCH_LIEF_PLAN_ABRUF" ADD CONSTRAINT "FK_LIEF_PLAN_ABRUF_RV" FOREIGN KEY ("LIEF_PLAN_RV_ID")
	  REFERENCES "DIRKSPZM32"."ISI_PURCH_LIEF_PLAN_RV" ("LIEF_PLAN_RV_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"448f3196754eba99aa0c6f8687de526d5432cfa6","type":"REF_CONSTRAINT","name":"FK_LIEF_PLAN_ABRUF_RV","schemaName":"DIRKSPZM32","sxml":""}