
  ALTER TABLE "DIRKSPZM32"."LVS_PACKSCHEMA_KOPF" ADD CONSTRAINT "FK_LVS_PACKSCHEMA_KOPF_LTENAME" FOREIGN KEY ("LTE_NAME", "SID")
	  REFERENCES "DIRKSPZM32"."LVS_LTE_CFG" ("LTE_NAME", "SID") ENABLE;


-- sqlcl_snapshot {"hash":"5baa039076ca97633b2bce064132c06d250e2628","type":"REF_CONSTRAINT","name":"FK_LVS_PACKSCHEMA_KOPF_LTENAME","schemaName":"DIRKSPZM32","sxml":""}