
  ALTER TABLE "PZM_LZ_SA" ADD CONSTRAINT "FK_LZSA_SA_KURZNAME" FOREIGN KEY ("LZSA_SA_KURZNAME")
	  REFERENCES "PZM_SCHICHTARTEN" ("SA_KURZNAME") DISABLE;


-- sqlcl_snapshot {"hash":"b46f9557bb7f69cd573d463fa9cf4535bc480f0d","type":"REF_CONSTRAINT","name":"FK_LZSA_SA_KURZNAME","schemaName":"DIRKSPZM32","sxml":""}