
  ALTER TABLE "DIRKSPZM32"."BDE_FA_AUFTRAG_LOG" ADD CONSTRAINT "FK_LEITZAHL" FOREIGN KEY ("LEITZAHL", "FA_AG", "FA_UPOS")
	  REFERENCES "DIRKSPZM32"."BDE_FA_AUFTRAG" ("LEITZAHL", "FA_AG", "FA_UPOS") ENABLE;


-- sqlcl_snapshot {"hash":"d5f37c31d5cc0c362ad203fdf9af743e07409139","type":"REF_CONSTRAINT","name":"FK_LEITZAHL","schemaName":"DIRKSPZM32","sxml":""}