
  ALTER TABLE "DIRKSPZM32"."ISI_PURCH_LIEF_PLAN_ABR_KAL" ADD CONSTRAINT "FK_LIEF_PLAN_ABR_KAL" FOREIGN KEY ("LIEF_PLAN_ABRUF_ID")
	  REFERENCES "DIRKSPZM32"."ISI_PURCH_LIEF_PLAN_ABRUF" ("LIEF_PLAN_ABRUF_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"fc30680b9e4ea7a0a5711c2377ee831f722971d0","type":"REF_CONSTRAINT","name":"FK_LIEF_PLAN_ABR_KAL","schemaName":"DIRKSPZM32","sxml":""}