
  ALTER TABLE "LVS_PACKSCHEMA_KOPF" ADD CONSTRAINT "FK_LVS_PACKSCHEMA_KOPF_LTENAME" FOREIGN KEY ("LTE_NAME", "SID")
	  REFERENCES "LVS_LTE_CFG" ("LTE_NAME", "SID") ENABLE;


-- sqlcl_snapshot {"hash":"bf3d3d117db3db8cdc5d2f3addbe5942bbafa480","type":"REF_CONSTRAINT","name":"FK_LVS_PACKSCHEMA_KOPF_LTENAME","schemaName":"DIRKSPZM32","sxml":""}