
  ALTER TABLE "DIRKSPZM32"."LVS_FAHRZEUGE_LS_ID" ADD CONSTRAINT "FK_LVS_FAHRZEUGE_LS_ID_RES" FOREIGN KEY ("RES_ID")
	  REFERENCES "DIRKSPZM32"."LVS_FAHRZEUGE" ("RES_ID") ENABLE;


-- sqlcl_snapshot {"hash":"63052ed94205b3ad1487649d6f2a921f57fde0bf","type":"REF_CONSTRAINT","name":"FK_LVS_FAHRZEUGE_LS_ID_RES","schemaName":"DIRKSPZM32","sxml":""}