
  ALTER TABLE "ISI_PURCH_LIEF_PLAN_ABRUF" ADD CONSTRAINT "FK_LIEF_PLAN_ABRUF_RV" FOREIGN KEY ("LIEF_PLAN_RV_ID")
	  REFERENCES "ISI_PURCH_LIEF_PLAN_RV" ("LIEF_PLAN_RV_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"64c68667d90cc21e8af37405b24cca34d8174258","type":"REF_CONSTRAINT","name":"FK_LIEF_PLAN_ABRUF_RV","schemaName":"DIRKSPZM32","sxml":""}