
  ALTER TABLE "LVS_FAHRZEUGE_LS_ID" ADD CONSTRAINT "FK_LVS_FAHRZEUGE_LS_ID_RES" FOREIGN KEY ("RES_ID")
	  REFERENCES "LVS_FAHRZEUGE" ("RES_ID") ENABLE;


-- sqlcl_snapshot {"hash":"ebdbd9af0a02c0d3b74fd66fe30ce0f9f11a2bd3","type":"REF_CONSTRAINT","name":"FK_LVS_FAHRZEUGE_LS_ID_RES","schemaName":"DIRKSPZM32","sxml":""}