
  ALTER TABLE "LVS_PACKSCHEMA_KOPF" ADD CONSTRAINT "FK_LVS_PACKSCHEMA_KOPF_LHMNAME" FOREIGN KEY ("LHM_NAME", "SID")
	  REFERENCES "LVS_LHM_CFG" ("LHM_NAME", "SID") ENABLE;


-- sqlcl_snapshot {"hash":"dbcf5c6aa515f4ee2361fab3f6ed5c9acfe32a0d","type":"REF_CONSTRAINT","name":"FK_LVS_PACKSCHEMA_KOPF_LHMNAME","schemaName":"DIRKSPZM32","sxml":""}