
  ALTER TABLE "DIRKSPZM32"."LVS_PACKSCHEMA_AUFBAU" ADD CONSTRAINT "FK_LVS_PACKSCHEMA_AUFBAU" FOREIGN KEY ("PACKSCHEMA_KOPF_ID", "FIRMA_NR", "SID")
	  REFERENCES "DIRKSPZM32"."LVS_PACKSCHEMA_KOPF" ("PACKSCHEMA_KOPF_ID", "FIRMA_NR", "SID") ENABLE;


-- sqlcl_snapshot {"hash":"77e4ff5c1dafdb9c5ccc9af8549c5977a52ca32c","type":"REF_CONSTRAINT","name":"FK_LVS_PACKSCHEMA_AUFBAU","schemaName":"DIRKSPZM32","sxml":""}