
  ALTER TABLE "PZM_VORGANGSQUALIFIKATION_NACHWEIS" ADD CONSTRAINT "FK_NACHWEIS_VQ_ID" FOREIGN KEY ("VQ_ID")
	  REFERENCES "PZM_VORGANGSQUALIFIKATION" ("VQ_ID") ENABLE;


-- sqlcl_snapshot {"hash":"a4303a812b029ceab0878deec76c3855144cb603","type":"REF_CONSTRAINT","name":"FK_NACHWEIS_VQ_ID","schemaName":"DIRKSPZM32","sxml":""}