
  ALTER TABLE "DIRKSPZM32"."PZM_VORGANGSQUALIFIKATION_NACHWEIS" ADD CONSTRAINT "FK_NACHWEIS_VQ_ID" FOREIGN KEY ("VQ_ID")
	  REFERENCES "DIRKSPZM32"."PZM_VORGANGSQUALIFIKATION" ("VQ_ID") ENABLE;


-- sqlcl_snapshot {"hash":"1adb5dfe26f40ae469d4d334b03b7d47a6d0ac9d","type":"REF_CONSTRAINT","name":"FK_NACHWEIS_VQ_ID","schemaName":"DIRKSPZM32","sxml":""}