
  ALTER TABLE "DIRKSPZM32"."PZM_PERSONAL" ADD CONSTRAINT "FK_PERS_TARIF_NAME" FOREIGN KEY ("TARIF_NAME")
	  REFERENCES "DIRKSPZM32"."PZM_TARIFMODELLE" ("TARIF_NAME") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"82c071a6482aa9ee4e7eadb1e1a398c486200f4e","type":"REF_CONSTRAINT","name":"FK_PERS_TARIF_NAME","schemaName":"DIRKSPZM32","sxml":""}