
  ALTER TABLE "PPS_PRIORITAETSKURVE" ADD CONSTRAINT "FK_PPS_PRIORITÄTEN" FOREIGN KEY ("PRIO_ID")
	  REFERENCES "PPS_PRIORITAETEN" ("PRIO_ID") ENABLE;


-- sqlcl_snapshot {"hash":"57a7563e1cedfcafd6d27438467e1cf56d92b10c","type":"REF_CONSTRAINT","name":"FK_PPS_PRIORITÄTEN","schemaName":"DIRKSPZM32","sxml":""}