
  ALTER TABLE "PZM_PRODUKTIONSBEREICHE_BU" ADD CONSTRAINT "FK_PB_BU_ID" FOREIGN KEY ("BU_ID")
	  REFERENCES "PZM_PROD_BUSINESS_UNITS_BEREICHE" ("BU_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"230ef556321c533711bbe59d43bc306c3bc5452c","type":"REF_CONSTRAINT","name":"FK_PB_BU_ID","schemaName":"DIRKSPZM32","sxml":""}