
  ALTER TABLE "PZM_PERSONAL" ADD CONSTRAINT "FK_PERS_ABT_ID" FOREIGN KEY ("PERS_ABT_ID")
	  REFERENCES "PZM_ABTEILUNGEN" ("ABT_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"26cf57b63f07731d6d9f69ed6fe6b3e7efe8f543","type":"REF_CONSTRAINT","name":"FK_PERS_ABT_ID","schemaName":"DIRKSPZM32","sxml":""}