
  ALTER TABLE "PZM_KONTEN_UMBUCHEN" ADD CONSTRAINT "FK_PZM_KONTEN_UMBUCHEN_ABT_ID" FOREIGN KEY ("ABT_ID")
	  REFERENCES "PZM_ABTEILUNGEN" ("ABT_ID") ENABLE;


-- sqlcl_snapshot {"hash":"77fc981e3f732827179942cd4eb68ddd29c3157c","type":"REF_CONSTRAINT","name":"FK_PZM_KONTEN_UMBUCHEN_ABT_ID","schemaName":"DIRKSPZM32","sxml":""}