
  ALTER TABLE "DIRKSPZM32"."PZM_PERSONAL" ADD CONSTRAINT "FK_PERS_ABT_ID" FOREIGN KEY ("PERS_ABT_ID")
	  REFERENCES "DIRKSPZM32"."PZM_ABTEILUNGEN" ("ABT_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"9b589c1c4d0d194ddb6ae226a6358fc78c775272","type":"REF_CONSTRAINT","name":"FK_PERS_ABT_ID","schemaName":"DIRKSPZM32","sxml":""}