
  ALTER TABLE "DIRKSPZM32"."PZM_PRODUKTIONSBEREICHE_BU" ADD CONSTRAINT "FK_PB_BU_ID" FOREIGN KEY ("BU_ID")
	  REFERENCES "DIRKSPZM32"."PZM_PROD_BUSINESS_UNITS_BEREICHE" ("BU_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"7af697f73ce5ef2ff36801ca72037ec0715eabdd","type":"REF_CONSTRAINT","name":"FK_PB_BU_ID","schemaName":"DIRKSPZM32","sxml":""}