
  ALTER TABLE "PZM_PERSONAL" ADD CONSTRAINT "FK_PERS_TARIF_NAME" FOREIGN KEY ("TARIF_NAME")
	  REFERENCES "PZM_TARIFMODELLE" ("TARIF_NAME") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"5d7086993745584fd088f3914af739b97c0d2f8b","type":"REF_CONSTRAINT","name":"FK_PERS_TARIF_NAME","schemaName":"DIRKSPZM32","sxml":""}