
  ALTER TABLE "DIRKSPZM32"."PZM_PRODUKTIONSBEREICHE" ADD CONSTRAINT "FK_PB_KST_ID" FOREIGN KEY ("PB_KST_ID")
	  REFERENCES "DIRKSPZM32"."ISI_KOSTENSTELLEN" ("KST_NR") DISABLE;


-- sqlcl_snapshot {"hash":"06a6af9e8e9c8193f4b9e686103290bfa3fcae0c","type":"REF_CONSTRAINT","name":"FK_PB_KST_ID","schemaName":"DIRKSPZM32","sxml":""}