
  ALTER TABLE "DIRKSPZM32"."PZM_PERS_LOHN_ZULAGEN" ADD CONSTRAINT "FK_PZM_PERS_LOHN_ZULAGEN_LZ_ID" FOREIGN KEY ("LZ_ID")
	  REFERENCES "DIRKSPZM32"."PZM_LOHNARTEN" ("LZ_ID") ON DELETE CASCADE DISABLE;


-- sqlcl_snapshot {"hash":"73fcb9280171a7c04becc31e3626485d5a2f4d7c","type":"REF_CONSTRAINT","name":"FK_PZM_PERS_LOHN_ZULAGEN_LZ_ID","schemaName":"DIRKSPZM32","sxml":""}