
  ALTER TABLE "DIRKSPZM32"."PZM_PRODUKTIONSBEREICHE" ADD CONSTRAINT "FK_PB_PERSONAL_ABT_ID" FOREIGN KEY ("PB_PERSONAL_ABT_ID")
	  REFERENCES "DIRKSPZM32"."PZM_ABTEILUNGEN" ("ABT_ID") DISABLE;


-- sqlcl_snapshot {"hash":"f32fbe08b4f7002aca6130a9173e140be04d7ec6","type":"REF_CONSTRAINT","name":"FK_PB_PERSONAL_ABT_ID","schemaName":"DIRKSPZM32","sxml":""}