
  ALTER TABLE "DIRKSPZM32"."ISI_PURCH_KOPF" ADD CONSTRAINT "FK_PURCH_KOPF_KUNDE" FOREIGN KEY ("KUNDE_ID")
	  REFERENCES "DIRKSPZM32"."ISI_ADRESSEN" ("ADRESS_ID") ENABLE;


-- sqlcl_snapshot {"hash":"7d000a11e8ee8597da824808e6e1c294bb2432e5","type":"REF_CONSTRAINT","name":"FK_PURCH_KOPF_KUNDE","schemaName":"DIRKSPZM32","sxml":""}