
  ALTER TABLE "PZM_PRODUKTIONSBEREICHE" ADD CONSTRAINT "FK_PB_ADRESS_ID" FOREIGN KEY ("PB_ADRESS_ID")
	  REFERENCES "ISI_ADRESSEN" ("ADRESS_ID") DISABLE;


-- sqlcl_snapshot {"hash":"9808502ec868151aaf45c9c594e6f08d0088e8ad","type":"REF_CONSTRAINT","name":"FK_PB_ADRESS_ID","schemaName":"DIRKSPZM32","sxml":""}