
  ALTER TABLE "PZM_VORGANGSQUALIFIKATION_PERS" ADD CONSTRAINT "FK_PERS_VQ_ID" FOREIGN KEY ("PERS_VQ_ID")
	  REFERENCES "PZM_VORGANGSQUALIFIKATION" ("VQ_ID") ENABLE;


-- sqlcl_snapshot {"hash":"1e91445781bcc94d3328d41a1fe2c41dc6ef040c","type":"REF_CONSTRAINT","name":"FK_PERS_VQ_ID","schemaName":"DIRKSPZM32","sxml":""}