
  ALTER TABLE "ISI_PURCH_POS" ADD CONSTRAINT "FK_PURCH_POS_LIEF_PL_KAL" FOREIGN KEY ("LIEF_PLAN_ABR_KAL_ID")
	  REFERENCES "ISI_PURCH_LIEF_PLAN_ABR_KAL" ("LIEF_PLAN_ABR_KAL_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"f68f41b0743ab00fcbb17bb75fede02db6a5c620","type":"REF_CONSTRAINT","name":"FK_PURCH_POS_LIEF_PL_KAL","schemaName":"DIRKSPZM32","sxml":""}