
  ALTER TABLE "PZM_PRODUKTIONSBEREICHE" ADD CONSTRAINT "FK_PB_KST_ID" FOREIGN KEY ("PB_KST_ID")
	  REFERENCES "ISI_KOSTENSTELLEN" ("KST_NR") DISABLE;


-- sqlcl_snapshot {"hash":"34b7f2cbd4dc5fa4c8914b5151424895499d95b8","type":"REF_CONSTRAINT","name":"FK_PB_KST_ID","schemaName":"DIRKSPZM32","sxml":""}