
  ALTER TABLE "ISI_PURCH_POS" ADD CONSTRAINT "FK_PURCH_POS_PARENT_POS" FOREIGN KEY ("KOPF_ID", "PARENT_POS")
	  REFERENCES "ISI_PURCH_POS" ("KOPF_ID", "POS") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"48f5d72a86ca6bd9a48485cbee1128dda763e24e","type":"REF_CONSTRAINT","name":"FK_PURCH_POS_PARENT_POS","schemaName":"DIRKSPZM32","sxml":""}