
  ALTER TABLE "PZM_VORGANGSQUAL_EINSATZ_PLAN" ADD CONSTRAINT "FK_PLAN_VQ_ID" FOREIGN KEY ("PLAN_VQ_ID")
	  REFERENCES "PZM_VORGANGSQUALIFIKATION" ("VQ_ID") ENABLE;


-- sqlcl_snapshot {"hash":"451663de4f445631b45128b04b8c8e9f0b47286e","type":"REF_CONSTRAINT","name":"FK_PLAN_VQ_ID","schemaName":"DIRKSPZM32","sxml":""}