
  ALTER TABLE "DIRKSPZM32"."PZM_PERSONAL" ADD CONSTRAINT "FK_PERS_REGION_CODE" FOREIGN KEY ("PERS_REGION_CODE")
	  REFERENCES "DIRKSPZM32"."ISI_LAND_REGION" ("CODE") DISABLE;


-- sqlcl_snapshot {"hash":"6b50e7c35c42c862c03ec2c019fe1761329b7b88","type":"REF_CONSTRAINT","name":"FK_PERS_REGION_CODE","schemaName":"DIRKSPZM32","sxml":""}