
  ALTER TABLE "PZM_PERS_LOHN_ZULAGEN" ADD CONSTRAINT "FK_PZM_PERS_LOHN_ZULAGEN_PERS_NR" FOREIGN KEY ("PERS_NR")
	  REFERENCES "PZM_PERSONAL" ("PERS_NR") ON DELETE CASCADE DISABLE;


-- sqlcl_snapshot {"hash":"bfc8b8a72799051c25faa3a2b5bb9d4ef5353b77","type":"REF_CONSTRAINT","name":"FK_PZM_PERS_LOHN_ZULAGEN_PERS_NR","schemaName":"DIRKSPZM32","sxml":""}