
  ALTER TABLE "PZM_PERS_LOHN_ZULAGEN" ADD CONSTRAINT "FK_PZM_PERS_LOHN_ZULAGEN_LZ_ID" FOREIGN KEY ("LZ_ID")
	  REFERENCES "PZM_LOHNARTEN" ("LZ_ID") ON DELETE CASCADE DISABLE;


-- sqlcl_snapshot {"hash":"54c9eb5b8b8f773a15f8ac08483e50f79a934ed8","type":"REF_CONSTRAINT","name":"FK_PZM_PERS_LOHN_ZULAGEN_LZ_ID","schemaName":"DIRKSPZM32","sxml":""}