
  ALTER TABLE "PZM_PRODUKTIONSBEREICHE" ADD CONSTRAINT "FK_PB_PERSONAL_ABT_ID" FOREIGN KEY ("PB_PERSONAL_ABT_ID")
	  REFERENCES "PZM_ABTEILUNGEN" ("ABT_ID") DISABLE;


-- sqlcl_snapshot {"hash":"579d7840aa5a0d39d81e3448b040397701442b4a","type":"REF_CONSTRAINT","name":"FK_PB_PERSONAL_ABT_ID","schemaName":"DIRKSPZM32","sxml":""}