
  ALTER TABLE "PZM_ZE_AZK_URLAUB" ADD CONSTRAINT "FK_PZM_ZE_AZK_URLAUB_KST" FOREIGN KEY ("PERS_KST_ID")
	  REFERENCES "ISI_KOSTENSTELLEN" ("KST_NR") DISABLE;


-- sqlcl_snapshot {"hash":"df073d66cbebee3bcebc483cd95ebbda99c15de0","type":"REF_CONSTRAINT","name":"FK_PZM_ZE_AZK_URLAUB_KST","schemaName":"DIRKSPZM32","sxml":""}