
  ALTER TABLE "PZM_BEREITSCHAFT_PLAN" ADD CONSTRAINT "FK_PZM_BEREITSCHAFT_PLAN_CFG" FOREIGN KEY ("BEREITSCHAFT_CFG")
	  REFERENCES "PZM_BEREITSCHAFT_CFG" ("BEREITSCHAFT_CFG") ENABLE;


-- sqlcl_snapshot {"hash":"2d059e9d8a73c25975502b0a346b7101ae6c8b85","type":"REF_CONSTRAINT","name":"FK_PZM_BEREITSCHAFT_PLAN_CFG","schemaName":"DIRKSPZM32","sxml":""}