
  ALTER TABLE "PZM_PRODUKTIONSBEREICHE_BU" ADD CONSTRAINT "FK_PB_BU_PB_ID" FOREIGN KEY ("PB_ID")
	  REFERENCES "PZM_PRODUKTIONSBEREICHE" ("PB_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"1ff3c5617a1b6bc879ed2c53be40159124f2fef4","type":"REF_CONSTRAINT","name":"FK_PB_BU_PB_ID","schemaName":"DIRKSPZM32","sxml":""}