
  ALTER TABLE "PZM_ZEITERFASSUNG_EINTRAEGE" ADD CONSTRAINT "FK_PZM_ZEITERFASSUNG_EINTRAEGE_ZE_ID" FOREIGN KEY ("ZE_ID")
	  REFERENCES "PZM_ZEITERFASSUNG" ("ZE_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"b72ff2b60db06922aefa2180b3c764a49e7dda9a","type":"REF_CONSTRAINT","name":"FK_PZM_ZEITERFASSUNG_EINTRAEGE_ZE_ID","schemaName":"DIRKSPZM32","sxml":""}