
  ALTER TABLE "DIRKSPZM32"."ISI_PURCH_POS" ADD CONSTRAINT "FK_PURCH_POS_LIEF_PL_KAL" FOREIGN KEY ("LIEF_PLAN_ABR_KAL_ID")
	  REFERENCES "DIRKSPZM32"."ISI_PURCH_LIEF_PLAN_ABR_KAL" ("LIEF_PLAN_ABR_KAL_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"507cac98fa6629e3d53415a3dd7e74c5cc9162d9","type":"REF_CONSTRAINT","name":"FK_PURCH_POS_LIEF_PL_KAL","schemaName":"DIRKSPZM32","sxml":""}