
  ALTER TABLE "PZM_PERSONAL" ADD CONSTRAINT "FK_PERS_PB_ID" FOREIGN KEY ("PERS_PB_ID")
	  REFERENCES "PZM_PRODUKTIONSBEREICHE" ("PB_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"40c27f588983baa256ca01bac30d88d99dd967e8","type":"REF_CONSTRAINT","name":"FK_PERS_PB_ID","schemaName":"DIRKSPZM32","sxml":""}