
  ALTER TABLE "DIRKSPZM32"."PZM_VORGANGSQUALIFIKATION_PERS" ADD CONSTRAINT "FK_PERS_VQ_ID" FOREIGN KEY ("PERS_VQ_ID")
	  REFERENCES "DIRKSPZM32"."PZM_VORGANGSQUALIFIKATION" ("VQ_ID") ENABLE;


-- sqlcl_snapshot {"hash":"ab527c1de7730a2d4102a53805dc1e45a463ddbe","type":"REF_CONSTRAINT","name":"FK_PERS_VQ_ID","schemaName":"DIRKSPZM32","sxml":""}