
  ALTER TABLE "PZM_ZE_LOA_13W_SCHNITT" ADD CONSTRAINT "FK_PZM_ZE_LOA_13W_PERS_NR" FOREIGN KEY ("PERS_NR")
	  REFERENCES "PZM_PERSONAL" ("PERS_NR") ON DELETE CASCADE DISABLE;


-- sqlcl_snapshot {"hash":"7d3da4e587fe33651f08e031b74b47cdeb1a1303","type":"REF_CONSTRAINT","name":"FK_PZM_ZE_LOA_13W_PERS_NR","schemaName":"DIRKSPZM32","sxml":""}