
  ALTER TABLE "DIRKSPZM32"."PZM_BEREITSCHAFT_PLAN" ADD CONSTRAINT "FK_PZM_BEREITSCHAFT_PLAN_CFG" FOREIGN KEY ("BEREITSCHAFT_CFG")
	  REFERENCES "DIRKSPZM32"."PZM_BEREITSCHAFT_CFG" ("BEREITSCHAFT_CFG") ENABLE;


-- sqlcl_snapshot {"hash":"d2ec57b63cee719e1e632c547b4a38effccf4006","type":"REF_CONSTRAINT","name":"FK_PZM_BEREITSCHAFT_PLAN_CFG","schemaName":"DIRKSPZM32","sxml":""}