
  ALTER TABLE "DIRKSPZM32"."PZM_ZEITERFASSUNG_EINTRAEGE" ADD CONSTRAINT "FK_PZM_ZEITERFASSUNG_EINTRAEGE_ZE_ID" FOREIGN KEY ("ZE_ID")
	  REFERENCES "DIRKSPZM32"."PZM_ZEITERFASSUNG" ("ZE_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"85540b61536b0e7fbdb37362168f15e7511e99b5","type":"REF_CONSTRAINT","name":"FK_PZM_ZEITERFASSUNG_EINTRAEGE_ZE_ID","schemaName":"DIRKSPZM32","sxml":""}