
  ALTER TABLE "DIRKSPZM32"."PPS_PRIORITAETSKURVE" ADD CONSTRAINT "FK_PPS_PRIORITÄTEN" FOREIGN KEY ("PRIO_ID")
	  REFERENCES "DIRKSPZM32"."PPS_PRIORITAETEN" ("PRIO_ID") ENABLE;


-- sqlcl_snapshot {"hash":"bfd79afa87d575b6343d27fb76114b1b4fd0977a","type":"REF_CONSTRAINT","name":"FK_PPS_PRIORITÄTEN","schemaName":"DIRKSPZM32","sxml":""}