
  ALTER TABLE "DIRKSPZM32"."PZM_PERSONAL" ADD CONSTRAINT "FK_PERS_PB_ID" FOREIGN KEY ("PERS_PB_ID")
	  REFERENCES "DIRKSPZM32"."PZM_PRODUKTIONSBEREICHE" ("PB_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"dc2df1e4f95c25e46906d8bb054ee330b27b33bc","type":"REF_CONSTRAINT","name":"FK_PERS_PB_ID","schemaName":"DIRKSPZM32","sxml":""}