
  ALTER TABLE "DIRKSPZM32"."PZM_BEREITSCHAFT_PLAN" ADD CONSTRAINT "FK_PZM_BEREITSCHAFT_PLAN_PERS_NR" FOREIGN KEY ("PERS_NR")
	  REFERENCES "DIRKSPZM32"."PZM_PERSONAL" ("PERS_NR") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"fa2c56484cf737372e8917778e368b68c469be87","type":"REF_CONSTRAINT","name":"FK_PZM_BEREITSCHAFT_PLAN_PERS_NR","schemaName":"DIRKSPZM32","sxml":""}