
  ALTER TABLE "DIRKSPZM32"."PZM_KONTEN_UMBUCHEN" ADD CONSTRAINT "FK_PZM_KONTEN_UMBUCHEN_ABT_ID" FOREIGN KEY ("ABT_ID")
	  REFERENCES "DIRKSPZM32"."PZM_ABTEILUNGEN" ("ABT_ID") ENABLE;


-- sqlcl_snapshot {"hash":"72fad188ec5b71e9b035c21710be3fcffd27d8e2","type":"REF_CONSTRAINT","name":"FK_PZM_KONTEN_UMBUCHEN_ABT_ID","schemaName":"DIRKSPZM32","sxml":""}