
  ALTER TABLE "DIRKSPZM32"."PZM_VORGANGSQUAL_EINSATZ_PLAN" ADD CONSTRAINT "FK_PLAN_VQ_ID" FOREIGN KEY ("PLAN_VQ_ID")
	  REFERENCES "DIRKSPZM32"."PZM_VORGANGSQUALIFIKATION" ("VQ_ID") ENABLE;


-- sqlcl_snapshot {"hash":"8ef9d779eabdcf397ed6cd03e6940053c589ce88","type":"REF_CONSTRAINT","name":"FK_PLAN_VQ_ID","schemaName":"DIRKSPZM32","sxml":""}