
  ALTER TABLE "ISI_RAVE_REPORTS_CFG" ADD CONSTRAINT "FK_RV_REP_PROJEKT" FOREIGN KEY ("SID", "FIRMA_NR", "KATEGORIE", "RAVE_PROJEKT")
	  REFERENCES "ISI_RAVE_PROJEKTE_CFG" ("SID", "FIRMA_NR", "KATEGORIE", "RAVE_PROJEKT") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"1b97b3b9d7d948bff62bf466dfb47aa0ab1c3cba","type":"REF_CONSTRAINT","name":"FK_RV_REP_PROJEKT","schemaName":"DIRKSPZM32","sxml":""}