
  ALTER TABLE "DIRKSPZM32"."ISI_RAVE_REPORTS_CFG" ADD CONSTRAINT "FK_RV_REP_PROJEKT" FOREIGN KEY ("SID", "FIRMA_NR", "KATEGORIE", "RAVE_PROJEKT")
	  REFERENCES "DIRKSPZM32"."ISI_RAVE_PROJEKTE_CFG" ("SID", "FIRMA_NR", "KATEGORIE", "RAVE_PROJEKT") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"d18cf30551173beb7cbd719fe6201eb73acf7740","type":"REF_CONSTRAINT","name":"FK_RV_REP_PROJEKT","schemaName":"DIRKSPZM32","sxml":""}