
  ALTER TABLE "ISI_RESOURCE" ADD CONSTRAINT "FK_RES_LAGER_ROH" FOREIGN KEY ("LAGER_ROH")
	  REFERENCES "LVS_LGR" ("LGR_PLATZ") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"2e9a1ddad2a3830d28d8d5bf98885cbbbb75912e","type":"REF_CONSTRAINT","name":"FK_RES_LAGER_ROH","schemaName":"DIRKSPZM32","sxml":""}