
  ALTER TABLE "ISI_ADRESSEN" ADD CONSTRAINT "FK_REGION_CODE" FOREIGN KEY ("REGION_CODE")
	  REFERENCES "ISI_LAND_REGION" ("CODE") ENABLE;


-- sqlcl_snapshot {"hash":"04a493e4ed76b0af63a4f0c520e4e2034989b8eb","type":"REF_CONSTRAINT","name":"FK_REGION_CODE","schemaName":"DIRKSPZM32","sxml":""}