
  ALTER TABLE "DIRKSPZM32"."ISI_LAND_SPRACHE" ADD CONSTRAINT "FK_REGION" FOREIGN KEY ("REGION_ID")
	  REFERENCES "DIRKSPZM32"."ISI_LAND_REGION" ("REGION_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"7cbb202f9fae5638b02f9f97dbebc743b27cfd42","type":"REF_CONSTRAINT","name":"FK_REGION","schemaName":"DIRKSPZM32","sxml":""}