
  ALTER TABLE "ISI_LAND_SPRACHE" ADD CONSTRAINT "FK_REGION" FOREIGN KEY ("REGION_ID")
	  REFERENCES "ISI_LAND_REGION" ("REGION_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"e814842955e11470f06d44e73f9defdec0f44805","type":"REF_CONSTRAINT","name":"FK_REGION","schemaName":"DIRKSPZM32","sxml":""}