
  ALTER TABLE "DIRKSPZM32"."ISI_RESOURCE" ADD CONSTRAINT "FK_RES_LAGER_FERTIG" FOREIGN KEY ("LAGER_FERTIG")
	  REFERENCES "DIRKSPZM32"."LVS_LGR" ("LGR_PLATZ") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"6dc6648cb0139d73d9f8d8566abcd7500a379ee7","type":"REF_CONSTRAINT","name":"FK_RES_LAGER_FERTIG","schemaName":"DIRKSPZM32","sxml":""}