
  ALTER TABLE "DIRKSPZM32"."ISI_RESOURCE" ADD CONSTRAINT "FK_RES_LAGER_ROH" FOREIGN KEY ("LAGER_ROH")
	  REFERENCES "DIRKSPZM32"."LVS_LGR" ("LGR_PLATZ") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"3da2e7d496f6f6c4752220a77bbfe7fcd06023c3","type":"REF_CONSTRAINT","name":"FK_RES_LAGER_ROH","schemaName":"DIRKSPZM32","sxml":""}