
  ALTER TABLE "DIRKSPZM32"."PZM_SCHICHT_PERIODEN" ADD CONSTRAINT "FK_SP_SA_WOT_DO" FOREIGN KEY ("SP_SA_WOT_DO")
	  REFERENCES "DIRKSPZM32"."PZM_SCHICHTARTEN" ("SA_KURZNAME") DISABLE;


-- sqlcl_snapshot {"hash":"93e5b131d29c8efe8cceb0f5a084e878acace591","type":"REF_CONSTRAINT","name":"FK_SP_SA_WOT_DO","schemaName":"DIRKSPZM32","sxml":""}