
  ALTER TABLE "DIRKSPZM32"."PZM_SCHICHT_PERIODEN" ADD CONSTRAINT "FK_SP_SA_WOT_FR" FOREIGN KEY ("SP_SA_WOT_FR")
	  REFERENCES "DIRKSPZM32"."PZM_SCHICHTARTEN" ("SA_KURZNAME") DISABLE;


-- sqlcl_snapshot {"hash":"c7eb9818e6215a416bcdc1d1bb1e20d569f0c7e4","type":"REF_CONSTRAINT","name":"FK_SP_SA_WOT_FR","schemaName":"DIRKSPZM32","sxml":""}