
  ALTER TABLE "SEC_GROUP_ACTIONS" ADD CONSTRAINT "FK_SEC_GA_GROUP_ID" FOREIGN KEY ("SID", "GROUP_ID")
	  REFERENCES "SEC_GROUPS" ("SID", "GROUP_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"b42cfdd056ecb458a89a822263bfa8d5db2e56ac","type":"REF_CONSTRAINT","name":"FK_SEC_GA_GROUP_ID","schemaName":"DIRKSPZM32","sxml":""}