
  ALTER TABLE "SEC_GROUP_MODULES" ADD CONSTRAINT "FK_SEC_GM_GROUP_ID" FOREIGN KEY ("SID", "GROUP_ID")
	  REFERENCES "SEC_GROUPS" ("SID", "GROUP_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"1550f7c48b7ec47c7f3213a56b9e8b5935448b5b","type":"REF_CONSTRAINT","name":"FK_SEC_GM_GROUP_ID","schemaName":"DIRKSPZM32","sxml":""}