
  ALTER TABLE "PZM_SCHICHT_PERIODEN" ADD CONSTRAINT "FK_SP_SA_WOT_MI" FOREIGN KEY ("SP_SA_WOT_MI")
	  REFERENCES "PZM_SCHICHTARTEN" ("SA_KURZNAME") DISABLE;


-- sqlcl_snapshot {"hash":"fdba2df7ae224002a0375f2c1b83c2bcbb0319b2","type":"REF_CONSTRAINT","name":"FK_SP_SA_WOT_MI","schemaName":"DIRKSPZM32","sxml":""}