
  ALTER TABLE "PZM_SCHICHT_PERIODEN" ADD CONSTRAINT "FK_SP_SA_WOT_DI" FOREIGN KEY ("SP_SA_WOT_DI")
	  REFERENCES "PZM_SCHICHTARTEN" ("SA_KURZNAME") DISABLE;


-- sqlcl_snapshot {"hash":"57bddbc1befcf5e4c5e179d7c5463126cf923697","type":"REF_CONSTRAINT","name":"FK_SP_SA_WOT_DI","schemaName":"DIRKSPZM32","sxml":""}