
  ALTER TABLE "PZM_SCHICHT_PERIODEN" ADD CONSTRAINT "FK_SP_SA_WOT_DO" FOREIGN KEY ("SP_SA_WOT_DO")
	  REFERENCES "PZM_SCHICHTARTEN" ("SA_KURZNAME") DISABLE;


-- sqlcl_snapshot {"hash":"041480d33bb4287a5f740357cd6a23f6b1c990bf","type":"REF_CONSTRAINT","name":"FK_SP_SA_WOT_DO","schemaName":"DIRKSPZM32","sxml":""}