
  ALTER TABLE "DIRKSPZM32"."SEC_GROUP_SECTIONS" ADD CONSTRAINT "FK_SEC_GS_GROUP_ID" FOREIGN KEY ("SID", "GROUP_ID")
	  REFERENCES "DIRKSPZM32"."SEC_GROUPS" ("SID", "GROUP_ID") ENABLE;


-- sqlcl_snapshot {"hash":"1858cda1f0bcc1fddde49b575f55f15945e870f8","type":"REF_CONSTRAINT","name":"FK_SEC_GS_GROUP_ID","schemaName":"DIRKSPZM32","sxml":""}