
  ALTER TABLE "DIRKSPZM32"."PZM_SCHICHT_PERIODEN" ADD CONSTRAINT "FK_SP_SA_WOT_DI" FOREIGN KEY ("SP_SA_WOT_DI")
	  REFERENCES "DIRKSPZM32"."PZM_SCHICHTARTEN" ("SA_KURZNAME") DISABLE;


-- sqlcl_snapshot {"hash":"dbefc8dfbee0e1910d896335166082f59d03421b","type":"REF_CONSTRAINT","name":"FK_SP_SA_WOT_DI","schemaName":"DIRKSPZM32","sxml":""}