
  ALTER TABLE "DIRKSPZM32"."PZM_SCHICHT_PERIODEN" ADD CONSTRAINT "FK_SP_SM_NAME" FOREIGN KEY ("SP_SM_NAME")
	  REFERENCES "DIRKSPZM32"."PZM_SCHICHT_MODELLE" ("SM_NAME") DISABLE;


-- sqlcl_snapshot {"hash":"617e92fad8ed46dabeed9a36099cc911d08685e8","type":"REF_CONSTRAINT","name":"FK_SP_SM_NAME","schemaName":"DIRKSPZM32","sxml":""}