
  ALTER TABLE "SEC_GROUP_SECTIONS" ADD CONSTRAINT "FK_SEC_GS_GROUP_ID" FOREIGN KEY ("SID", "GROUP_ID")
	  REFERENCES "SEC_GROUPS" ("SID", "GROUP_ID") ENABLE;


-- sqlcl_snapshot {"hash":"f15450aa20f19d7688a30629dad3a7a1b1e25dac","type":"REF_CONSTRAINT","name":"FK_SEC_GS_GROUP_ID","schemaName":"DIRKSPZM32","sxml":""}