
  ALTER TABLE "PZM_SCHICHT_PERIODEN" ADD CONSTRAINT "FK_SP_SA_WOT_SA" FOREIGN KEY ("SP_SA_WOT_SA")
	  REFERENCES "PZM_SCHICHTARTEN" ("SA_KURZNAME") DISABLE;


-- sqlcl_snapshot {"hash":"beba142be726908b06f9e2d7055057a56178cefd","type":"REF_CONSTRAINT","name":"FK_SP_SA_WOT_SA","schemaName":"DIRKSPZM32","sxml":""}