
  ALTER TABLE "DIRKSPZM32"."SEC_GROUP_ACTIONS" ADD CONSTRAINT "FK_SEC_GA_GROUP_ID" FOREIGN KEY ("SID", "GROUP_ID")
	  REFERENCES "DIRKSPZM32"."SEC_GROUPS" ("SID", "GROUP_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"b766173a1909813c36a782fab1df7d9ea522b386","type":"REF_CONSTRAINT","name":"FK_SEC_GA_GROUP_ID","schemaName":"DIRKSPZM32","sxml":""}