
  ALTER TABLE "DIRKSPZM32"."PZM_SCHICHT_PERIODEN" ADD CONSTRAINT "FK_SP_SA_WOT_MI" FOREIGN KEY ("SP_SA_WOT_MI")
	  REFERENCES "DIRKSPZM32"."PZM_SCHICHTARTEN" ("SA_KURZNAME") DISABLE;


-- sqlcl_snapshot {"hash":"88c84fb1dde4181bf590a7cef9dafd7cb8274be6","type":"REF_CONSTRAINT","name":"FK_SP_SA_WOT_MI","schemaName":"DIRKSPZM32","sxml":""}