
  ALTER TABLE "DIRKSPZM32"."LVS_SERIE_ID_POS" ADD CONSTRAINT "FK_SERIE_ID" FOREIGN KEY ("SERIE_ID")
	  REFERENCES "DIRKSPZM32"."LVS_SERIE_ID_KOPF" ("SERIE_ID") ON DELETE SET NULL ENABLE;


-- sqlcl_snapshot {"hash":"f8cfd1e7a1001ae41a01ecd89844ff4ad460cdcc","type":"REF_CONSTRAINT","name":"FK_SERIE_ID","schemaName":"DIRKSPZM32","sxml":""}