
  ALTER TABLE "PZM_SCHICHT_PERIODEN" ADD CONSTRAINT "FK_SP_SA_WOT_FR" FOREIGN KEY ("SP_SA_WOT_FR")
	  REFERENCES "PZM_SCHICHTARTEN" ("SA_KURZNAME") DISABLE;


-- sqlcl_snapshot {"hash":"2496e7ee35857ab562d7b59a9d24cfc05ccebd00","type":"REF_CONSTRAINT","name":"FK_SP_SA_WOT_FR","schemaName":"DIRKSPZM32","sxml":""}