
  ALTER TABLE "PZM_SCHICHT_PERIODEN" ADD CONSTRAINT "FK_SP_SA_WOT_MO" FOREIGN KEY ("SP_SA_WOT_MO")
	  REFERENCES "PZM_SCHICHTARTEN" ("SA_KURZNAME") DISABLE;


-- sqlcl_snapshot {"hash":"be64050d01c3ce6cfef00c1edb9485b87e604a49","type":"REF_CONSTRAINT","name":"FK_SP_SA_WOT_MO","schemaName":"DIRKSPZM32","sxml":""}