
  ALTER TABLE "DIRKSPZM32"."PZM_SCHICHT_PERIODEN" ADD CONSTRAINT "FK_SP_SA_WOT_MO" FOREIGN KEY ("SP_SA_WOT_MO")
	  REFERENCES "DIRKSPZM32"."PZM_SCHICHTARTEN" ("SA_KURZNAME") DISABLE;


-- sqlcl_snapshot {"hash":"fe2ed6f15b85a493ffb37fff1c5bb76c2df5d958","type":"REF_CONSTRAINT","name":"FK_SP_SA_WOT_MO","schemaName":"DIRKSPZM32","sxml":""}