
  ALTER TABLE "PZM_SCHICHT_PERIODEN" ADD CONSTRAINT "FK_SP_SM_NAME" FOREIGN KEY ("SP_SM_NAME")
	  REFERENCES "PZM_SCHICHT_MODELLE" ("SM_NAME") DISABLE;


-- sqlcl_snapshot {"hash":"2e9353b3dc6cc180202283196e5fbc48182c257c","type":"REF_CONSTRAINT","name":"FK_SP_SM_NAME","schemaName":"DIRKSPZM32","sxml":""}