
  ALTER TABLE "DIRKSPZM32"."SEC_GROUP_MODULES" ADD CONSTRAINT "FK_SEC_GM_GROUP_ID" FOREIGN KEY ("SID", "GROUP_ID")
	  REFERENCES "DIRKSPZM32"."SEC_GROUPS" ("SID", "GROUP_ID") ON DELETE CASCADE ENABLE;


-- sqlcl_snapshot {"hash":"33caab567112c6266e5c89ab2c5bb10a40684026","type":"REF_CONSTRAINT","name":"FK_SEC_GM_GROUP_ID","schemaName":"DIRKSPZM32","sxml":""}