
  ALTER TABLE "PZM_ZE_LOA_AUSW" ADD CONSTRAINT "FK_ZEAW_LZ_ID" FOREIGN KEY ("ZEAW_LZ_ID")
	  REFERENCES "PZM_LOHNARTEN" ("LZ_ID") ENABLE;


-- sqlcl_snapshot {"hash":"2e23c2af7d728a46ae8eab5f83f758e9a66e5212","type":"REF_CONSTRAINT","name":"FK_ZEAW_LZ_ID","schemaName":"DIRKSPZM32","sxml":""}