
  ALTER TABLE "PZM_ZEITERFASSUNG" ADD CONSTRAINT "FK_ZE_SA_KURZNAME" FOREIGN KEY ("ZE_SA_KURZNAME")
	  REFERENCES "PZM_SCHICHTARTEN" ("SA_KURZNAME") DISABLE;


-- sqlcl_snapshot {"hash":"4ef7e26055413c69fa62cf77133d58c467e193d4","type":"REF_CONSTRAINT","name":"FK_ZE_SA_KURZNAME","schemaName":"DIRKSPZM32","sxml":""}