
  ALTER TABLE "DIRKSPZM32"."PZM_ZEITERFASSUNG" ADD CONSTRAINT "FK_ZE_KORR_PERS_NR" FOREIGN KEY ("ZE_KORR_PERS_NR")
	  REFERENCES "DIRKSPZM32"."PZM_PERSONAL" ("PERS_NR") DISABLE;


-- sqlcl_snapshot {"hash":"4554dafa1ee018de7858032f5b37385cc987a4be","type":"REF_CONSTRAINT","name":"FK_ZE_KORR_PERS_NR","schemaName":"DIRKSPZM32","sxml":""}