
  ALTER TABLE "DIRKSPZM32"."PZM_ZE_LOA_AUSW" ADD CONSTRAINT "FK_ZEAW_LZ_ID" FOREIGN KEY ("ZEAW_LZ_ID")
	  REFERENCES "DIRKSPZM32"."PZM_LOHNARTEN" ("LZ_ID") ENABLE;


-- sqlcl_snapshot {"hash":"6b6daaf35f637924cfd6da0034ee4c99040180b4","type":"REF_CONSTRAINT","name":"FK_ZEAW_LZ_ID","schemaName":"DIRKSPZM32","sxml":""}