
  ALTER TABLE "PZM_ZEITERFASSUNG" ADD CONSTRAINT "FK_ZE_KORR_PERS_NR" FOREIGN KEY ("ZE_KORR_PERS_NR")
	  REFERENCES "PZM_PERSONAL" ("PERS_NR") DISABLE;


-- sqlcl_snapshot {"hash":"6d791f3b90f5df8cec4bf7fed411772fce27998e","type":"REF_CONSTRAINT","name":"FK_ZE_KORR_PERS_NR","schemaName":"DIRKSPZM32","sxml":""}