
  ALTER TABLE "DIRKSPZM32"."PZM_ZEITERFASSUNG" ADD CONSTRAINT "FK_ZE_STATUS" FOREIGN KEY ("ZE_STATUS")
	  REFERENCES "DIRKSPZM32"."PZM_ZE_STATUSINFO" ("STAT_ID") DISABLE;


-- sqlcl_snapshot {"hash":"3870e27aacf6768d9b4be2b8c64a82ddbecb1f60","type":"REF_CONSTRAINT","name":"FK_ZE_STATUS","schemaName":"DIRKSPZM32","sxml":""}