
  ALTER TABLE "DIRKSPZM32"."PZM_ZEITERFASSUNG" ADD CONSTRAINT "FK_ZE_SA_KURZNAME" FOREIGN KEY ("ZE_SA_KURZNAME")
	  REFERENCES "DIRKSPZM32"."PZM_SCHICHTARTEN" ("SA_KURZNAME") DISABLE;


-- sqlcl_snapshot {"hash":"52cb6d09aaf9bcfaffa4feed076e9620b0e5058e","type":"REF_CONSTRAINT","name":"FK_ZE_SA_KURZNAME","schemaName":"DIRKSPZM32","sxml":""}