
  ALTER TABLE "PZM_ZEITERFASSUNG" ADD CONSTRAINT "FK_ZE_PB_ID" FOREIGN KEY ("ZE_PB_ID")
	  REFERENCES "PZM_PRODUKTIONSBEREICHE" ("PB_ID") DISABLE;


-- sqlcl_snapshot {"hash":"05f84bdde9226db322d42b0f4b4f1517b9f5241d","type":"REF_CONSTRAINT","name":"FK_ZE_PB_ID","schemaName":"DIRKSPZM32","sxml":""}