
  ALTER TABLE "DIRKSPZM32"."PZM_ZEITERFASSUNG" ADD CONSTRAINT "FK_ZE_PB_ID" FOREIGN KEY ("ZE_PB_ID")
	  REFERENCES "DIRKSPZM32"."PZM_PRODUKTIONSBEREICHE" ("PB_ID") DISABLE;


-- sqlcl_snapshot {"hash":"6dcf454654317c9c84dff5388c56b77ec8e0775a","type":"REF_CONSTRAINT","name":"FK_ZE_PB_ID","schemaName":"DIRKSPZM32","sxml":""}