
  ALTER TABLE "DIRKSPZM32"."PZM_ZEITERFASSUNG" ADD CONSTRAINT "FK_ZE_ABT_ID" FOREIGN KEY ("ZE_ABT_ID")
	  REFERENCES "DIRKSPZM32"."PZM_ABTEILUNGEN" ("ABT_ID") DISABLE;


-- sqlcl_snapshot {"hash":"12426ca9d114c3b42b2d91b3d08242d3becbaa5a","type":"REF_CONSTRAINT","name":"FK_ZE_ABT_ID","schemaName":"DIRKSPZM32","sxml":""}