
  ALTER TABLE "PZM_BEREITSCHAFT_CFG" ADD CONSTRAINT "PK_PZM_BEREITSCHAFT_CFG_LOA" FOREIGN KEY ("LOA_ID")
	  REFERENCES "PZM_LOHNARTEN" ("LZ_ID") ENABLE;


-- sqlcl_snapshot {"hash":"5e31cb0c2122d22fb2494a521e756290ccdda456","type":"REF_CONSTRAINT","name":"PK_PZM_BEREITSCHAFT_CFG_LOA","schemaName":"DIRKSPZM32","sxml":""}