
  ALTER TABLE "DIRKSPZM32"."PZM_BEREITSCHAFT_CFG" ADD CONSTRAINT "PK_PZM_BEREITSCHAFT_CFG_LOA_FE" FOREIGN KEY ("LOA_ID_FE")
	  REFERENCES "DIRKSPZM32"."PZM_LOHNARTEN" ("LZ_ID") ENABLE;


-- sqlcl_snapshot {"hash":"8abb97d31ee418e91200adc3222c9ad1277233ac","type":"REF_CONSTRAINT","name":"PK_PZM_BEREITSCHAFT_CFG_LOA_FE","schemaName":"DIRKSPZM32","sxml":""}