
  ALTER TABLE "PZM_BEREITSCHAFT_CFG" ADD CONSTRAINT "PK_PZM_BEREITSCHAFT_CFG_LOA_SA" FOREIGN KEY ("LOA_ID_SA")
	  REFERENCES "PZM_LOHNARTEN" ("LZ_ID") ENABLE;


-- sqlcl_snapshot {"hash":"ad5ffa34922e235a155b57f74115338ae50cdfcd","type":"REF_CONSTRAINT","name":"PK_PZM_BEREITSCHAFT_CFG_LOA_SA","schemaName":"DIRKSPZM32","sxml":""}