
  ALTER TABLE "DIRKSPZM32"."PZM_BEREITSCHAFT_CFG" ADD CONSTRAINT "PK_PZM_BEREITSCHAFT_CFG_LOA" FOREIGN KEY ("LOA_ID")
	  REFERENCES "DIRKSPZM32"."PZM_LOHNARTEN" ("LZ_ID") ENABLE;


-- sqlcl_snapshot {"hash":"2716fc8ebcf87b22efd5f05a09c45abf106ca456","type":"REF_CONSTRAINT","name":"PK_PZM_BEREITSCHAFT_CFG_LOA","schemaName":"DIRKSPZM32","sxml":""}