
  ALTER TABLE "DIRKSPZM32"."PZM_BEREITSCHAFT_CFG" ADD CONSTRAINT "PK_PZM_BEREITSCHAFT_CFG_LOA_SO" FOREIGN KEY ("LOA_ID_SO")
	  REFERENCES "DIRKSPZM32"."PZM_LOHNARTEN" ("LZ_ID") ENABLE;


-- sqlcl_snapshot {"hash":"a13211f43deec0de1387838541d25823a63f97f6","type":"REF_CONSTRAINT","name":"PK_PZM_BEREITSCHAFT_CFG_LOA_SO","schemaName":"DIRKSPZM32","sxml":""}