
  ALTER TABLE "PZM_BEREITSCHAFT_CFG" ADD CONSTRAINT "PK_PZM_BEREITSCHAFT_CFG_LOA_SO" FOREIGN KEY ("LOA_ID_SO")
	  REFERENCES "PZM_LOHNARTEN" ("LZ_ID") ENABLE;


-- sqlcl_snapshot {"hash":"f66b9399e3dbde7176c44db08519894b52a3a198","type":"REF_CONSTRAINT","name":"PK_PZM_BEREITSCHAFT_CFG_LOA_SO","schemaName":"DIRKSPZM32","sxml":""}