create or replace 
package DIRKSPZM32.pps_p_bde is

  /*
  __________________________________________________
  Author
  HJGOEDEKE (-AG-)  17.12.2007 13:14:07
  __________________________________________________
  Description
  PPS Funktionen für die Erzeugung von BDE Daten
  und PPS Daten aus Plandaten
  __________________________________________________
  TODO
  none
  __________________________________________________
  Date         Ver.        AUTOR    Comment
  -----------  ---------   ------   ---------------
  27.11.2009   3.5.0.1     (-BW-)   Minor Release
               3.4.4.1              Package erstellt
  */

  type t_bde_fa_plan is record(
    sid                         pps_arb_plan.sid%type,
    firma_nr                    pps_arb_plan.firma_nr%type,
    arb_plan_id                 pps_arb_plan.arb_plan_id%type,
    arb_plan_name               pps_arb_plan.arb_plan_name%type,
    arb_plan_text1              pps_arb_plan.text1%type,
    arb_plan_text2              pps_arb_plan.text2%type,
    arb_plan_text3              pps_arb_plan.text3%type,
    arb_soll_betriebsart        pps_arb_plan.soll_betriebsart%type,
    fa_gruppe                   bde_fa_kopf.fa_gruppe%type,
    arb_plan_pos_id             pps_arb_plan_ag.arb_plan_pos_id%type,
    pos_nr                      pps_arb_plan_ag.pos_nr%type,
    ag_upos                     pps_arb_plan_ag.ag_upos%type,
    satzartz                    pps_arb_plan_ag.satzart%type,
    ag_name1                    pps_arb_plan_ag.ag_name1%type,
    ag_name2                    pps_arb_plan_ag.ag_name2%type,
    ag_text1                    pps_arb_plan_ag.ag_text1%type,
    ag_text2                    pps_arb_plan_ag.ag_text2%type,
    ag_text3                    pps_arb_plan_ag.ag_text3%type,
    ag_plan_menge_faktor        pps_arb_plan_ag.plan_menge_faktor%type,
    ag_plan_menge_faktor_op     pps_arb_plan_ag.plan_menge_faktor_op%type,
    res_id                      pps_arb_plan_ag.res_id%type,
    nio_res_id                  pps_arb_plan_ag.res_id%type,
    prod_params                 pps_arb_plan_ag.prod_params%type,
    quitt_gruppe_ag             pps_arb_plan_ag.quitt_gruppe_ag%type,
    soll_zeit_ruest             pps_arb_plan_ag.soll_zeit_ruest%type,
    soll_zeit_p_einh            pps_arb_plan_ag.soll_zeit_p_einh%type,
    soll_zeit_stoer_p_std       pps_arb_plan_ag.soll_zeit_stoer_p_std%type,
    termin_start_gepl           bde_fa_auftrag.termin_start_gepl%type,
    termin_ende_gepl            bde_fa_auftrag.termin_ende_gepl%type,
    prod_reihenfolge            pps_arb_plan_ag_stl.prod_reihenfolge%type,
    prod_menge_p_einheit        pps_arb_plan_ag_stl.prod_menge_p_einheit%type,
    prod_menge_p_einheit_op     pps_arb_plan_ag_stl.prod_menge_p_einheit_op%type,
    prod_menge_ix               pps_arb_plan_ag_stl.prod_menge_ix%type,
    stueckliste_id              pps_stueckliste.stueckliste_id%type,
    stueckliste_name            pps_stueckliste.stueckliste_name%type,
    stl_text1                   pps_stueckliste.text1%type,
    stl_text2                   pps_stueckliste.text1%type,
    stl_text3                   pps_stueckliste.text1%type,
    stueckliste_pos_id          pps_stueckliste_pos.stueckliste_pos_id%type,
    stueckliste_pos_nr          pps_stueckliste_pos.pos_nr%type,
    artikel_id                  pps_stueckliste_pos.artikel_id%type,
    zeichnung                   pps_stueckliste_pos.zeichnung%type,
    zeichnung_index             pps_stueckliste_pos.zeichnung_index%type,
    stk_prod_params             pps_stueckliste_pos.prod_params%type,
    stk_plan_menge_p_einheit    pps_stueckliste_pos.plan_menge_p_einheit%type,
    stk_plan_menge_p_einheit_op pps_stueckliste_pos.plan_menge_p_einheit_op%type,
    vorgangsqualifikation       pps_arb_plan_ag.vorgangsqualifikation%type,
    ag_alternative              pps_arb_plan_ag.ag_alternative%type
    );


  v_version_str constant varchar2(20) := '3.5.0.1 / 27.11.2009';
  function get_version return varchar2;

  procedure c_create_bde_fa_auftrag_a_plan(in_sid              in isi_sid.sid%type,
                                           in_firma_nr         in isi_firma.firma_nr%type,
                                           in_artikel_id       in isi_artikel.artikel_id%type,
                                           in_charge_bez       in lvs_charge.charge_bez%type,
                                           in_res_id           in isi_resource.res_id%type,
                                           in_login_id         in isi_user.login_id%type,
                                           in_menge            in lvs_lam.menge%type,
                                           in_ab_text1         in bde_fa_auftrag.ab_text1%type,
                                           in_ab_text2         in bde_fa_auftrag.ab_text2%type,
                                           in_ab_text3         in bde_fa_auftrag.ab_text3%type,
                                           in_soll_betriebsart in bde_fa_kopf.soll_betriebsart%type,
                                           in_kunden_nr        in bde_fa_auftrag.kunden_nr%type,
                                           in_kd_art_nr        in bde_fa_auftrag.kd_art_nr%type,
                                           in_ag_name1         in bde_fa_auftrag.ag_bez1%type,
                                           in_ag_name2         in bde_fa_auftrag.ag_bez2%type,
                                           in_ag_text1         in bde_fa_auftrag.ag_text1%type,
                                           in_ag_text2         in bde_fa_auftrag.ag_text2%type,
                                           in_ag_text3         in bde_fa_auftrag.ag_text3%type,
                                           in_kenz_lhm_druck   in bde_fa_auftrag.kenz_lhm_druck%type,
                                           in_anz_lte          in bde_fa_auftrag.lte_anz%type,
                                           in_anz_lhm          in bde_fa_auftrag.lhm_anz%type,
                                           in_bestnr_kd        in bde_fa_auftrag.best_nr_kunde%type,
                                           in_abnr             in bde_fa_auftrag.abnr%type,
                                           in_serie_id         in bde_fa_kopf.serie_id%type,
                                           in_serie_auto_inc   in bde_fa_kopf.serie_auto_inc%type,
                                           in_fa_gruppe        in bde_fa_kopf.fa_gruppe%type,
                                           in_out_leitzahl     in out bde_fa_auftrag.leitzahl%type);

  procedure create_bde_fa_auftrag_a_plan(in_sid              in isi_sid.sid%type,
                                         in_firma_nr         in isi_firma.firma_nr%type,
                                         in_artikel_id       in isi_artikel.artikel_id%type,
                                         in_charge_bez       in lvs_charge.charge_bez%type,
                                         in_res_id           in isi_resource.res_id%type,
                                         in_login_id         in isi_user.login_id%type,
                                         in_menge            in lvs_lam.menge%type,
                                         in_ab_text1         in bde_fa_auftrag.ab_text1%type,
                                         in_ab_text2         in bde_fa_auftrag.ab_text2%type,
                                         in_ab_text3         in bde_fa_auftrag.ab_text3%type,
                                         in_soll_betriebsart in bde_fa_kopf.soll_betriebsart%type,
                                         in_kunden_nr        in bde_fa_auftrag.kunden_nr%type,
                                         in_kd_art_nr        in bde_fa_auftrag.kd_art_nr%type,
                                         in_ag_name1         in bde_fa_auftrag.ag_bez1%type,
                                         in_ag_name2         in bde_fa_auftrag.ag_bez2%type,
                                         in_ag_text1         in bde_fa_auftrag.ag_text1%type,
                                         in_ag_text2         in bde_fa_auftrag.ag_text2%type,
                                         in_ag_text3         in bde_fa_auftrag.ag_text3%type,
                                         in_kenz_lhm_druck   in bde_fa_auftrag.kenz_lhm_druck%type,
                                         in_anz_lte          in bde_fa_auftrag.lte_anz%type,
                                         in_anz_lhm          in bde_fa_auftrag.lhm_anz%type,
                                         in_bestnr_kd        in bde_fa_auftrag.best_nr_kunde%type,
                                         in_abnr             in bde_fa_auftrag.abnr%type,
                                         in_serie_id         in bde_fa_kopf.serie_id%type,
                                         in_serie_auto_inc   in bde_fa_kopf.serie_auto_inc%type,
                                         in_fa_gruppe        in bde_fa_kopf.fa_gruppe%type,
                                         in_out_leitzahl     in out bde_fa_auftrag.leitzahl%type);

  procedure crt_bde_fa_auft_a_plan_35_11(in_sid               in isi_sid.sid%type,
                                         in_firma_nr          in isi_firma.firma_nr%type,
                                         in_artikel_id        in isi_artikel.artikel_id%type,
                                         in_charge_bez        in lvs_charge.charge_bez%type,
                                         in_res_id            in isi_resource.res_id%type,
                                         in_login_id          in isi_user.login_id%type,
                                         in_menge             in lvs_lam.menge%type,
                                         in_ab_text1          in bde_fa_auftrag.ab_text1%type,
                                         in_ab_text2          in bde_fa_auftrag.ab_text2%type,
                                         in_ab_text3          in bde_fa_auftrag.ab_text3%type,
                                         in_soll_betriebsart  in bde_fa_kopf.soll_betriebsart%type,
                                         in_kunden_nr         in bde_fa_auftrag.kunden_nr%type,
                                         in_kd_art_nr         in bde_fa_auftrag.kd_art_nr%type,
                                         in_ag_name1          in bde_fa_auftrag.ag_bez1%type,
                                         in_ag_name2          in bde_fa_auftrag.ag_bez2%type,
                                         in_ag_text1          in bde_fa_auftrag.ag_text1%type,
                                         in_ag_text2          in bde_fa_auftrag.ag_text2%type,
                                         in_ag_text3          in bde_fa_auftrag.ag_text3%type,
                                         in_kenz_lhm_druck    in bde_fa_auftrag.kenz_lhm_druck%type,
                                         in_anz_lte           in bde_fa_auftrag.lte_anz%type,
                                         in_anz_lhm           in bde_fa_auftrag.lhm_anz%type,
                                         in_bestnr_kd         in bde_fa_auftrag.best_nr_kunde%type,
                                         in_abnr              in bde_fa_auftrag.abnr%type,
                                         in_serie_id          in bde_fa_kopf.serie_id%type,
                                         in_serie_auto_inc    in bde_fa_kopf.serie_auto_inc%type,
                                         in_fa_gruppe         in bde_fa_kopf.fa_gruppe%type,
                                         in_dispo_charge_rein in varchar2,
                                         in_hersteller_liste  in pps_simple_fa.hersteller_kuerzel_liste%type,
                                         in_lam_sel1          in lvs_lam.LAM_SEL1%type,
                                         in_lam_sel2          in lvs_lam.LAM_SEL2%type,
                                         in_lam_sel3          in lvs_lam.LAM_SEL3%type,
                                         in_lam_sel4          in lvs_lam.LAM_SEL4%type,
                                         in_lam_sel5          in lvs_lam.LAM_SEL5%type,
                                         in_lam_sel6          in lvs_lam.LAM_SEL6%type,
                                         in_lam_sel7          in lvs_lam.LAM_SEL7%type,
                                         in_lam_sel8          in lvs_lam.LAM_SEL8%type,
                                         in_lam_sel9          in lvs_lam.LAM_SEL9%type,
                                         in_lam_sel10         in lvs_lam.LAM_SEL10%type,
                                         in_adress_id         in bde_fa_auftrag.adress_id%type,
                                         in_lohn_arbeit       in bde_fa_auftrag.lohn_arbeit%type,
                                         in_out_leitzahl      in out bde_fa_auftrag.leitzahl%type);

  procedure create_bde_fa_auf_a_plan_dis_h(in_sid               in isi_sid.sid%type,
                                           in_firma_nr          in isi_firma.firma_nr%type,
                                           in_artikel_id        in isi_artikel.artikel_id%type,
                                           in_charge_bez        in lvs_charge.charge_bez%type,
                                           in_res_id            in isi_resource.res_id%type,
                                           in_login_id          in isi_user.login_id%type,
                                           in_menge             in lvs_lam.menge%type,
                                           in_ab_text1          in bde_fa_auftrag.ab_text1%type,
                                           in_ab_text2          in bde_fa_auftrag.ab_text2%type,
                                           in_ab_text3          in bde_fa_auftrag.ab_text3%type,
                                           in_soll_betriebsart  in bde_fa_kopf.soll_betriebsart%type,
                                           in_kunden_nr         in bde_fa_auftrag.kunden_nr%type,
                                           in_kd_art_nr         in bde_fa_auftrag.kd_art_nr%type,
                                           in_ag_name1          in bde_fa_auftrag.ag_bez1%type,
                                           in_ag_name2          in bde_fa_auftrag.ag_bez2%type,
                                           in_ag_text1          in bde_fa_auftrag.ag_text1%type,
                                           in_ag_text2          in bde_fa_auftrag.ag_text2%type,
                                           in_ag_text3          in bde_fa_auftrag.ag_text3%type,
                                           in_kenz_lhm_druck    in bde_fa_auftrag.kenz_lhm_druck%type,
                                           in_anz_lte           in bde_fa_auftrag.lte_anz%type,
                                           in_anz_lhm           in bde_fa_auftrag.lhm_anz%type,
                                           in_bestnr_kd         in bde_fa_auftrag.best_nr_kunde%type,
                                           in_abnr              in bde_fa_auftrag.abnr%type,
                                           in_serie_id          in bde_fa_kopf.serie_id%type,
                                           in_serie_auto_inc    in bde_fa_kopf.serie_auto_inc%type,
                                           in_fa_gruppe         in bde_fa_kopf.fa_gruppe%type,
                                           in_dispo_charge_rein in varchar2,
                                           in_hersteller_liste  in pps_simple_fa.hersteller_kuerzel_liste%type,
                                           in_out_leitzahl      in out bde_fa_auftrag.leitzahl%type);

  procedure crt_bde_fa_auf_a_plan_h_35_11(in_sid               in isi_sid.sid%type,
                                          in_firma_nr          in isi_firma.firma_nr%type,
                                          in_artikel_id        in isi_artikel.artikel_id%type,
                                          in_charge_bez        in lvs_charge.charge_bez%type,
                                          in_res_id            in isi_resource.res_id%type,
                                          in_login_id          in isi_user.login_id%type,
                                          in_menge             in lvs_lam.menge%type,
                                          in_ab_text1          in bde_fa_auftrag.ab_text1%type,
                                          in_ab_text2          in bde_fa_auftrag.ab_text2%type,
                                          in_ab_text3          in bde_fa_auftrag.ab_text3%type,
                                          in_soll_betriebsart  in bde_fa_kopf.soll_betriebsart%type,
                                          in_kunden_nr         in bde_fa_auftrag.kunden_nr%type,
                                          in_kd_art_nr         in bde_fa_auftrag.kd_art_nr%type,
                                          in_ag_name1          in bde_fa_auftrag.ag_bez1%type,
                                          in_ag_name2          in bde_fa_auftrag.ag_bez2%type,
                                          in_ag_text1          in bde_fa_auftrag.ag_text1%type,
                                          in_ag_text2          in bde_fa_auftrag.ag_text2%type,
                                          in_ag_text3          in bde_fa_auftrag.ag_text3%type,
                                          in_kenz_lhm_druck    in bde_fa_auftrag.kenz_lhm_druck%type,
                                          in_anz_lte           in bde_fa_auftrag.lte_anz%type,
                                          in_anz_lhm           in bde_fa_auftrag.lhm_anz%type,
                                          in_bestnr_kd         in bde_fa_auftrag.best_nr_kunde%type,
                                          in_abnr              in bde_fa_auftrag.abnr%type,
                                          in_serie_id          in bde_fa_kopf.serie_id%type,
                                          in_serie_auto_inc    in bde_fa_kopf.serie_auto_inc%type,
                                          in_fa_gruppe         in bde_fa_kopf.fa_gruppe%type,
                                          in_dispo_charge_rein in varchar2,
                                          in_hersteller_liste  in pps_simple_fa.hersteller_kuerzel_liste%type,
                                          in_lam_sel1          in lvs_lam.LAM_SEL1%type,
                                          in_lam_sel2          in lvs_lam.LAM_SEL2%type,
                                          in_lam_sel3          in lvs_lam.LAM_SEL3%type,
                                          in_lam_sel4          in lvs_lam.LAM_SEL4%type,
                                          in_lam_sel5          in lvs_lam.LAM_SEL5%type,
                                          in_lam_sel6          in lvs_lam.LAM_SEL6%type,
                                          in_lam_sel7          in lvs_lam.LAM_SEL7%type,
                                          in_lam_sel8          in lvs_lam.LAM_SEL8%type,
                                          in_lam_sel9          in lvs_lam.LAM_SEL9%type,
                                          in_lam_sel10         in lvs_lam.LAM_SEL10%type,
                                          in_adress_id         in bde_fa_auftrag.adress_id%type,
                                          in_lohn_arbeit       in bde_fa_auftrag.lohn_arbeit%type,
                                          in_out_leitzahl      in out bde_fa_auftrag.leitzahl%type);

  procedure create_bde_fa_auf_a_plan_dispo(in_sid               in isi_sid.sid%type,
                                           in_firma_nr          in isi_firma.firma_nr%type,
                                           in_artikel_id        in isi_artikel.artikel_id%type,
                                           in_charge_bez        in lvs_charge.charge_bez%type,
                                           in_res_id            in isi_resource.res_id%type,
                                           in_login_id          in isi_user.login_id%type,
                                           in_menge             in lvs_lam.menge%type,
                                           in_ab_text1          in bde_fa_auftrag.ab_text1%type,
                                           in_ab_text2          in bde_fa_auftrag.ab_text2%type,
                                           in_ab_text3          in bde_fa_auftrag.ab_text3%type,
                                           in_soll_betriebsart  in bde_fa_kopf.soll_betriebsart%type,
                                           in_kunden_nr         in bde_fa_auftrag.kunden_nr%type,
                                           in_kd_art_nr         in bde_fa_auftrag.kd_art_nr%type,
                                           in_ag_name1          in bde_fa_auftrag.ag_bez1%type,
                                           in_ag_name2          in bde_fa_auftrag.ag_bez2%type,
                                           in_ag_text1          in bde_fa_auftrag.ag_text1%type,
                                           in_ag_text2          in bde_fa_auftrag.ag_text2%type,
                                           in_ag_text3          in bde_fa_auftrag.ag_text3%type,
                                           in_kenz_lhm_druck    in bde_fa_auftrag.kenz_lhm_druck%type,
                                           in_anz_lte           in bde_fa_auftrag.lte_anz%type,
                                           in_anz_lhm           in bde_fa_auftrag.lhm_anz%type,
                                           in_bestnr_kd         in bde_fa_auftrag.best_nr_kunde%type,
                                           in_abnr              in bde_fa_auftrag.abnr%type,
                                           in_serie_id          in bde_fa_kopf.serie_id%type,
                                           in_serie_auto_inc    in bde_fa_kopf.serie_auto_inc%type,
                                           in_fa_gruppe         in bde_fa_kopf.fa_gruppe%type,
                                           in_dispo_charge_rein in varchar2,
                                           in_out_leitzahl      in out bde_fa_auftrag.leitzahl%type);

  procedure c_create_bde_fa_auf_a_pla_disp(in_sid               in isi_sid.sid%type,
                                           in_firma_nr          in isi_firma.firma_nr%type,
                                           in_artikel_id        in isi_artikel.artikel_id%type,
                                           in_charge_bez        in lvs_charge.charge_bez%type,
                                           in_res_id            in isi_resource.res_id%type,
                                           in_login_id          in isi_user.login_id%type,
                                           in_menge             in lvs_lam.menge%type,
                                           in_ab_text1          in bde_fa_auftrag.ab_text1%type,
                                           in_ab_text2          in bde_fa_auftrag.ab_text2%type,
                                           in_ab_text3          in bde_fa_auftrag.ab_text3%type,
                                           in_soll_betriebsart  in bde_fa_kopf.soll_betriebsart%type,
                                           in_kunden_nr         in bde_fa_auftrag.kunden_nr%type,
                                           in_kd_art_nr         in bde_fa_auftrag.kd_art_nr%type,
                                           in_ag_name1          in bde_fa_auftrag.ag_bez1%type,
                                           in_ag_name2          in bde_fa_auftrag.ag_bez2%type,
                                           in_ag_text1          in bde_fa_auftrag.ag_text1%type,
                                           in_ag_text2          in bde_fa_auftrag.ag_text2%type,
                                           in_ag_text3          in bde_fa_auftrag.ag_text3%type,
                                           in_kenz_lhm_druck    in bde_fa_auftrag.kenz_lhm_druck%type,
                                           in_anz_lte           in bde_fa_auftrag.lte_anz%type,
                                           in_anz_lhm           in bde_fa_auftrag.lhm_anz%type,
                                           in_bestnr_kd         in bde_fa_auftrag.best_nr_kunde%type,
                                           in_abnr              in bde_fa_auftrag.abnr%type,
                                           in_serie_id          in bde_fa_kopf.serie_id%type,
                                           in_serie_auto_inc    in bde_fa_kopf.serie_auto_inc%type,
                                           in_fa_gruppe         in bde_fa_kopf.fa_gruppe%type,
                                           in_dispo_charge_rein in varchar2,
                                           in_out_leitzahl      in out bde_fa_auftrag.leitzahl%type);

  procedure c_create_bde_fa_auftrag_a_pps(in_sid         in isi_sid.sid%type,
                                          in_firma_nr    in isi_firma.firma_nr%type,
                                          in_plan_auf_id in pps_plan_auftrag.plan_auf_id%type,
                                          in_login_id    in isi_user.login_id%type);

  procedure c_create_pps_auftrag_a_plan(in_sid              in isi_sid.sid%type,
                                        in_firma_nr         in isi_firma.firma_nr%type,
                                        in_artikel_id       in isi_artikel.artikel_id%type,
                                        in_charge_bez       in lvs_charge.charge_bez%type,
                                        in_res_id           in isi_resource.res_id%type,
                                        in_login_id         in isi_user.login_id%type,
                                        in_menge            in lvs_lam.menge%type,
                                        in_ab_text1         in bde_fa_auftrag.ab_text1%type,
                                        in_ab_text2         in bde_fa_auftrag.ab_text2%type,
                                        in_ab_text3         in bde_fa_auftrag.ab_text3%type,
                                        in_soll_betriebsart in bde_fa_kopf.soll_betriebsart%type,
                                        in_kunden_nr        in bde_fa_auftrag.kunden_nr%type,
                                        in_kd_art_nr        in bde_fa_auftrag.kd_art_nr%type,
                                        in_ag_name1         in bde_fa_auftrag.ag_bez1%type,
                                        in_ag_name2         in bde_fa_auftrag.ag_bez2%type,
                                        in_ag_text1         in bde_fa_auftrag.ag_text1%type,
                                        in_ag_text2         in bde_fa_auftrag.ag_text2%type,
                                        in_ag_text3         in bde_fa_auftrag.ag_text3%type,
                                        in_kenz_lhm_druck   in bde_fa_auftrag.kenz_lhm_druck%type,
                                        in_anz_lte          in bde_fa_auftrag.lte_anz%type,
                                        in_anz_lhm          in bde_fa_auftrag.lhm_anz%type,
                                        in_bestnr_kd        in bde_fa_auftrag.best_nr_kunde%type,
                                        in_abnr             in bde_fa_auftrag.abnr%type,
                                        in_serie_id         in bde_fa_kopf.serie_id%type,
                                        in_serie_auto_inc   in bde_fa_kopf.serie_auto_inc%type,
                                        in_fa_gruppe        in bde_fa_kopf.fa_gruppe%type,
                                        in_out_leitzahl     in out bde_fa_auftrag.leitzahl%type);

procedure crt_bde_fa_auft_a_plan_DB31 (in_sid               in isi_sid.sid%type,
                                         in_firma_nr          in isi_firma.firma_nr%type,
                                         in_artikel_id        in isi_artikel.artikel_id%type,
                                         in_charge_bez        in lvs_charge.charge_bez%type,
                                         in_res_id            in isi_resource.res_id%type,
                                         in_login_id          in isi_user.login_id%type,
                                         in_menge             in lvs_lam.menge%type,
                                         in_ab_text1          in bde_fa_auftrag.ab_text1%type,
                                         in_ab_text2          in bde_fa_auftrag.ab_text2%type,
                                         in_ab_text3          in bde_fa_auftrag.ab_text3%type,
                                         in_soll_betriebsart  in bde_fa_kopf.soll_betriebsart%type,
                                         in_kunden_nr         in bde_fa_auftrag.kunden_nr%type,
                                         in_kd_art_nr         in bde_fa_auftrag.kd_art_nr%type,
                                         in_ag_name1          in bde_fa_auftrag.ag_bez1%type,
                                         in_ag_name2          in bde_fa_auftrag.ag_bez2%type,
                                         in_ag_text1          in bde_fa_auftrag.ag_text1%type,
                                         in_ag_text2          in bde_fa_auftrag.ag_text2%type,
                                         in_ag_text3          in bde_fa_auftrag.ag_text3%type,
                                         in_kenz_lhm_druck    in bde_fa_auftrag.kenz_lhm_druck%type,
                                         in_anz_lte           in bde_fa_auftrag.lte_anz%type,
                                         in_anz_lhm           in bde_fa_auftrag.lhm_anz%type,
                                         in_bestnr_kd         in bde_fa_auftrag.best_nr_kunde%type,
                                         in_abnr              in bde_fa_auftrag.abnr%type,
                                         in_serie_id          in bde_fa_kopf.serie_id%type,
                                         in_serie_auto_inc    in bde_fa_kopf.serie_auto_inc%type,
                                         in_fa_gruppe         in bde_fa_kopf.fa_gruppe%type,
                                         in_dispo_charge_rein in varchar2,
                                         in_hersteller_liste  in pps_simple_fa.hersteller_kuerzel_liste%type,
                                         in_lam_sel1          in lvs_lam.LAM_SEL1%type,
                                         in_lam_sel2          in lvs_lam.LAM_SEL2%type,
                                         in_lam_sel3          in lvs_lam.LAM_SEL3%type,
                                         in_lam_sel4          in lvs_lam.LAM_SEL4%type,
                                         in_lam_sel5          in lvs_lam.LAM_SEL5%type,
                                         in_lam_sel6          in lvs_lam.LAM_SEL6%type,
                                         in_lam_sel7          in lvs_lam.LAM_SEL7%type,
                                         in_lam_sel8          in lvs_lam.LAM_SEL8%type,
                                         in_lam_sel9          in lvs_lam.LAM_SEL9%type,
                                         in_lam_sel10         in lvs_lam.LAM_SEL10%type,
                                         in_adress_id         in bde_fa_auftrag.adress_id%type,
                                         in_lohn_arbeit       in bde_fa_auftrag.lohn_arbeit%type,
                                         in_seq_nr            in bde_fa_auftrag.seq_nr%type,
                                         in_lead_leitzahl     in bde_fa_auftrag.lead_leitzahl%type,
                                         in_primaer_leitzahl  in bde_fa_auftrag.primaer_leitzahl%type,
                                         in_out_leitzahl      in out bde_fa_auftrag.leitzahl%type
                                         );


  procedure create_pps_auftrag_a_plan(in_sid              in isi_sid.sid%type,
                                      in_firma_nr         in isi_firma.firma_nr%type,
                                      in_artikel_id       in isi_artikel.artikel_id%type,
                                      in_charge_bez       in lvs_charge.charge_bez%type,
                                      in_res_id           in isi_resource.res_id%type,
                                      in_login_id         in isi_user.login_id%type,
                                      in_menge            in lvs_lam.menge%type,
                                      in_ab_text1         in bde_fa_auftrag.ab_text1%type,
                                      in_ab_text2         in bde_fa_auftrag.ab_text2%type,
                                      in_ab_text3         in bde_fa_auftrag.ab_text3%type,
                                      in_soll_betriebsart in bde_fa_kopf.soll_betriebsart%type,
                                      in_kunden_nr        in bde_fa_auftrag.kunden_nr%type,
                                      in_kd_art_nr        in bde_fa_auftrag.kd_art_nr%type,
                                      in_ag_name1         in bde_fa_auftrag.ag_bez1%type,
                                      in_ag_name2         in bde_fa_auftrag.ag_bez2%type,
                                      in_ag_text1         in bde_fa_auftrag.ag_text1%type,
                                      in_ag_text2         in bde_fa_auftrag.ag_text2%type,
                                      in_ag_text3         in bde_fa_auftrag.ag_text3%type,
                                      in_kenz_lhm_druck   in bde_fa_auftrag.kenz_lhm_druck%type,
                                      in_anz_lte          in bde_fa_auftrag.lte_anz%type,
                                      in_anz_lhm          in bde_fa_auftrag.lhm_anz%type,
                                      in_bestnr_kd        in bde_fa_auftrag.best_nr_kunde%type,
                                      in_abnr             in bde_fa_auftrag.abnr%type,
                                      in_serie_id         in bde_fa_kopf.serie_id%type,
                                      in_serie_auto_inc   in bde_fa_kopf.serie_auto_inc%type,
                                      in_fa_gruppe        in bde_fa_kopf.fa_gruppe%type,
                                      in_out_leitzahl     in out bde_fa_auftrag.leitzahl%type);

  procedure create_bde_fa_auftrag_DB31(in_ag_satzart              in bde_fa_auftrag.satzart%type,
                                       in_kenz_letzter            in bde_fa_auftrag.kenz_letzt_ag%type,
                                       in_artikel_id              in isi_artikel.artikel_id%type,
                                       in_zeichnung               in isi_artikel.zeichnung%type,
                                       in_zeichnung_index         in isi_artikel.zeichnung_index%type,
                                       in_charge_bez              in lvs_charge.charge_bez%type,
                                       in_login_id                in isi_user.login_id%type,
                                       in_menge                   in lvs_lam.menge%type,
                                       in_kunden_nr               in bde_fa_auftrag.kunden_nr%type,
                                       in_kd_art_nr               in bde_fa_auftrag.kd_art_nr%type,
                                       in_kenz_lhm_druck          in bde_fa_auftrag.kenz_lhm_druck%type,
                                       in_lte_name                in bde_fa_auftrag.lte_name%type,
                                       in_lte_menge               in bde_fa_auftrag.lte_menge%type,
                                       in_anz_lte                 in bde_fa_auftrag.lte_anz%type,
                                       in_lhm_name                in bde_fa_auftrag.lhm_name%type,
                                       in_lhm_menge               in bde_fa_auftrag.lhm_menge%type,
                                       in_anz_lhm                 in bde_fa_auftrag.lhm_anz%type,
                                       in_bestnr_kd               in bde_fa_auftrag.best_nr_kunde%type,
                                       in_abnr                    in bde_fa_auftrag.abnr%type,
                                       in_out_leitzahl            in out bde_fa_auftrag.leitzahl%type,
                                       in_fa_ag                   in bde_fa_auftrag.fa_ag%type,
                                       in_abfuell_grob            in bde_fa_auftrag.abfuell_abschalt_grob%type,
                                       in_abfuell_mittel          in bde_fa_auftrag.abfuell_abschalt_mittel%type,
                                       in_abfuell_fein            in bde_fa_auftrag.abfuell_abschalt_fein%type,
                                       in_abfuell_tolleranz_plus  in bde_fa_auftrag.abfuell_toleranz_plus%type,
                                       in_abfuell_tolleranz_minus in bde_fa_auftrag.abfuell_toleranz_minus%type,
                                       in_abfuell_soll            in bde_fa_auftrag.abfuell_soll%type,
                                       in_bde_fa_plan             in t_bde_fa_plan,
                                       in_seq_nr                  in bde_fa_auftrag.seq_nr%type,
                                       in_lead_leitzahl           in bde_fa_auftrag.lead_leitzahl%type,
                                       in_primaer_leitzahl        in bde_fa_auftrag.primaer_leitzahl%type,
                                       in_dispo_charge_rein       in varchar2,
                                       in_hersteller_liste        in pps_simple_fa.hersteller_kuerzel_liste%type
                                       );

  procedure create_bde_fa_dispo(in_sid               in isi_sid.sid%type,
                                in_firma_nr          in isi_firma.firma_nr%type,
                                in_dispo_charge_rein in varchar2,
                                in_hersteller_liste  in pps_simple_fa.hersteller_kuerzel_liste%type,
                                in_leitzahl          in bde_fa_auftrag.leitzahl%type,
                                in_fa_ag             in bde_fa_auftrag.fa_ag%type,
                                in_fa_upos           in bde_fa_auftrag.fa_upos%type,
                                in_komplett          in varchar2,
                                in_user_id           in isi_user.login_id%type,
                                in_ICE               in varchar2);

  procedure create_bde_fa_dispo_db31 (in_sid               in isi_sid.sid%type,
                                      in_firma_nr          in isi_firma.firma_nr%type,
                                      in_dispo_charge_rein in varchar2,
                                      in_hersteller_liste  in pps_simple_fa.hersteller_kuerzel_liste%type,
                                      in_leitzahl          in bde_fa_auftrag.leitzahl%type,
                                      in_fa_ag             in bde_fa_auftrag.fa_ag%type,
                                      in_fa_upos           in bde_fa_auftrag.fa_upos%type,
                                      in_komplett          in varchar2,
                                      in_user_id           in isi_user.login_id%type,
                                      in_ICE               in varchar2,
                                      in_min_res_menge     in lvs_lam.res_menge%type);

  procedure create_new_lam_f_rest(in_sid      in isi_sid.sid%type,
                                  in_firma_nr in isi_firma.firma_nr%type,
                                  in_lam      in lvs_lam%rowtype,
                                  in_user_id  in isi_user.login_id%type);

  procedure storno_bde_fa_dispo(in_sid      in isi_sid.sid%type,
                                in_firma_nr in isi_firma.firma_nr%type,
                                in_leitzahl in bde_fa_auftrag.leitzahl%type,
                                in_fa_ag    in bde_fa_auftrag.fa_ag%type,
                                in_fa_upos  in bde_fa_auftrag.fa_upos%type,
                                in_user_id  in isi_user.login_id%type);

  function check_bde_fa_for_delete(in_sid             in pe_drucker_cfg.sid%type,
                                   in_firma_nr        in pe_drucker_cfg.firma_nr%type,
                                   in_leitzahl        in bde_fa_auftrag.leitzahl%type,
                                   out_anz_bde_beg    out number)
    return boolean;
  
  function get_lte_dipo_ziele(in_sid          in lvs_lte.sid%type,
                              in_firma_nr     in lvs_lte.firma_nr%type,
                              in_lte_id       in lvs_lte.lte_id%type)
                              return varchar2;
  
  function chk_lte_on_res_lgr_grp (in_sid          in lvs_lte.sid%type,
                                   in_firma_nr     in lvs_lte.firma_nr%type,
                                   in_lte_id       in lvs_lte.lte_id%type,
                                   in_auf_id       in bde_fa_auftrag.auf_id%type)
                                   return number;
  
  function comp_w_fixed_id_in_params (in_params in bde_fa_kopf.prod_params%type,
                                      in_lte_id in lvs_lte.lte_id%type)
                                      return number;
  procedure crt_bde_fa_auft_a_plan_DB31_f (in_sid               in isi_sid.sid%type,
                                           in_firma_nr          in isi_firma.firma_nr%type,
                                           in_artikel_id        in isi_artikel.artikel_id%type,
                                           in_charge_bez        in lvs_charge.charge_bez%type,
                                           in_res_id            in isi_resource.res_id%type,
                                           in_login_id          in isi_user.login_id%type,
                                           in_menge             in lvs_lam.menge%type,
                                           in_ab_text1          in bde_fa_auftrag.ab_text1%type,
                                           in_ab_text2          in bde_fa_auftrag.ab_text2%type,
                                           in_ab_text3          in bde_fa_auftrag.ab_text3%type,
                                           in_soll_betriebsart  in bde_fa_kopf.soll_betriebsart%type,
                                           in_kunden_nr         in bde_fa_auftrag.kunden_nr%type,
                                           in_kd_art_nr         in bde_fa_auftrag.kd_art_nr%type,
                                           in_ag_name1          in bde_fa_auftrag.ag_bez1%type,
                                           in_ag_name2          in bde_fa_auftrag.ag_bez2%type,
                                           in_ag_text1          in bde_fa_auftrag.ag_text1%type,
                                           in_ag_text2          in bde_fa_auftrag.ag_text2%type,
                                           in_ag_text3          in bde_fa_auftrag.ag_text3%type,
                                           in_kenz_lhm_druck    in bde_fa_auftrag.kenz_lhm_druck%type,
                                           in_anz_lte           in bde_fa_auftrag.lte_anz%type,
                                           in_anz_lhm           in bde_fa_auftrag.lhm_anz%type,
                                           in_bestnr_kd         in bde_fa_auftrag.best_nr_kunde%type,
                                           in_abnr              in bde_fa_auftrag.abnr%type,
                                           in_serie_id          in bde_fa_kopf.serie_id%type,
                                           in_serie_auto_inc    in bde_fa_kopf.serie_auto_inc%type,
                                           in_fa_gruppe         in bde_fa_kopf.fa_gruppe%type,
                                           in_dispo_charge_rein in varchar2,
                                           in_hersteller_liste  in pps_simple_fa.hersteller_kuerzel_liste%type,
                                           in_lam_sel1          in lvs_lam.LAM_SEL1%type,
                                           in_lam_sel2          in lvs_lam.LAM_SEL2%type,
                                           in_lam_sel3          in lvs_lam.LAM_SEL3%type,
                                           in_lam_sel4          in lvs_lam.LAM_SEL4%type,
                                           in_lam_sel5          in lvs_lam.LAM_SEL5%type,
                                           in_lam_sel6          in lvs_lam.LAM_SEL6%type,
                                           in_lam_sel7          in lvs_lam.LAM_SEL7%type,
                                           in_lam_sel8          in lvs_lam.LAM_SEL8%type,
                                           in_lam_sel9          in lvs_lam.LAM_SEL9%type,
                                           in_lam_sel10         in lvs_lam.LAM_SEL10%type,
                                           in_adress_id         in bde_fa_auftrag.adress_id%type,
                                           in_lohn_arbeit       in bde_fa_auftrag.lohn_arbeit%type,
                                           in_seq_nr            in bde_fa_auftrag.seq_nr%type,
                                           in_lead_leitzahl     in bde_fa_auftrag.lead_leitzahl%type,
                                           in_primaer_leitzahl  in bde_fa_auftrag.primaer_leitzahl%type,
                                           in_fixed_id          in aps_plan_ergebnis.fixed_properties%type,
                                           in_fixed_lte_id      in lvs_lte.lte_id%type,
                                           in_out_leitzahl      in out bde_fa_auftrag.leitzahl%type);
end pps_p_bde;
/



-- sqlcl_snapshot {"hash":"83b45d3205d6f108c53bd1bbc743bfaa2c9d3da8","type":"PACKAGE_SPEC","name":"PPS_P_BDE","schemaName":"DIRKSPZM32","sxml":""}