
  CREATE TABLE "DIRKSPZM32"."ISI_DB_MA_SLA" 
   (	"DB_FUNKTION" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"DB_LAST_CHANGE" TIMESTAMP (6) NOT NULL ENABLE
   ) ;
ALTER TABLE "DIRKSPZM32"."ISI_DB_MA_SLA" ADD CONSTRAINT "PK_ISI_DB_MA_SLA" PRIMARY KEY ("DB_FUNKTION")
  USING INDEX  ENABLE;


-- sqlcl_snapshot {"hash":"59a63571e19b07f9299f50853c78a50ff3633a49","type":"TABLE","name":"ISI_DB_MA_SLA","schemaName":"DIRKSPZM32","sxml":"\n  <TABLE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>ISI_DB_MA_SLA</NAME>\n   <RELATIONAL_TABLE>\n      <COL_LIST>\n         <COL_LIST_ITEM>\n            <NAME>DB_FUNKTION</NAME>\n            <DATATYPE>VARCHAR2</DATATYPE>\n            <LENGTH>20</LENGTH>\n            <CHAR_SEMANTICS></CHAR_SEMANTICS>\n            <COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME>\n            <NOT_NULL></NOT_NULL>\n         </COL_LIST_ITEM>\n         <COL_LIST_ITEM>\n            <NAME>DB_LAST_CHANGE</NAME>\n            <DATATYPE>TIMESTAMP</DATATYPE>\n            <SCALE>6</SCALE>\n            <NOT_NULL></NOT_NULL>\n         </COL_LIST_ITEM>\n      </COL_LIST>\n      <PRIMARY_KEY_CONSTRAINT_LIST>\n         <PRIMARY_KEY_CONSTRAINT_LIST_ITEM>\n            <NAME>PK_ISI_DB_MA_SLA</NAME>\n            <COL_LIST>\n               <COL_LIST_ITEM>\n                  <NAME>DB_FUNKTION</NAME>\n               </COL_LIST_ITEM>\n            </COL_LIST>\n            <USING_INDEX></USING_INDEX>\n         </PRIMARY_KEY_CONSTRAINT_LIST_ITEM>\n      </PRIMARY_KEY_CONSTRAINT_LIST>\n      <DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION>\n      <PHYSICAL_PROPERTIES>\n         <HEAP_TABLE></HEAP_TABLE>\n      </PHYSICAL_PROPERTIES>\n   </RELATIONAL_TABLE>\n</TABLE>"}