
  CREATE TABLE "DIRKSPZM32"."LVS_LTE_DATUM_LID" 
   (	"LTE_BARCODE_KEY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"LTE_LID" NUMBER(*,0)
   ) ;
ALTER TABLE "DIRKSPZM32"."LVS_LTE_DATUM_LID" ADD CONSTRAINT "PK_LVS_LTE_DATUM_LNR" PRIMARY KEY ("LTE_BARCODE_KEY")
  USING INDEX  ENABLE;


-- sqlcl_snapshot {"hash":"650f61e4207f671250aa179e18f8b2346a778c6d","type":"TABLE","name":"LVS_LTE_DATUM_LID","schemaName":"DIRKSPZM32","sxml":"\n  <TABLE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>LVS_LTE_DATUM_LID</NAME>\n   <RELATIONAL_TABLE>\n      <COL_LIST>\n         <COL_LIST_ITEM>\n            <NAME>LTE_BARCODE_KEY</NAME>\n            <DATATYPE>VARCHAR2</DATATYPE>\n            <LENGTH>255</LENGTH>\n            <CHAR_SEMANTICS></CHAR_SEMANTICS>\n            <COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME>\n            <NOT_NULL></NOT_NULL>\n         </COL_LIST_ITEM>\n         <COL_LIST_ITEM>\n            <NAME>LTE_LID</NAME>\n            <DATATYPE>NUMBER</DATATYPE>\n            <SCALE>0</SCALE>\n         </COL_LIST_ITEM>\n      </COL_LIST>\n      <PRIMARY_KEY_CONSTRAINT_LIST>\n         <PRIMARY_KEY_CONSTRAINT_LIST_ITEM>\n            <NAME>PK_LVS_LTE_DATUM_LNR</NAME>\n            <COL_LIST>\n               <COL_LIST_ITEM>\n                  <NAME>LTE_BARCODE_KEY</NAME>\n               </COL_LIST_ITEM>\n            </COL_LIST>\n            <USING_INDEX></USING_INDEX>\n         </PRIMARY_KEY_CONSTRAINT_LIST_ITEM>\n      </PRIMARY_KEY_CONSTRAINT_LIST>\n      <DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION>\n      <PHYSICAL_PROPERTIES>\n         <HEAP_TABLE></HEAP_TABLE>\n      </PHYSICAL_PROPERTIES>\n   </RELATIONAL_TABLE>\n</TABLE>"}