
  CREATE TABLE "DIRKSPZM32"."MFR_ANLAGEN" 
   (	"ANLAGEN_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ANLAGEN_TEXT" VARCHAR2(100 CHAR) NOT NULL ENABLE
   ) ;
ALTER TABLE "DIRKSPZM32"."MFR_ANLAGEN" ADD CONSTRAINT "PK_MFR_ANLAGEN" PRIMARY KEY ("ANLAGEN_ID")
  USING INDEX  ENABLE;


-- sqlcl_snapshot {"hash":"b643e05b8b85b4a7481537d2986be5985161eb38","type":"TABLE","name":"MFR_ANLAGEN","schemaName":"DIRKSPZM32","sxml":"\n  <TABLE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>MFR_ANLAGEN</NAME>\n   <RELATIONAL_TABLE>\n      <COL_LIST>\n         <COL_LIST_ITEM>\n            <NAME>ANLAGEN_ID</NAME>\n            <DATATYPE>NUMBER</DATATYPE>\n            <SCALE>0</SCALE>\n            <NOT_NULL></NOT_NULL>\n         </COL_LIST_ITEM>\n         <COL_LIST_ITEM>\n            <NAME>ANLAGEN_TEXT</NAME>\n            <DATATYPE>VARCHAR2</DATATYPE>\n            <LENGTH>100</LENGTH>\n            <CHAR_SEMANTICS></CHAR_SEMANTICS>\n            <COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME>\n            <NOT_NULL></NOT_NULL>\n         </COL_LIST_ITEM>\n      </COL_LIST>\n      <PRIMARY_KEY_CONSTRAINT_LIST>\n         <PRIMARY_KEY_CONSTRAINT_LIST_ITEM>\n            <NAME>PK_MFR_ANLAGEN</NAME>\n            <COL_LIST>\n               <COL_LIST_ITEM>\n                  <NAME>ANLAGEN_ID</NAME>\n               </COL_LIST_ITEM>\n            </COL_LIST>\n            <USING_INDEX></USING_INDEX>\n         </PRIMARY_KEY_CONSTRAINT_LIST_ITEM>\n      </PRIMARY_KEY_CONSTRAINT_LIST>\n      <DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION>\n      <PHYSICAL_PROPERTIES>\n         <HEAP_TABLE></HEAP_TABLE>\n      </PHYSICAL_PROPERTIES>\n   </RELATIONAL_TABLE>\n</TABLE>"}