
  CREATE TABLE "DIRKSPZM32"."PZM_LZ_SA" 
   (	"LZSA_LZ_ID" NUMBER(6,0) NOT NULL ENABLE, 
	"LZSA_SA_KURZNAME" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"LZSA_GUELTIG" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
   ) ;
ALTER TABLE "DIRKSPZM32"."PZM_LZ_SA" ADD CONSTRAINT "PZM_LZ_SA" PRIMARY KEY ("LZSA_LZ_ID", "LZSA_SA_KURZNAME")
  USING INDEX  ENABLE;


-- sqlcl_snapshot {"hash":"e955c0ecc33db7d50fd0c619c879ae38965bbbae","type":"TABLE","name":"PZM_LZ_SA","schemaName":"DIRKSPZM32","sxml":"\n  <TABLE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>PZM_LZ_SA</NAME>\n   <RELATIONAL_TABLE>\n      <COL_LIST>\n         <COL_LIST_ITEM>\n            <NAME>LZSA_LZ_ID</NAME>\n            <DATATYPE>NUMBER</DATATYPE>\n            <PRECISION>6</PRECISION>\n            <SCALE>0</SCALE>\n            <NOT_NULL></NOT_NULL>\n         </COL_LIST_ITEM>\n         <COL_LIST_ITEM>\n            <NAME>LZSA_SA_KURZNAME</NAME>\n            <DATATYPE>VARCHAR2</DATATYPE>\n            <LENGTH>10</LENGTH>\n            <CHAR_SEMANTICS></CHAR_SEMANTICS>\n            <COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME>\n            <NOT_NULL></NOT_NULL>\n         </COL_LIST_ITEM>\n         <COL_LIST_ITEM>\n            <NAME>LZSA_GUELTIG</NAME>\n            <DATATYPE>NUMBER</DATATYPE>\n            <PRECISION>1</PRECISION>\n            <SCALE>0</SCALE>\n            <DEFAULT>1</DEFAULT>\n            <NOT_NULL></NOT_NULL>\n         </COL_LIST_ITEM>\n      </COL_LIST>\n      <PRIMARY_KEY_CONSTRAINT_LIST>\n         <PRIMARY_KEY_CONSTRAINT_LIST_ITEM>\n            <NAME>PZM_LZ_SA</NAME>\n            <COL_LIST>\n               <COL_LIST_ITEM>\n                  <NAME>LZSA_LZ_ID</NAME>\n               </COL_LIST_ITEM>\n               <COL_LIST_ITEM>\n                  <NAME>LZSA_SA_KURZNAME</NAME>\n               </COL_LIST_ITEM>\n            </COL_LIST>\n            <USING_INDEX></USING_INDEX>\n         </PRIMARY_KEY_CONSTRAINT_LIST_ITEM>\n      </PRIMARY_KEY_CONSTRAINT_LIST>\n      <DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION>\n      <PHYSICAL_PROPERTIES>\n         <HEAP_TABLE></HEAP_TABLE>\n      </PHYSICAL_PROPERTIES>\n   </RELATIONAL_TABLE>\n</TABLE>"}