
  CREATE TABLE "DIRKSPZM32"."SQD_LAND_TRSP_ZIEL" 
   (	"LAND_KURZ" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"LGR_ORT" NUMBER(*,5) NOT NULL ENABLE, 
	"LGR_PLATZ" VARCHAR2(30 CHAR), 
	"ADRESS_ID" NUMBER(*,0), 
	"BEMERKUNG" VARCHAR2(30 CHAR)
   ) ;
  CREATE INDEX "DIRKSPZM32"."IX_LAND_ADR" ON "DIRKSPZM32"."SQD_LAND_TRSP_ZIEL" ("LAND_KURZ", "ADRESS_ID") 
  ;
ALTER TABLE "DIRKSPZM32"."SQD_LAND_TRSP_ZIEL" ADD CONSTRAINT "PK_SQD_LAND" PRIMARY KEY ("LAND_KURZ")
  USING INDEX "DIRKSPZM32"."IX_LAND_ADR"  ENABLE;


-- sqlcl_snapshot {"hash":"1dc10e9b4c6639d67f2d57b9efa9e21fb0025c84","type":"TABLE","name":"SQD_LAND_TRSP_ZIEL","schemaName":"DIRKSPZM32","sxml":"\n  <TABLE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SQD_LAND_TRSP_ZIEL</NAME>\n   <RELATIONAL_TABLE>\n      <COL_LIST>\n         <COL_LIST_ITEM>\n            <NAME>LAND_KURZ</NAME>\n            <DATATYPE>VARCHAR2</DATATYPE>\n            <LENGTH>10</LENGTH>\n            <CHAR_SEMANTICS></CHAR_SEMANTICS>\n            <COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME>\n            <NOT_NULL></NOT_NULL>\n         </COL_LIST_ITEM>\n         <COL_LIST_ITEM>\n            <NAME>LGR_ORT</NAME>\n            <DATATYPE>NUMBER</DATATYPE>\n            <SCALE>5</SCALE>\n            <NOT_NULL></NOT_NULL>\n         </COL_LIST_ITEM>\n         <COL_LIST_ITEM>\n            <NAME>LGR_PLATZ</NAME>\n            <DATATYPE>VARCHAR2</DATATYPE>\n            <LENGTH>30</LENGTH>\n            <CHAR_SEMANTICS></CHAR_SEMANTICS>\n            <COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME>\n         </COL_LIST_ITEM>\n         <COL_LIST_ITEM>\n            <NAME>ADRESS_ID</NAME>\n            <DATATYPE>NUMBER</DATATYPE>\n            <SCALE>0</SCALE>\n         </COL_LIST_ITEM>\n         <COL_LIST_ITEM>\n            <NAME>BEMERKUNG</NAME>\n            <DATATYPE>VARCHAR2</DATATYPE>\n            <LENGTH>30</LENGTH>\n            <CHAR_SEMANTICS></CHAR_SEMANTICS>\n            <COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME>\n         </COL_LIST_ITEM>\n      </COL_LIST>\n      <PRIMARY_KEY_CONSTRAINT_LIST>\n         <PRIMARY_KEY_CONSTRAINT_LIST_ITEM>\n            <NAME>PK_SQD_LAND</NAME>\n            <COL_LIST>\n               <COL_LIST_ITEM>\n                  <NAME>LAND_KURZ</NAME>\n               </COL_LIST_ITEM>\n            </COL_LIST>\n            <USING_INDEX></USING_INDEX>\n         </PRIMARY_KEY_CONSTRAINT_LIST_ITEM>\n      </PRIMARY_KEY_CONSTRAINT_LIST>\n      <DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION>\n      <PHYSICAL_PROPERTIES>\n         <HEAP_TABLE></HEAP_TABLE>\n      </PHYSICAL_PROPERTIES>\n   </RELATIONAL_TABLE>\n</TABLE>"}