
  CREATE TABLE "DIRKSPZM32"."Z_PZM_PERS_NR_CHG_SCHICHTMODEL" 
   (	"PERS_NR" NUMBER(*,0), 
	"PERS_SM" VARCHAR2(50 CHAR)
   ) ;
ALTER TABLE "DIRKSPZM32"."Z_PZM_PERS_NR_CHG_SCHICHTMODEL" ADD CONSTRAINT "U_Z_PZM_PERS_NR_CHG_SCHICHTMODEL_PERS_NR" UNIQUE ("PERS_NR")
  USING INDEX  ENABLE;


-- sqlcl_snapshot {"hash":"d7e3d8e8d861d01607dae2191903a3d3929b1b9e","type":"TABLE","name":"Z_PZM_PERS_NR_CHG_SCHICHTMODEL","schemaName":"DIRKSPZM32","sxml":"\n  <TABLE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>Z_PZM_PERS_NR_CHG_SCHICHTMODEL</NAME>\n   <RELATIONAL_TABLE>\n      <COL_LIST>\n         <COL_LIST_ITEM>\n            <NAME>PERS_NR</NAME>\n            <DATATYPE>NUMBER</DATATYPE>\n            <SCALE>0</SCALE>\n         </COL_LIST_ITEM>\n         <COL_LIST_ITEM>\n            <NAME>PERS_SM</NAME>\n            <DATATYPE>VARCHAR2</DATATYPE>\n            <LENGTH>50</LENGTH>\n            <CHAR_SEMANTICS></CHAR_SEMANTICS>\n            <COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME>\n         </COL_LIST_ITEM>\n      </COL_LIST>\n      <UNIQUE_KEY_CONSTRAINT_LIST>\n         <UNIQUE_KEY_CONSTRAINT_LIST_ITEM>\n            <NAME>U_Z_PZM_PERS_NR_CHG_SCHICHTMODEL_PERS_NR</NAME>\n            <COL_LIST>\n               <COL_LIST_ITEM>\n                  <NAME>PERS_NR</NAME>\n               </COL_LIST_ITEM>\n            </COL_LIST>\n            <USING_INDEX></USING_INDEX>\n         </UNIQUE_KEY_CONSTRAINT_LIST_ITEM>\n      </UNIQUE_KEY_CONSTRAINT_LIST>\n      <DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION>\n      <PHYSICAL_PROPERTIES>\n         <HEAP_TABLE></HEAP_TABLE>\n      </PHYSICAL_PROPERTIES>\n   </RELATIONAL_TABLE>\n</TABLE>"}