
   CREATE SEQUENCE  "DIRKSPZM32"."PE_SEQ_PE_JOBS"  MINVALUE 0 MAXVALUE 999999 INCREMENT BY 1 /* start with n */ CACHE 10 ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"8b24baa079f07568509e29cb9fffc7f131bb9140","type":"SEQUENCE","name":"PE_SEQ_PE_JOBS","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>PE_SEQ_PE_JOBS</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>0</MINVALUE>\n   <MAXVALUE>999999</MAXVALUE>\n   <CYCLE></CYCLE>\n   <CACHE>10</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}