
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_PPS_PLAN_AUFTRAG_AG"  MINVALUE 1 MAXVALUE 900000 INCREMENT BY 1 /* start with n */ NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"b121b50c4178f1fdb4df0bf0dac65877a6a82162","type":"SEQUENCE","name":"SEQ_PPS_PLAN_AUFTRAG_AG","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_PPS_PLAN_AUFTRAG_AG</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>900000</MAXVALUE>\n   <CACHE>0</CACHE>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}