
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_ISI_MAIL_QUEUE_ID"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 /* start with n */ CACHE 5 NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"e00d7fc3cb4244be7301541aed6634935be93936","type":"SEQUENCE","name":"SEQ_ISI_MAIL_QUEUE_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_ISI_MAIL_QUEUE_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>99999999</MAXVALUE>\n   <CYCLE></CYCLE>\n   <CACHE>5</CACHE>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}