
   CREATE SEQUENCE  "SEQ_EMS_KONTO_NR"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 /* start with n */ NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"75ea6719bee6534fb4a84a60f08d25ce9a43d12c","type":"SEQUENCE","name":"SEQ_EMS_KONTO_NR","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_EMS_KONTO_NR</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>0</MINVALUE>\n   <MAXVALUE>99999999</MAXVALUE>\n   <CACHE>0</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}