
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_ARTIKEL_GRUPPE_ID"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 /* start with n */ CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"14b83ae3336004a0855df6ee3cec64a1494bae63","type":"SEQUENCE","name":"SEQ_ARTIKEL_GRUPPE_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_ARTIKEL_GRUPPE_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>99999</MAXVALUE>\n   <CACHE>20</CACHE>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}