
   CREATE SEQUENCE  "SEQ_ISI_ARBEITSPLATZ_CFG_ID"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 /* start with n */ CACHE 20 NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"cd498f4177eed8e63acead92772e01e0175d2b1f","type":"SEQUENCE","name":"SEQ_ISI_ARBEITSPLATZ_CFG_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_ISI_ARBEITSPLATZ_CFG_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>99999999</MAXVALUE>\n   <CYCLE></CYCLE>\n   <CACHE>20</CACHE>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}