
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_TEMP"  MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 /* start with n */ CACHE 10 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"5c6c616e373ea369f0a8c7cf62db43a6dd88d256","type":"SEQUENCE","name":"SEQ_TEMP","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_TEMP</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>999</MAXVALUE>\n   <CACHE>10</CACHE>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}