
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_ARTIKEL_ID"  MINVALUE 0 MAXVALUE 99999999999999 INCREMENT BY 1 /* start with n */ NOCACHE  ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"b0b7f7aad0ac3383e22abee825d95f5db992a0cf","type":"SEQUENCE","name":"SEQ_ARTIKEL_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_ARTIKEL_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>0</MINVALUE>\n   <MAXVALUE>99999999999999</MAXVALUE>\n   <CYCLE></CYCLE>\n   <CACHE>0</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}