
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_ISI_DB_AKTIVITAET"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 /* start with n */ CACHE 10 NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"324978dab034afbf25a1e324e811e8aef21dd697","type":"SEQUENCE","name":"SEQ_ISI_DB_AKTIVITAET","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_ISI_DB_AKTIVITAET</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>999999999999</MAXVALUE>\n   <CYCLE></CYCLE>\n   <CACHE>10</CACHE>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}