
   CREATE SEQUENCE  "SEQ_PZM_KONTO_NR"  MINVALUE 0 MAXVALUE 999999999 INCREMENT BY 1 /* start with n */ NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"71077469b5e8ac0d550db4c717d24678d658814d","type":"SEQUENCE","name":"SEQ_PZM_KONTO_NR","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_PZM_KONTO_NR</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>0</MINVALUE>\n   <MAXVALUE>999999999</MAXVALUE>\n   <CACHE>0</CACHE>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}