
   CREATE SEQUENCE  "SEQ_BDE_FA_AUFTRAG_LOG_ID"  MINVALUE 0 MAXVALUE 999999999999 INCREMENT BY 1 /* start with n */ NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"04caf8d38d38f531c662403a9bdb6cf90c6ca161","type":"SEQUENCE","name":"SEQ_BDE_FA_AUFTRAG_LOG_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_BDE_FA_AUFTRAG_LOG_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>0</MINVALUE>\n   <MAXVALUE>999999999999</MAXVALUE>\n   <CACHE>0</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}