
   CREATE SEQUENCE  "SEQ_ISI_LANGUAGE_LANG_ID"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 /* start with n */ CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"cee99aad9a1817df6fc01ff44d950e2adf209f8d","type":"SEQUENCE","name":"SEQ_ISI_LANGUAGE_LANG_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_ISI_LANGUAGE_LANG_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>99999999</MAXVALUE>\n   <CACHE>20</CACHE>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}