
   CREATE SEQUENCE  "SEQ_ISI_FIRMA_CFG_ID"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 /* start with n */ CACHE 20 NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"6b057a07ae312be28dcaafcc6c980a8592a8e163","type":"SEQUENCE","name":"SEQ_ISI_FIRMA_CFG_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_ISI_FIRMA_CFG_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>99999</MAXVALUE>\n   <CYCLE></CYCLE>\n   <CACHE>20</CACHE>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}