
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_LVS_ARTIKEL_LGR_INFO"  MINVALUE 0 MAXVALUE 999999999 INCREMENT BY 1 /* start with n */ NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"ff7ba33c6e9e87a733f40e2b79ed0ddca5401949","type":"SEQUENCE","name":"SEQ_LVS_ARTIKEL_LGR_INFO","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_LVS_ARTIKEL_LGR_INFO</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>0</MINVALUE>\n   <MAXVALUE>999999999</MAXVALUE>\n   <CACHE>0</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}