
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_DIS_TO_ORDER"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 /* start with n */ NOCACHE  ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"aa7f7a4fab91b964d8e7ff1050da5aeb4d167ce0","type":"SEQUENCE","name":"SEQ_DIS_TO_ORDER","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_DIS_TO_ORDER</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>99999999999999</MAXVALUE>\n   <CYCLE></CYCLE>\n   <CACHE>0</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}