
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_LICENSE_TICKET_ID"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 /* start with n */ CACHE 10 ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"85bec3d52bb5c2ce81dabd1abfdfc2dbacc0ac5e","type":"SEQUENCE","name":"SEQ_LICENSE_TICKET_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_LICENSE_TICKET_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>999999999999</MAXVALUE>\n   <CYCLE></CYCLE>\n   <CACHE>10</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}