
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_LHM_LGR_ID"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 /* start with n */ NOCACHE  ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"d4868cd503b1ac14879fb547d201d15581e98c22","type":"SEQUENCE","name":"SEQ_LHM_LGR_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_LHM_LGR_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>99999999999</MAXVALUE>\n   <CYCLE></CYCLE>\n   <CACHE>0</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}