
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_EVENT_ID"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 /* start with n */ NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"b71d9d56f06f791ee483c1b98964d6340d23d74f","type":"SEQUENCE","name":"SEQ_EVENT_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_EVENT_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>0</MINVALUE>\n   <MAXVALUE>9999999999</MAXVALUE>\n   <CACHE>0</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}