
   CREATE SEQUENCE  "SEQ_LAM_LGR_ID"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 /* start with n */ NOCACHE  ORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"292759ceab00dac1037f390bad6bbef5ba150d9a","type":"SEQUENCE","name":"SEQ_LAM_LGR_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_LAM_LGR_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>99999999999</MAXVALUE>\n   <CYCLE></CYCLE>\n   <CACHE>0</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}