
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_EVENT_MSG_TEXT_ID"  MINVALUE 0 MAXVALUE 9999999999 INCREMENT BY 1 /* start with n */ NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"30c4d4bf087a5cece41c978f6a13a5510f7a7c16","type":"SEQUENCE","name":"SEQ_EVENT_MSG_TEXT_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_EVENT_MSG_TEXT_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>0</MINVALUE>\n   <MAXVALUE>9999999999</MAXVALUE>\n   <CACHE>0</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}