
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_BDE_FA_AUFTRAG_LEITZAHL"  MINVALUE 1 MAXVALUE 900000 INCREMENT BY 1 /* start with n */ NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"e0728e2dd8bf7a7f3d60846ae4899f3aba8555e4","type":"SEQUENCE","name":"SEQ_BDE_FA_AUFTRAG_LEITZAHL","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_BDE_FA_AUFTRAG_LEITZAHL</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>900000</MAXVALUE>\n   <CACHE>0</CACHE>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}