
   CREATE SEQUENCE  "SEQ_EMS_KONTEN_ART_BH"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 /* start with n */ NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"55988a668307b9d03ef9dd06866ab5c51b47d21b","type":"SEQUENCE","name":"SEQ_EMS_KONTEN_ART_BH","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_EMS_KONTEN_ART_BH</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>0</MINVALUE>\n   <MAXVALUE>99999999</MAXVALUE>\n   <CACHE>0</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}