
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_ISI_ARBEITSPLATZ_CFG_ID"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 /* start with n */ CACHE 20 NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"77f6186031b8cf6d4e712e16b5ebae0c58549c07","type":"SEQUENCE","name":"SEQ_ISI_ARBEITSPLATZ_CFG_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_ISI_ARBEITSPLATZ_CFG_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>99999999</MAXVALUE>\n   <CYCLE></CYCLE>\n   <CACHE>20</CACHE>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}