
   CREATE SEQUENCE  "SEQ_ISI_PURCH_KOPF"  MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 /* start with n */ CACHE 20 NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"4e0cdee8d6e201bd0e2ce2e63b0adc364cb068b4","type":"SEQUENCE","name":"SEQ_ISI_PURCH_KOPF","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_ISI_PURCH_KOPF</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>9999999</MAXVALUE>\n   <CYCLE></CYCLE>\n   <CACHE>20</CACHE>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}