
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_ARTIKEL_STATUS_ID"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 /* start with n */ NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"996e1b387cad0155086d9e9fd6b7dbc2ab6b5766","type":"SEQUENCE","name":"SEQ_ARTIKEL_STATUS_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_ARTIKEL_STATUS_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>0</MINVALUE>\n   <MAXVALUE>99999999</MAXVALUE>\n   <CACHE>0</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}