
   CREATE SEQUENCE  "SEQ_PZM_BEREITSCHAFT_PLAN"  MINVALUE 0 MAXVALUE 99999999999999 INCREMENT BY 1 /* start with n */ NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"2a0faf77cfff75cc923dbcc93670fee35a7e50a1","type":"SEQUENCE","name":"SEQ_PZM_BEREITSCHAFT_PLAN","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_PZM_BEREITSCHAFT_PLAN</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>0</MINVALUE>\n   <MAXVALUE>99999999999999</MAXVALUE>\n   <CACHE>0</CACHE>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}