
   CREATE SEQUENCE  "SEQ_ISI_RES_SCHICHT_ID"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 /* start with n */ CACHE 5 NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"0668e9a79f315f5e5723e5e71b18ab83aefa7ec0","type":"SEQUENCE","name":"SEQ_ISI_RES_SCHICHT_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_ISI_RES_SCHICHT_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>99999999</MAXVALUE>\n   <CYCLE></CYCLE>\n   <CACHE>5</CACHE>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}