
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_ISI_ARBEITSPLAZ_ID"  MINVALUE 100000 MAXVALUE 999999 INCREMENT BY 1 /* start with n */ NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"96ee7210a9596ef5177e700abb52dea08bfd9e5d","type":"SEQUENCE","name":"SEQ_ISI_ARBEITSPLAZ_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_ISI_ARBEITSPLAZ_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>100000</MINVALUE>\n   <MAXVALUE>999999</MAXVALUE>\n   <CACHE>0</CACHE>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}