
   CREATE SEQUENCE  "SEQ_SCHEDULE_CFG_ID"  MINVALUE 0 MAXVALUE 999999999 INCREMENT BY 1 /* start with n */ CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"11c74d7d3ed9f570ba27addbe9b4c464c3bc10d8","type":"SEQUENCE","name":"SEQ_SCHEDULE_CFG_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_SCHEDULE_CFG_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>0</MINVALUE>\n   <MAXVALUE>999999999</MAXVALUE>\n   <CACHE>20</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}