
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_LVS_PROD_LINIE_NR"  MINVALUE 0 MAXVALUE 99999 INCREMENT BY 1 /* start with n */ NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"30c26402d6e31e60be3ddafe6a270ed0290953b1","type":"SEQUENCE","name":"SEQ_LVS_PROD_LINIE_NR","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_LVS_PROD_LINIE_NR</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>0</MINVALUE>\n   <MAXVALUE>99999</MAXVALUE>\n   <CACHE>0</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}