
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_TSL_ID"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 /* start with n */ CACHE 20 NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"6e78cfc540ea644378ff2a456e5bd576b9301eaf","type":"SEQUENCE","name":"SEQ_TSL_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_TSL_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>1</MINVALUE>\n   <MAXVALUE>999999999</MAXVALUE>\n   <CYCLE></CYCLE>\n   <CACHE>20</CACHE>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}