
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_AA_ID"  MINVALUE 0 MAXVALUE 9999 INCREMENT BY 1 /* start with n */ NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"1be35fbe75ff693d2136b70e8eff790113c3d006","type":"SEQUENCE","name":"SEQ_AA_ID","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_AA_ID</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>0</MINVALUE>\n   <MAXVALUE>9999</MAXVALUE>\n   <CACHE>0</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}