
   CREATE SEQUENCE  "DIRKSPZM32"."SEQ_TMS_ORDER_LI_NR"  MINVALUE 0 MAXVALUE 99999999999 INCREMENT BY 1 /* start with n */ NOCACHE  ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


-- sqlcl_snapshot {"hash":"b1fc6b5684d1bc7828dea8dbac0010e7518f7c7d","type":"SEQUENCE","name":"SEQ_TMS_ORDER_LI_NR","schemaName":"DIRKSPZM32","sxml":"\n  <SEQUENCE xmlns=\"http://xmlns.oracle.com/ku\" version=\"1.0\">\n   <SCHEMA>DIRKSPZM32</SCHEMA>\n   <NAME>SEQ_TMS_ORDER_LI_NR</NAME>\n   \n   <INCREMENT>1</INCREMENT>\n   <MINVALUE>0</MINVALUE>\n   <MAXVALUE>99999999999</MAXVALUE>\n   <CACHE>0</CACHE>\n   <ORDER></ORDER>\n   <SCALE>NOSCALE</SCALE>\n</SEQUENCE>"}