comment on table DIRKSPZM32.APS_FA_KOPF is 'Fertigungsaufträge aus dem APS';
comment on column DIRKSPZM32.APS_FA_KOPF."ARBEITSPLANBEZEICHNUNG" is 'Bezeichnung des verwendeten Arbeitsplans';
comment on column DIRKSPZM32.APS_FA_KOPF."ARBEITSPLANINFO1" is 'freier Arbeitsplan-Eintrag 1';
comment on column DIRKSPZM32.APS_FA_KOPF."ARBEITSPLANINFO2" is 'freier Arbeitsplan-Eintrag 2';
comment on column DIRKSPZM32.APS_FA_KOPF."ARBEITSPLANINFO3" is 'freier Arbeitsplan-Eintrag 3';
comment on column DIRKSPZM32.APS_FA_KOPF."ARBEITSPLANNR" is 'Identifikation des verwendeten Arbeitsplans';
comment on column DIRKSPZM32.APS_FA_KOPF."EINHEITSBEZEICHNUNG" is 'Bezeichnung der Einheit von Mengenangaben';
comment on column DIRKSPZM32.APS_FA_KOPF."EINHEITSNR" is 'Identifikation der Einheit von Mengenangaben';
comment on column DIRKSPZM32.APS_FA_KOPF."ERGEBNISNR" is 'Identifikation des Optimierungsergebnisses';
comment on column DIRKSPZM32.APS_FA_KOPF."FAKOPFINFO1" is 'freier FA-Eintrag 1';
comment on column DIRKSPZM32.APS_FA_KOPF."FAKOPFINFO2" is 'freier FA-Eintrag 2';
comment on column DIRKSPZM32.APS_FA_KOPF."FAKOPFINFO3" is 'freier FA-Eintrag 3';
comment on column DIRKSPZM32.APS_FA_KOPF."FAKOPFNR" is 'Identifikation des Fertigungsauftrags';
comment on column DIRKSPZM32.APS_FA_KOPF."FREIGEGEBEN" is 'Ist der FA freigegeben?';
comment on column DIRKSPZM32.APS_FA_KOPF."GESPERRT" is 'Ist der FA gesperrt?';
comment on column DIRKSPZM32.APS_FA_KOPF."MATERIALBEZEICHNUNG" is 'Bezeichnung des zu fertigenden Materials';
comment on column DIRKSPZM32.APS_FA_KOPF."MATERIALINFO1" is 'freier Material-Eintrag 1';
comment on column DIRKSPZM32.APS_FA_KOPF."MATERIALINFO2" is 'freier Material-Eintrag 2';
comment on column DIRKSPZM32.APS_FA_KOPF."MATERIALINFO3" is 'freier Material-Eintrag 3';
comment on column DIRKSPZM32.APS_FA_KOPF."MATERIALNR" is 'Identifikation des zu fertigenden Materials';
comment on column DIRKSPZM32.APS_FA_KOPF."MENGEBRUTTO" is 'Zu fertigende Istmenge vor Ausschuss';
comment on column DIRKSPZM32.APS_FA_KOPF."MENGENETTO" is 'Zu fertigende Sollmenge nach Ausschuss';
comment on column DIRKSPZM32.APS_FA_KOPF."PLANENDE" is 'Geplantes Ende';
comment on column DIRKSPZM32.APS_FA_KOPF."PLANFILTERTYP" is 'Identifikation des Planfilters';
comment on column DIRKSPZM32.APS_FA_KOPF."PLANFILTERTYPBESCHREIBUNG" is 'Planfiltertyp textuell';
comment on column DIRKSPZM32.APS_FA_KOPF."PLANFRUEHESTERSTART" is 'frühestmöglicher Start laut Planung';
comment on column DIRKSPZM32.APS_FA_KOPF."PLANFRUEHESTESENDE" is 'frühestmögliches Ende laut Planung';
comment on column DIRKSPZM32.APS_FA_KOPF."PLANNR" is 'Identifikation der Planung';
comment on column DIRKSPZM32.APS_FA_KOPF."PLANSPAETESTERSTART" is 'spätestmöglicher Start laut Planung';
comment on column DIRKSPZM32.APS_FA_KOPF."PLANSPAETESTESENDE" is 'spätestmögliches Ende laut Planung';
comment on column DIRKSPZM32.APS_FA_KOPF."PLANSTART" is 'Geplanter Start';
comment on column DIRKSPZM32.APS_FA_KOPF."PLANSTATUS" is 'Identifikation des Planstatus';
comment on column DIRKSPZM32.APS_FA_KOPF."PLANSTATUSBESCHREIBUNG" is 'PlanStatus textuell';
comment on column DIRKSPZM32.APS_FA_KOPF."PLANTERMINFIX" is 'Sind Termin, Planungstyp und Priorität fest vorgegeben sind';
comment on column DIRKSPZM32.APS_FA_KOPF."PLANUNGSTYP" is 'Identifikation des Typs';
comment on column DIRKSPZM32.APS_FA_KOPF."PLANUNGSTYPBESCHREIBUNG" is 'Typ textuell';
comment on column DIRKSPZM32.APS_FA_KOPF."PRIORITAETSBEZEICHNUNG" is 'Bezeichnung der Priorität des Fertigungsauftrags';
comment on column DIRKSPZM32.APS_FA_KOPF."PRIORITAETSINFO1" is 'Benutzerdefinierte Informationen zur Priorität';
comment on column DIRKSPZM32.APS_FA_KOPF."PRIORITAETSINFO2" is 'Benutzerdefinierte Informationen zur Priorität';
comment on column DIRKSPZM32.APS_FA_KOPF."PRIORITAETSINFO3" is 'Benutzerdefinierte Informationen zur Priorität';
comment on column DIRKSPZM32.APS_FA_KOPF."PRIORITAETSNR" is 'Identifikation der Priorität des Fertigungsauftrags';
comment on column DIRKSPZM32.APS_FA_KOPF."STATUS" is 'Identifikation des Status';
comment on column DIRKSPZM32.APS_FA_KOPF."STATUSBESCHREIBUNG" is 'Status textuell';
comment on column DIRKSPZM32.APS_FA_KOPF."STUECKLISTENBEZEICHNUNG" is 'Bezeichnung der verwendeten Stückliste';
comment on column DIRKSPZM32.APS_FA_KOPF."STUECKLISTENINFO1" is 'freier Stücklisten-Eintrag 1';
comment on column DIRKSPZM32.APS_FA_KOPF."STUECKLISTENINFO2" is 'freier Stücklisten-Eintrag 2';
comment on column DIRKSPZM32.APS_FA_KOPF."STUECKLISTENINFO3" is 'freier Stücklisten-Eintrag 3';
comment on column DIRKSPZM32.APS_FA_KOPF."STUECKLISTENNR" is 'Identifikation der verwendeten Stückliste';
comment on column DIRKSPZM32.APS_FA_KOPF."TERMIN" is 'Fertigstellungstermin';
comment on column DIRKSPZM32.APS_FA_KOPF."TYP" is 'Identifikation des Typs';
comment on column DIRKSPZM32.APS_FA_KOPF."TYPBESCHREIBUNG" is 'Typ textuell';
comment on column DIRKSPZM32.APS_FA_KOPF."WERT" is 'Wert des Fertigungsauftrags';



-- sqlcl_snapshot {"hash":"12f5c9209a733c9576c906fe32377e730de0f5a0","type":"COMMENT","name":"aps_fa_kopf","schemaName":"dirkspzm32","sxml":""}