comment on table DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS is 'Aufträge für die Planung APS';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."ADRESS_ID_LIEFER" is 'ID der Lieferadresse';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."ADRESS_ID_RECHN" is 'ID, wer hat diese Bestellung erstellt (Rechnungsadresse)';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."AEND_DATUM" is 'Bearbeitungsdatum, zuletzt bearbeitet am';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."AEND_LOGIN_ID" is 'ID des Bearbeiters';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."ANBRUCH" is 'T = True Erlaubt, F = False Verboten, A = Vozugsweise Anbruch, V = Vorzugsweise Volle, I = Egal ignorieren';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."APS_PLAN_STATUS" is 'PS = Planung gestartet PE = Ende Planung fertig mit Ergebnis, PA = Planung Abgebrochen, letzes Ergebnis ist wieder hergestellt - RET = Rettung letzer Planungslauf mit Status Fertig';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."ARTIKEL_ID" is 'Artikel_ID Ref. zur Artikelnummer in ISI_ARTIKEL';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."AUFTRAG_NR" is 'Auftragsnummer';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."AUFTR_DATUM" is 'Generierungsdatum des Auftrags';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."BESTELLER" is 'LVS, HOST, BDE ...';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."BEST_NR_KUNDE" is 'Bestellnummer des Kunden';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."CHARGE_ID" is 'Charge';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."ERZ_DATUM" is 'Erstellungsdatum, erstellt am';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."ERZ_LOGIN_ID" is 'ID des Erstellers';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."FEHLER_TEXT" is 'Fehlertext';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."FERTIG_DATUM" is 'Abgeschlossen am';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."FIRMA_NR" is 'Firmennummer in der Datenbank';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."FREIGABE" is 'M = Manuelle Freigabe, A = Automatisch Freigeben zum Datum, E = Paletten Einzelanforderung';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."FREIGABE_DATUM" is 'FREIGABE = M --> Erst dann freizugeben, A --> Automatische Freigabe genau am';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."FREIGEGEBEN_DATUM" is 'Freigegeban am';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."IST_MENGE" is 'Ist Menge (Bereits verladen)';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."JIS_IMPULS_BEREICH" is '(54) K100, Manufacturing Department, Fertigungsbereich';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."JIS_IMPULS_DATUM" is 'Melde-Datum';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."JIS_LFDNR" is 'Sequenz auf der Linie';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."JIS_LINIE" is 'Linie der Meldung';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."LAM_SEL1" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."LAM_SEL10" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."LAM_SEL2" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."LAM_SEL3" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."LAM_SEL4" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."LAM_SEL5" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."LAM_SEL6" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."LAM_SEL7" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."LAM_SEL8" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."LAM_SEL9" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."LIEFER_DATUM" is 'Gewünsches Liefer/Transportdatum';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."LI_NR" is 'Vorgegebene Lieferscheinnummer';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."LI_POS_NR" is 'Vorgegebene Lieferschein Positionsnummer';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."LVS_INFO" is 'für Informationen vom LVS';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."MENGENEINHEIT" is 'Mengeneinheit aus Menge Basis';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."MENGE_BASIS" is 'LKE = Kleinste Einheit, LHM = Name LHM, LTE = Name Transporteinheit';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."MHD" is 'MHD Welches MHD soll genommen werden (Filter nur Ware mit diesem MHD darf genommen werden)';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."MIN_MHD_TAGE" is 'Mindest MHD-Tage für die Ware (Filter)';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."MIN_REIFEZEIT" is 'Mindest Reifezeit für diesen Artikel (Filter)';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."NACHRICHT_URSPRG" is 'Ursprungsdatei, z.B. M100_r0011239.d01.txt';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."ORDER_INFO" is 'Info für Kommissionierer';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."PLANREIHENFOLGE" is 'Sequenzreihenfolge in der Planung';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."POS_NR" is 'Positionsnummer';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."PRIORITAET" is 'Priorität (0..9), 9: hohe Priorität - Zu bilden aus den Planvorgaben ';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."QUELL_LAGERORTE" is 'Lagerorte aus denen diese Ware entnommen werden kann';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."SERIENNR_ID" is 'Serien-Nummer';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."SID" is 'Datenbank für Konsolidierung';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."SOLL_MENGE" is 'Soll-Menge';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."STRATEGIE" is 'FIFO, LIFO ...';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."UPOS_NR" is 'Unterposition Bsp.: Eine Position mit n Chargen etc.';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."ZEICHNUNG_INDEX" is 'Zeichnungsindex (Filter)';
comment on column DIRKSPZM32.APS_PLAN_KUNDEN_AUFTR_POS."ZIEL" is 'WA wenn Auslagerung';



-- sqlcl_snapshot {"hash":"50f30b7d3d48b179872bbafc68b5acaa1e75f834","type":"COMMENT","name":"aps_plan_kunden_auftr_pos","schemaName":"dirkspzm32","sxml":""}