comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."ABFUELL_ABSCHALT_FEIN" is 'Absch. Fein';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."ABFUELL_ABSCHALT_GROB" is 'Absch. Grob';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."ABFUELL_ABSCHALT_MITTEL" is 'Absch. Mittel';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."ABFUELL_SILO" is 'Silo für Abfüllung';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."ABFUELL_SOLL" is 'Sollmenge für die Abfüllung';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."ABFUELL_TOLERANZ_MINUS" is 'Toleranz Minus';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."ABFUELL_TOLERANZ_PLUS" is 'Toleranz Plus';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."ABNR" is 'Auftrag Bestätigungsnummer (PLEIT)';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AB_ARTIKEL_ID" is 'Artikelnummer des Fertigartikels aus dem Kundenauftrag';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AB_IST_MG" is 'Bereits gefertigte Menge im Kundenauftrag (Fertigartikel)';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AB_SOLL_MG" is 'Sollmenge aus dem Kundenauftrag (Fertigartikel)';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AB_TEXT1" is 'Zusatztext aud Kundenauftrag';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AB_TEXT2" is 'Zusatztext aud Kundenauftrag';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AB_TEXT3" is 'Zusatztext aud Kundenauftrag';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."ADRESS_ID" is 'Verlängerte Werkbank, Eigetümer der Rohstoffe und Fertigware';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_ARTIKEL_ID" is 'Artikel ID für den AG';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_ART_BREITE" is 'Breite';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_ART_DICKE" is 'Dicke';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_ART_DURCH" is 'Durchmesser';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_ART_LAENGE" is 'Länge';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_BEZ1" is 'Arbeitsgang Bezeichnung';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_BEZ2" is 'Arbeitsgang Bezeichnung';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_IST_MG" is 'Bereits gefertigte Menge in diesem AG';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_IST_MG_B" is 'Angefalle Menge in B-Qualität für diesen AG';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_IST_MG_RUESTEN" is 'Angefalle Menge beim Rüsten und Anfahren für diesen AG';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_IST_MG_SCHROTT" is 'Angefalle Schrottmenge für diesen AG';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_LOS_IST_MG" is 'Istmenge in diesem AG die als Produktionsmenge auf der Maschiene produziert wurde (Teilmenge für dieses Produktionslos)';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_LOS_MG" is 'Sollmenge in diesem AG die als Produktionsmenge zur Maschiene gesendet werden soll (Teilmenge für dieses Produktionslos)';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_OPT_GRP" is 'Rüstgruppe zur optimierung im APS';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_PROD_FREI" is 'T = Freigegeben für Produktion, F = Nur für Planung';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_SOLL_MG" is 'Sollmenge in diesem AG';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_TEXT1" is 'Zusatztext für diesen Arbeitsgang';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_TEXT2" is 'Zusatztext für diesen Arbeitsgang';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_TEXT3" is 'Zusatztext für diesen Arbeitsgang';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AG_UEBERLAPPEN" is 'Anzahl die fertig sein müssen, um den  nächsten AG zu beginnen nächsten AG zu beginnen';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."ANZ_MITARBEITER" is 'Anzahl der benötigten Mitarbeiter';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."ANZ_RES" is 'Anzahl der Maschinen die an diesem AG arbeiten';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."ANZ_ROHSTOFFE" is 'Anzahl der benötigten Drähte';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AUF_ID" is 'eindeutige Sequenz-Nummer für Reservierungen und DISPO';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."AUSGEF_ENDE" is 'AUSGEFÜHRTES ENDE';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."BEST_NR_KUNDE" is 'Bestellnummer des Kunden';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."CHARGE_ID" is 'ID der Charge';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."CREATED_DATE" is 'creation date+time of this dataset';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."CREATED_LOGIN_ID" is 'login id of the user creating this dataset';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."EINSATZ" is 'Gewicht Einsatz incl. Verschnitt und Schrott (Noch nicht gefüllt)';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."EXT_ARBEITS_ANWEISUNG" is 'URL zur Arbeitsanweisung';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."FA_AG" is 'Arbeitsgang des Auftrags';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."FA_UPOS" is 'Unterposition des Arbeitsgangs';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."FIRMA_NR" is 'Firmennummer in der Datenbank';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."FREIG_STATUS" is '"AR" Aktuell Rüsten"AP" Aktuell in Produktion, "TF" Teilfertigung gemeldet';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."FREIG_WANN" is 'Wann wurde Fertig gemeldet';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."FREIG_WER" is 'Wer hat Fertig gemeldet';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."FREMD_ZEICHNUNG" is 'Externe Zeichnung';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."GEWICHT" is 'Gewicht der gefertigten Teile (Noch nicht gefüllt)';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."JOB_SEQUENZ" is 'Job Sequenz als Abarbeitungsreihenfolge für selektierte Splitts';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."KATEGORIE" is 'Kategorie z.B. SAMPLE, Nachschreiber, ...';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."KD_ART_NR" is 'Kundenartikelnummer';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."KENZ_LETZT_AG" is '1 Wenn letzter Prod. AG';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."KENZ_LHM_DRUCK" is '''T'' = Bei jedem Karton soll auch ein Etikett gedruckt werden';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."KUNDEN_AB" is 'AB Nummer des Kundenauftrags';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."KUNDEN_AB_POS" is 'AB Positionsnummer des Kundenauftrags';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."KUNDEN_AB_TEXT" is 'Beschreibender Text zum  Kundenauftrags';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."KUNDEN_AB_UPOS" is 'AB Unterposition des Kundenauftrags';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."KUNDEN_NR" is 'Kundennummer für den Auftrag';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."KUNDEN_NR_ADR_LIEFER" is 'Lieferadresse (Kunden; Gruppenmerkmal ist die Kundenummer)';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."LAST_CHANGE_DATE" is 'change date+time of this dataset';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."LAST_CHANGE_LOGIN_ID" is 'login id of the user changing this dataset';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."LEAD_LEITZAHL" is 'Leitzahl des Primärauftrag';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."LEITZAHL" is 'Leitzahl des Fertigungsauftrags (KLEIT)';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."LHM_ANZ" is 'Sollmenge Anz. Gebinde';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."LHM_ANZ_IST" is 'Istmenge Anz. Gebinde';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."LHM_MENGE" is 'Menge (Stück) im LHM';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."LHM_NAME" is 'Art, Name des LHM''s Bsp.: K600 als Karton 600';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."LOHN_ARBEIT" is 'Ist der Auftrag Lohnarbeit ''T''=True, ''F''=False  -> verlängerte Werkbank, soll bevorzugt KONSI-Bestände des Kunden verwenden ';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."LTE_ANZ" is 'Sollmenge Anz. LTE';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."LTE_ANZ_IST" is 'Istmenge Anz. LTE';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."LTE_LHM_LAGEN" is 'Aus ISI_ARTIKEL oder Schnittstelle';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."LTE_LHM_PRO_LAGE" is 'Aus ISI_ARTIKEL oder Schnittstelle';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."LTE_MENGE" is 'Menge (Stück) im LTE';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."LTE_NAME" is 'Art, Name der Transporteinheit z.B. EURO für EURO-PALETTE';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."LUECKENFUELLER" is '"Lückenfüller ''F'' False (Nein) (Zwischenplanen) ''T'' = Ja"';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MAX_TAKT_AUSF_ZEIT" is 'Eine Störung beginnt wenn x takte ausgefallen sind';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MAX_TAKT_ZEIT" is 'Maximale taktzeit';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MA_HERSTELLER_KUERZEL_LISTE" is 'Wenn Herstelle-Rein, dann ist hier der Hersteller als Liste hinterlegt Wert mit ;';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MA_RESERVIERT" is 'Ist der Rohstoff (Materialanforderung) Reserviert T=Ist Reserviert, F=Ist nicht reserviert';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MA_RES_CHARGE_ID" is 'Wenn ID gefüllt, dann muss Chargenrein der Rohstoff verwendet werden';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MA_RES_MENGE" is 'Welche Menge  Rohstoff (Materialanforderung) ist Reserviert';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MA_RES_MENGE_KOMM" is 'Welche Menge  Rohstoff wurde berreitgestellt / Kommissioniert';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MDE_IST_MG" is 'Bereits gefertigte Menge in diesem AG aus MDE';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MDE_IST_MG_B" is 'Angefalle Menge in B-Qualität für diesen AG aus MDE';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MDE_IST_MG_B_T" is 'Angefalle Menge in B-Qualität für diesen AG aus MDE Tag';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MDE_IST_MG_RUESTEN" is 'Angefalle Menge beim Rüsten und Anfahren für diesen AG aus MDE';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MDE_IST_MG_RUESTEN_T" is 'Angefalle Menge beim Rüsten und Anfahren für diesen AG aus MDE Tag';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MDE_IST_MG_SCHROTT" is 'Angefalle Schrottmenge für diesen AG aus MDE';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MDE_IST_MG_SCHROTT_T" is 'Angefalle Schrottmenge für diesen AG aus MDE Tag';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MDE_IST_MG_T" is 'Bereits gefertigte Menge in diesem AG aus MDE Tag';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MDE_MICRO_STOP" is 'Angefallene Microstops aus MDE';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MDE_MICRO_STOP_T" is 'Angefallene Microstops aus MDE Tag';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."MIN_TAKT_ZEIT" is 'Minimale Takzeit';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."NIO_RES_ID" is 'Resource, auf der NIO Teile Nachbearbeitet werden können. Kann auch als Ausschleuspunkt genutzt werden';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."NR_PRUEFUNG" is 'Nummer der Prüfung (Nicht der Stammsatz der die Prüfung beschreibt)';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."NUTZEN" is 'Nutzen in % (Noch nicht gefüllt)';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."PACKSCHEMA_KOPF_ID" is 'ID / Name des Packschemas';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."PRIMAER_LEITZAHL" is 'Leitzahl des Primärauftrag';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."PRIORITAET" is 'Priorität des Fertigungsauftrags';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."PROD_MENGE_P_EINHEIT" is 'Menge je Einheit als Abs. Multiplikator oder Divisor. Bedarfsmenge zum AG';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."PROD_MENGE_P_EINHEIT_OP" is '''ABS'' = Absolute -> Immer genau diese Menge ''MUL'' = Multiplizieren, ''DIV'' = Dividieren';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."PROD_PARAMS" is 'Optional: Parameter die ggf. zusammen mit dem Maschinenprogr. an die Resource gesendet werden.';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."PROD_ZEIT_ERF" is 'Erfasste netto Produktionszeit in Minuten';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."PROD_ZEIT_GEPL" is 'Geplante netto Produktionszeit';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."PROD_ZEIT_IST" is 'Angefallene netto Produktionszeit';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."QUITT_GRUPPE_AG" is 'Quittierungs-Gruppe der quittierenden Pos_Nr, sonst eigene Pos_Nr.';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."RCV_AG_IST_MG" is 'Bereits gefertigte Menge in diesem AG die zum HOST gesendet wurde';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."RCV_AG_IST_MG_B" is 'Angefalle Menge in B-Qualität für diesen AG die zum HOST gesendet wurde';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."RCV_AG_IST_MG_RUESTEN" is 'Angefalle Menge beim Rüsten und Anfahren für diesen AG die zum HOST gesendet wurde';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."RCV_AG_IST_MG_SCHROTT" is 'Angefalle Schrottmenge für diesen AG die zum HOST gesendet wurde';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."RCV_PROD_ZEIT_ERF" is 'Erfasste netto Produktionszeit in Minuten - Aus Anmeldungen in BDE_PROD_KOPF_MA - Mitarbeiterstunden übertragen';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."RCV_PROD_ZEIT_IST" is 'Angefallene netto Produktionszeit in Minuten die zum HOST gesendet wurde';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."RCV_RUEST_ZEIT_ERF" is 'Erfasste Rüstzeit in Minuten - Aus Anmeldungen in BDE_PROD_KOPF_MA - Mitarbeiterstunden übertragen';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."RCV_RUEST_ZEIT_IST" is 'Angefallene Rüstzeit in Minuten die zum HOST gesendet wurde';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."RCV_STOER_ZEIT_IST" is 'Angefallene Ausfallzeiten in Minuten die zum HOST gesendet wurde';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."RES_ID" is 'Maschinen ID aus der Resourcentabelle falls eindeutig';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."RUEST_ZEIT_ERF" is 'Erfasste Rüstzeit in Minuten';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."RUEST_ZEIT_GEPL" is 'Geplante Rüstzeit';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."RUEST_ZEIT_IST" is 'Angefallene Rüstzeit';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."SATZART" is '"V" Verrichten, "M" = Materialanforderung';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."SCHROTT" is 'Gewicht Schrott (Noch nicht gefüllt)';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."SCHROTT_PROZ" is 'Ausschuss in Prozent';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."SEQ_NR" is 'Sequenz-Nummer, für das Zielprodukt auf der Fertigungslinie Montage - Ab DB31';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."SID" is 'Datenbank für Konsolidierung';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."START_BATCH_BY_ORDER_START" is 'Dieser Batch wird gestartet, wenn der AG auf der Maschine angemeldet wird';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."STATUS_BEGIN" is 'Seit wann gilt dieser Status';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."STATUS_FREIGABE" is 'Status der Freigabe';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."STATUS_ID" is '000 = In Produktion, sonst Nummer der Störung';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."STATUS_RES_ID" is 'Status der Resource (Wenn eindeutige ID)';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."STOER_ZEIT_ERF" is 'Erfasste  Ausfallzeiten in Minuten';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."STOER_ZEIT_GEPL" is 'Geplante, Berücksichtigte Stillstandszeit';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."STOER_ZEIT_IST" is 'Angefallene Ausfallzeiten';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."TERMIN_ENDE_ERF" is 'Erfasstes Produktionsende';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."TERMIN_ENDE_GEPL" is 'Geplantes Produktionsende';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."TERMIN_ENDE_IST" is 'Echtes Produktionsende';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."TERMIN_START_ERF" is 'Erfasster Produktionsstart';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."TERMIN_START_FRUEH" is 'Frühester Start Termin';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."TERMIN_START_GEPL" is 'Geplanter Produktionsbeginn';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."TERMIN_START_IST" is 'Echter Produktionsstart';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."TERM_BEST" is 'Bestätigter Termin in dd.mm.yyyy hh24:mi:ss';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."TERM_WUNSCH" is 'Wunschtermin in dd.mm.yyyy hh24:mi:ss';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."TRANSP_ZEIT" is 'Transportzeit für die Lieferung zum Kunden in STD';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."VERBRAUCH" is 'Gewicht Verbrauch (Noch nicht gefüllt)';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."VORGANGSQUALIFIKATION" is 'Qualifikation, die das Personal zur Bedienung des Vorgangs benötigt';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."ZEICHNUNG" is 'Externe Zeichnung';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."ZEICHNUNGNAME" is 'Zeichnungsname (*.TIF)';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."ZEICHNUNG_INDEX" is 'ZeichnungIndex';
comment on column DIRKSPZM32.BDE_FA_AUFTRAG_HIST."ZEIT_EINHEIT" is 'Benötigte Zeit je Einheit (Zykluszeit / (Stück je Zyklus)';



-- sqlcl_snapshot {"hash":"913fbf1b77fd4c11cc0aabdb58c4899c5fcedb1e","type":"COMMENT","name":"bde_fa_auftrag_hist","schemaName":"dirkspzm32","sxml":""}