comment on table DIRKSPZM32.EDI_VDA4987_DOCUMENT is 'VDA4987 Main Table / Haupttabelle';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."BUYER_ADDRESS_DESC" is 'Name and address description / Zeile für Name und Anschrift (an..35); Buyer''s name and address / Käufer (Kunde) ID, Name, Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."BUYER_CITY" is 'City name / Ort (an..35); Buyer''s name and address / Käufer (Kunde) ID, Name, Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."BUYER_COUNTRY_ID" is 'Country identifier / Ländername Code (an..3); Buyer''s name and address / Käufer (Kunde) ID, Name, Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."BUYER_COUNTRY_SUB" is 'Country subdivision identifier / Land-Untereinheit, z.B. NDS (an..9); Buyer''s name and address / Käufer (Kunde) ID, Name, Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."BUYER_ID" is 'Party identifier number / Beteiligter, Identifikation (an..35); Buyer''s name and address / Käufer (Kunde) ID, Name, Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."BUYER_NAME1" is 'Party name / Beteiligter (an..35); Buyer''s name and address / Käufer (Kunde) ID, Name, Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."BUYER_NAME2" is 'Party name / Beteiligter (an..35); Buyer''s name and address / Käufer (Kunde) ID, Name, Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."BUYER_POSTAL_CODE" is 'Postal identification code / Postleitzahl (an..17); Buyer''s name and address / Käufer (Kunde) ID, Name, Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."BUYER_STREET1" is 'Street and number or post office box identifier / Straße und Hausnummer oder Postfach (an..35); Buyer''s name and address / Käufer (Kunde) ID, Name, Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."BUYER_STREET2" is 'Street and number or post office box identifier / Straße und Hausnummer oder Postfach (an..35); Buyer''s name and address / Käufer (Kunde) ID, Name, Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CARRIER_ADD_PARTY_ID" is 'Reference identifier / Referenz, Identifikation (n..9); Carrier reference / Frachtführer Referenzangaben';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CARRIER_ID" is 'Carrier identifier / Frachtführer, Nummer (an..17); Transport information / Transportinformationen';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CARRIER_TO_ADDRESS_DESC" is 'Name and address description / Zeile für Name und Anschrift (an..35); Carrier name and address / Frachtführer - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CARRIER_TO_CITY" is 'City name / Ort (an..35); Carrier name and address / Frachtführer - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CARRIER_TO_COUNTRY_ID" is 'Country identifier / Ländername Code (an..3); Carrier name and address / Frachtführer - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CARRIER_TO_COUNTRY_SUB" is 'Country subdivision identifier / Land-Untereinheit, z.B. NDS (an..9); Carrier name and address / Frachtführer - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CARRIER_TO_ID" is 'Party identifier number / Beteiligter, Identifikation (an..35); Carrier name and address / Frachtführer - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CARRIER_TO_NAME1" is 'Party name / Beteiligter (an..35); Carrier name and address / Frachtführer - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CARRIER_TO_NAME2" is 'Party name / Beteiligter (an..35); Carrier name and address / Frachtführer - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CARRIER_TO_POSTAL_CODE" is 'Postal identification code / Postleitzahl (an..17); Carrier name and address / Frachtführer - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CARRIER_TO_STREET1" is 'Street and number or post office box identifier / Straße und Hausnummer oder Postfach (an..35); Carrier name and address / Frachtführer - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CARRIER_TO_STREET2" is 'Street and number or post office box identifier / Straße und Hausnummer oder Postfach (an..35); Carrier name and address / Frachtführer - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CODE_LIST_RESP_AGENCY_CODE" is 'Code list responsible agency code / Verantwortliche Stelle für die Codepflege, Code (an..3); Transport information / Transportinformationen';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CONSIGNMENT_GROSS_WEIGHT" is 'Gross weight (mass) excluding transport equipment (carrier equipment). The weight is to be rounded up to full kilogramms / Bruttogewicht - Gewicht (Masse) ausschließlich Transportausrüstung (carriers equipment). Das Gewicht ist auf volle Kilogramm aufzurunden. (n..7)';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CONSIGNMENT_NET_WEIGHT" is 'Weight (mass) of the products. The weight is to be rounded up to full kilogramms. / Gewicht (Masse) der Erzeugnisse. Das Gewicht ist auf volle Kilogramm aufzurunden. (n..7)';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CONSIGNMENT_NUMBER" is 'Unique reference for a shipment. A shipment is to be understood as the entirety of the material that has been loaded into the same means of transport by one shipping point to one recipient. A repetition within one calendar year is not permitted. / Eindeutige Referenznummer, die einer Sendung / Tour / Abfahrt eines Transportmittels zugeordnet ist. Entspricht der Sendungs-Ladungs-Bezugsnummer der VDA Empfehlung 4913. (an..8)';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CONSIGNMENT_TARA_WEIGHT" is 'Tara weight of consignment in kg, Weight (mass) of the packing materials / Taragewicht der Sendung in kg, Gewicht (Masse) der Packmittel (n..12)';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CONSIGNMENT_VOLUME" is 'Consignment volume (Total cube) / Volumen der Sendung';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CONSIGNMENT_VOLUME_UNIT" is 'Measurement Units: DMQ cubic decimetre; LTR litre; MTQ cubic metre';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CREATION_DATE" is 'Date of creation';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CUSTOMER_SHIPMENT_AUTH_ID" is 'Customer shipment authorisation identifier / Kunden-Sendungsfreigabenummer (an..17); Transport information / Transportinformationen';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CUSTOMER_TO_ADDRESS_DESC" is 'Name and address description / Zeile für Name und Anschrift (an..35); Ultimate customer''s name and address / Name und Anschrift des Endkunden';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CUSTOMER_TO_CITY" is 'City name / Ort (an..35); Ultimate customer''s name and address / Name und Anschrift des Endkunden';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CUSTOMER_TO_COUNTRY_ID" is 'Country identifier / Ländername Code (an..3); Ultimate customer''s name and address / Name und Anschrift des Endkunden';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CUSTOMER_TO_COUNTRY_SUB" is 'Country subdivision identifier / Land-Untereinheit, z.B. NDS (an..9); Ultimate customer''s name and address / Name und Anschrift des Endkunden';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CUSTOMER_TO_ID" is 'Party identifier number / Beteiligter, Identifikation (an..35); Ultimate customer''s name and address / Name und Anschrift des Endkunden';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CUSTOMER_TO_NAME1" is 'Party name / Beteiligter (an..35); Ultimate customer''s name and address / Name und Anschrift des Endkunden';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CUSTOMER_TO_NAME2" is 'Party name / Beteiligter (an..35); Ultimate customer''s name and address / Name und Anschrift des Endkunden';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CUSTOMER_TO_POSTAL_CODE" is 'Postal identification code / Postleitzahl (an..17); Ultimate customer''s name and address / Name und Anschrift des Endkunden';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CUSTOMER_TO_STREET1" is 'Street and number or post office box identifier / Straße und Hausnummer oder Postfach (an..35); Ultimate customer''s name and address / Name und Anschrift des Endkunden';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CUSTOMER_TO_STREET2" is 'Street and number or post office box identifier / Straße und Hausnummer oder Postfach (an..35); Ultimate customer''s name and address / Name und Anschrift des Endkunden';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CUSTOMS_CURRENCY" is 'EUR, Code specifying a currency in ISO 4217 three alpha code / Währungscode, verwende ISO 4217 3 alpha Code (an..3)';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."CUSTOMS_VALUE" is 'Customs value of the shipment / Zollwert der Sendung (n..35)';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."DELIVERY_IS_NOT_INV_RELEVANT" is '0/1; 1(true) = Delivery is not invoice relevant / Lieferung ist nicht Rechnungs-relevant';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."DESPATCH_ADVICE_DATE" is 'Creation DateTime of DESADV; Despatch advice date / Datum der DESADV Nachricht';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."DESPATCH_ADVICE_NUMBER" is 'Unique identifier of DESADV assigned by the supplier. No duplicates within one year. Lieferavis Nummer; Beginning of message / Beginn der Nachricht';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."DESPATCH_DATE" is 'Despatch date / Tatsächliches Versanddatum';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."DESTINATION_SYS" is 'Destination System';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."DIRECTION" is 'Direction; I=Inbound; O=Outbound';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."DISCHARGE_LOC_ID" is 'Location identifier / Ortsangabe, Nummer (an..3); Place of discharge  / Anlieferstelle';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."DISCHARGE_LOC_NAME" is 'Location name / Ortsangabe (an..256); Place of discharge  / Anlieferstelle';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."DOCUMENT_ID" is 'Unique Identifier of VDA4987 document; Primary Key';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."EQUIPMENT_ID" is 'ID of used equipment (an..12); Equipment / means of transport (trailer / swap body) / Frachtträger / Transportmittel (Anhänger / Wechselbrücke)';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."EQUIPMENT_TYPE" is 'Equipment type code qualifier: CN = Container; RR = Rail car; SW = Swap body; TE = Trailer / CN = Container; RR = Eisenbahnwaggon; SW = Wechselbehälter/Wechselbrücke; TE = Anhänger (an..3); Equipment / means of transport (trailer / swap body) / Frachtträger / Transportmittel (Anhänger / Wechselbrücke)';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."ESTIMATED_ARRIVAL_DATE" is 'Estimated arrival date / geschätztes Ankunftsdatum';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."EXCESS_TRANSP_RESP_CODE" is 'Excess transportation responsibility code / Besonderer Transport, Verantwortlichkeit, Code (an..3); Transport information / Transportinformationen';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."EXPORT_DATE" is 'Date of export';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."FILENAME" is 'Filename of corresponding VDA4987 document';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."FORWARD_ADD_PARTY_ID" is 'Reference identifier / Referenz, Identifikation (n..9); Freight forwarder reference / Spediteur Referenzangaben';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."FORWARD_TO_ADDRESS_DESC" is 'Name and address description / Zeile für Name und Anschrift (an..35); Freight forwarder name and address / Spediteur - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."FORWARD_TO_CITY" is 'City name / Ort (an..35); Freight forwarder name and address / Spediteur - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."FORWARD_TO_COUNTRY_ID" is 'Country identifier / Ländername Code (an..3); Freight forwarder name and address / Spediteur - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."FORWARD_TO_COUNTRY_SUB" is 'Country subdivision identifier / Land-Untereinheit, z.B. NDS (an..9); Freight forwarder name and address / Spediteur - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."FORWARD_TO_ID" is 'Party identifier number / Beteiligter, Identifikation (an..35); Freight forwarder name and address / Spediteur - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."FORWARD_TO_NAME1" is 'Party name / Beteiligter (an..35); Freight forwarder name and address / Spediteur - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."FORWARD_TO_NAME2" is 'Party name / Beteiligter (an..35); Freight forwarder name and address / Spediteur - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."FORWARD_TO_POSTAL_CODE" is 'Postal identification code / Postleitzahl (an..17); Freight forwarder name and address / Spediteur - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."FORWARD_TO_STREET1" is 'Street and number or post office box identifier / Straße und Hausnummer oder Postfach (an..35); Freight forwarder name and address / Spediteur - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."FORWARD_TO_STREET2" is 'Street and number or post office box identifier / Straße und Hausnummer oder Postfach (an..35); Freight forwarder name and address / Spediteur - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."IMPORT_DATE" is 'Date of import';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."INCOTERMS_LOC_ID" is 'Location identifier / Ortsangabe, Nummer (an..35); Location specification for INCOTERMS / Ortsangabe für INCOTERMS';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."INCOTERMS_LOC_NAME" is 'Location name / Ortsangabe (an..256); Location specification for INCOTERMS / Ortsangabe für INCOTERMS';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."INTERCHANGE_CONTROL_REFERENCE" is 'Unique ID of an interchange; Interchange header / Nutzdaten-Kopfsegment';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."LOADING_LOC_ID" is 'Location identifier / Ortsangabe, Nummer (an..17); Shipping location (Place of loading) / Beladestelle';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."LOADING_LOC_NAME" is 'Location name / Ortsangabe (an..256); Shipping location (Place of loading) / Beladestelle';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."MESSAGE_REFERENCE_NUMBER" is 'Message reference number in the interchange; Message header / Nachrichten-Kopfsegment';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."MESSAGE_TIMESTAMP" is 'DateTime of preparation; Interchange header / Nutzdaten-Kopfsegment';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."MESSAGE_TYPE" is 'Type of message';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."MODIFY_DATE" is 'Date of last modification';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."NUMBER_OF_LOADING_UNITS" is 'Number of loading units of the shipment / Anzahl der Ladeeinheiten der Sendung (n..4)';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."NUMBER_OF_MESSAGES" is 'Number of messages in the interchange (n..6); Interchange trailer / Nutzdaten-Endesegment';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."NUMBER_OF_SEGMENTS" is 'Number of segments in the message (n..6); Message trailer / Nachrichten-Endesegment';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."PREF_AUTH_DESC_CODE" is 'Free text description code / (an..17); Preference authorisation / Präferenzberechtigung';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."PREF_AUTH_LANG_CODE" is 'Code specifying the language name. Use ISO 639-1988 / Sprache, codiert; verwende ISO 639-1988 (an..3); Preference authorisation / Präferenzberechtigung';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."PREF_AUTH_TEXT1" is 'Text of the declaration of preference in accordance with the legal regulations. / Text der Präferenzerklärung entsprechend der gesetzlichen Vorgaben. (an..256); Preference authorisation / Präferenzberechtigung';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."PREF_AUTH_TEXT2" is 'Text of the declaration of preference in accordance with the legal regulations. / Text der Präferenzerklärung entsprechend der gesetzlichen Vorgaben. (an..256); Preference authorisation / Präferenzberechtigung';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."PREF_AUTH_TEXT3" is 'Text of the declaration of preference in accordance with the legal regulations. / Text der Präferenzerklärung entsprechend der gesetzlichen Vorgaben. (an..256); Preference authorisation / Präferenzberechtigung';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."PREF_AUTH_TEXT4" is 'Text of the declaration of preference in accordance with the legal regulations. / Text der Präferenzerklärung entsprechend der gesetzlichen Vorgaben. (an..256); Preference authorisation / Präferenzberechtigung';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."PREF_AUTH_TEXT5" is 'Text of the declaration of preference in accordance with the legal regulations. / Text der Präferenzerklärung entsprechend der gesetzlichen Vorgaben. (an..256); Preference authorisation / Präferenzberechtigung';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."RECEIVER_ID" is 'Odette ID of the receiver/recipient; Interchange header / Nutzdaten-Kopfsegment';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."RECIPIENT_REFERENCE" is 'Recipient''s reference/password; Interchange header / Nutzdaten-Kopfsegment';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."REQUESTED_DELIVERY_DATE" is 'Requested delivery date / Soll-Wareneingangstermin';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."REQUESTED_SHIPPING_DATE" is 'Shipping DateTime as requested by buyer. The date is based on the duration of transport as determined by the buyer. Das vom Käufer erwünschte Versanddatum; Requested shipment date / geforderter Versand-Abholtermin';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."REVERSE_ROUTING_ADDRESS" is 'Address for reverse routing; Interchange header / Nutzdaten-Kopfsegment';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SEAL_NUMBER" is 'Seal number / Plombennummer (an..35)';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SELLER_ADDITIONAL_PARTY_ID" is 'Reference identifier / Referenz, Identifikation (an..70); Seller (Supplier) Reference / Verkäufer (Lieferant) Referenzangaben';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SELLER_ADDRESS_DESC" is 'Name and address description / Zeile für Name und Anschrift (an..35); Seller''s name and address / Name und Anschrift des Verkäufers';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SELLER_CITY" is 'City name / Ort (an..35); Seller''s name and address / Name und Anschrift des Verkäufers';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SELLER_COUNTRY_ID" is 'Country identifier / Ländername Code (an..3); Seller''s name and address / Name und Anschrift des Verkäufers';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SELLER_COUNTRY_SUB" is 'Country subdivision identifier / Land-Untereinheit, z.B. NDS (an..9); Seller''s name and address / Name und Anschrift des Verkäufers';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SELLER_ID" is 'Party identifier number / Beteiligter, Identifikation (an..35); Seller''s name and address / Name und Anschrift des Verkäufers';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SELLER_NAME1" is 'Party name / Beteiligter (an..35); Seller''s name and address / Name und Anschrift des Verkäufers';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SELLER_NAME2" is 'Party name / Beteiligter (an..35); Seller''s name and address / Name und Anschrift des Verkäufers';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SELLER_POSTAL_CODE" is 'Postal identification code / Postleitzahl (an..17); Seller''s name and address / Name und Anschrift des Verkäufers';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SELLER_STREET1" is 'Street and number or post office box identifier / Straße und Hausnummer oder Postfach (an..35); Seller''s name and address / Name und Anschrift des Verkäufers';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SELLER_STREET2" is 'Street and number or post office box identifier / Straße und Hausnummer oder Postfach (an..35); Seller''s name and address / Name und Anschrift des Verkäufers';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SENDER_ADDITIONAL_PARTY_ID" is 'Reference identifier / Referenz, Identifikation (n..9); Message Sender name and address / Sender der Nachricht - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SENDER_ADDR_ID" is 'Party identifier number / Beteiligter, Identifikation (an..10); Message Sender name and address / Sender der Nachricht - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SENDER_CITY" is 'City name / Ort (an..35); Message Sender name and address / Sender der Nachricht - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SENDER_COUNTRY_ID" is 'Country identifier / Ländername Code (an..3); Message Sender name and address / Sender der Nachricht - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SENDER_COUNTRY_SUB" is 'Country subdivision identifier / Land-Untereinheit, z.B. NDS (an..9); Message Sender name and address / Sender der Nachricht - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SENDER_ID" is 'Odette ID of the sender; Interchange header / Nutzdaten-Kopfsegment';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SENDER_NAME1" is 'Party name / Beteiligter (an..35); Message Sender name and address / Sender der Nachricht - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SENDER_NAME2" is 'Party name / Beteiligter (an..35); Message Sender name and address / Sender der Nachricht - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SENDER_POSTAL_CODE" is 'Postal identification code / Postleitzahl (an..17); Message Sender name and address / Sender der Nachricht - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SENDER_STREET1" is 'Street and number or post office box identifier / Straße und Hausnummer oder Postfach (an..35); Message Sender name and address / Sender der Nachricht - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SENDER_STREET2" is 'Street and number or post office box identifier / Straße und Hausnummer oder Postfach (an..35); Message Sender name and address / Sender der Nachricht - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_FROM_ADDRESS_DESC" is 'Name and address description / Zeile für Name und Anschrift (an..35); Ship from''s name and address / Warenversender - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_FROM_ADD_PARTY_ID" is 'Reference identifier / Referenz, Identifikation (n..9); Ship from Reference / Warenversender Referenzangaben';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_FROM_CITY" is 'City name / Ort (an..35); Ship from''s name and address / Warenversender - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_FROM_COUNTRY_ID" is 'Country identifier / Ländername Code (an..3); Ship from''s name and address / Warenversender - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_FROM_COUNTRY_SUB" is 'Country subdivision identifier / Land-Untereinheit, z.B. NDS (an..9); Ship from''s name and address / Warenversender - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_FROM_ID" is 'Party identifier number / Beteiligter, Identifikation (an..35); Ship from''s name and address / Warenversender - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_FROM_NAME1" is 'Party name / Beteiligter (an..35); Ship from''s name and address / Warenversender - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_FROM_NAME2" is 'Party name / Beteiligter (an..35); Ship from''s name and address / Warenversender - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_FROM_POSTAL_CODE" is 'Postal identification code / Postleitzahl (an..17); Ship from''s name and address / Warenversender - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_FROM_STREET1" is 'Street and number or post office box identifier / Straße und Hausnummer oder Postfach (an..35); Ship from''s name and address / Warenversender - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_FROM_STREET2" is 'Street and number or post office box identifier / Straße und Hausnummer oder Postfach (an..35); Ship from''s name and address / Warenversender - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_TO_ADDRESS_DESC" is 'Name and address description / Zeile für Name und Anschrift (an..35); Ship to''s name and address / Warenempfänger - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_TO_CITY" is 'City name / Ort (an..35); Ship to''s name and address / Warenempfänger - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_TO_COUNTRY_ID" is 'Country identifier / Ländername Code (an..3); Ship to''s name and address / Warenempfänger - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_TO_COUNTRY_SUB" is 'Country subdivision identifier / Land-Untereinheit, z.B. NDS (an..9); Ship to''s name and address / Warenempfänger - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_TO_ID" is 'Party identifier number / Beteiligter, Identifikation (an..35); Ship to''s name and address / Warenempfänger - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_TO_NAME1" is 'Party name / Beteiligter (an..35); Ship to''s name and address / Warenempfänger - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_TO_NAME2" is 'Party name / Beteiligter (an..35); Ship to''s name and address / Warenempfänger - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_TO_NAME3" is 'Party name / Beteiligter (an..35); Ship to''s name and address / Warenempfänger - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_TO_NAME4" is 'Party name / Beteiligter (an..35); Ship to''s name and address / Warenempfänger - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_TO_POSTAL_CODE" is 'Postal identification code / Postleitzahl (an..17); Ship to''s name and address / Warenempfänger - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_TO_STREET1" is 'Street and number or post office box identifier / Straße und Hausnummer oder Postfach (an..35); Ship to''s name and address / Warenempfänger - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SHIP_TO_STREET2" is 'Street and number or post office box identifier / Straße und Hausnummer oder Postfach (an..35); Ship to''s name and address / Warenempfänger - Name und Anschrift';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."SUPPLIER_CUSTOMS_CLEARANCE" is '0/1; 1(true) = different from the standard delivery conditions, the supplier clears customs and then invoices the customer / abweichend von den Standardlieferbedingungen führt der Lieferant die Verzollung durch und stellt sie anschließend dem Kunden in Rechnung';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."TERMS_OF_DELIVERY" is 'Delivery or transport terms description code / Liefer- oder Transportbedingungen, Code (an..3)';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."TEST_INDICATOR" is 'Test Indicator, default 0 = false, 1 = true = Test Transmission; Interchange header / Nutzdaten-Kopfsegment';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."TRANSFER_CODE" is 'Returncode of record processing';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."TRANSFER_STATUS" is 'TransferStatus of record, N=New, ...';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."TRANSFER_TEXT" is 'Returntext of record processing';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."TRANSPORT_ID" is 'Transport chain reference / Transportkettenreferenz (an..35)';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."TRANSPORT_MEANS_DESC_CODE" is 'Transport means description code / Art des Transportmittels, Code (an..8); Transport information / Transportinformationen';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."TRANSPORT_MODE_CODE" is 'Transport Mode Codes: 10 Maritime transport; 20 Rail transport; 30 Road transport (default); 40 Air transport; 50 Mail; 60 Multimodal transport; (an..3); Transport information / Transportinformationen';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."TRANSPORT_ORDER_NUMBER" is 'Transport order number / Transportauftragsnummer (an..35)';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."TRANSP_MEANS_IDENT_NAME_ID" is 'Transport means identification name identifier / Transportmittel, Identifikation (an..25); Transport information / Transportinformationen';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."TRANSP_MEANS_NATION_CODE" is 'Transport means nationality code / Nationalität des Transportmittels, Code (a2); Transport information / Transportinformationen';
comment on column DIRKSPZM32.EDI_VDA4987_DOCUMENT."VAT_REG_NUMBER" is 'Unique identifier assigned to a business partner for the purpose of VAT handling by tax authorities. / Eindeutiger Identifier, der einem Geschäftspartner zum Zwecke der umsatzsteuerlichen Behandlung von der Steuerbehörde zugewiesen wurde.(an..17); VAT registration number / Umsatzsteuer ID';



-- sqlcl_snapshot {"hash":"c2aec3c3cf6587242f7cc923fbd0094c68916cb6","type":"COMMENT","name":"edi_vda4987_document","schemaName":"dirkspzm32","sxml":""}