comment on column DIRKSPZM32.FLS_ELEMENT_CFG."AKTIONS_LOGIK" is 'ProgrammLogik aufnahmeAutrag, VollAuftrag, Staubahn, abgabeAuftrag....';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."AUFTR_ART" is 'HALB, VOLL ...';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."DEFAULT_QUELL_ID" is 'Bei RBG mit 2.Stuf. Einlagerung EP sonst frei verwendbar';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."EDITOR_SPERRE" is 'Editor sperre wenn Notstrategie -> Wege aus der Applik. geändert wird dieses  Flag gesetzt';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."ELEMENT_IX" is 'IX unikat für Liste FLS Intern';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."ELEMENT_NAME" is 'Name des Fahrzeugs';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."ELEMENT_TYP" is 'RBG, QTW, ...';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."ENABLED" is 'Nur Enabled wird das  Element vom MFR beauftragt.';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."GESCHWINDIGKEIT_CM_PRO_MIN" is 'Geschwindigkeit des Transportbandes in  CM pro Minute';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."GEWERKE_NR" is 'Gewerke  NR mit dieser nr und der Positions nummer wird das Gewerk eindeutig';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."IS_ZIEL" is '0 = Kein Ziel, 1= internes Ziel, 2= externes Ziel';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."KONFIG_PARAMS" is 'individual Parameter wie in INI Datei  SCANNER=100; Peter=200; ';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."KOORDINAT_BEWEGUNG" is 'Visualisierung in welche Richtung';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."KOORDINAT_GESAMTLAENGE_CM" is 'Gesamtlaenge des Elements in cm';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."KOORDINAT_POS_X_ANFANG_CM" is 'Raumkoordinate des Elements X Pos. Anfangsposition in cm';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."KOORDINAT_POS_X_ENDE_CM" is 'Raumkoordinate des Elements X Pos. Endeposition in cm';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."KOORDINAT_POS_Y_ANFANG_CM" is 'Raumkoordinate des Elements Y Pos. Anfangsposition in cm';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."KOORDINAT_POS_Y_ENDE_CM" is 'Raumkoordinate des Elements Y Pos.  Endeposition in cm';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."KOORDINAT_POS_Z_ANFANG_CM" is 'Raumkoordinate des Elements Z Pos. Anfangsposition in cm';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."KOORDINAT_POS_Z_ENDE_CM" is 'Raumkoordinate des Elements Z Pos.  Endeposition in cm';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."KURZNAME" is 'Kurzname des Fahrzeugs z.B. auch als Hostname verwendbar !!!!!';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."MAX_FE" is 'max. Anzahl an Fertigungseinheiten auf diesem Element';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."POS_NR" is 'positions Nr z.B Positionsnummer des Aufstellungsplans';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."PROGR_NR" is 'Nummer zur verwendung in ';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."RESET_GRUPPEN_ID" is 'Gruppierung für eine  Reset gruppe ';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."SIMULAT_SPS_MT_ZENTEL_SEK" is 'Simulation in Zehntel Sekunden bis MT Anmeldung gesendet wird ';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."SIMULAT_SPS_PQ_ZENTEL_SEK" is 'Simulation in zehntel Sekunden bis Auftrag quittiert wird';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."STRATEGIE_AUFTR_TIMEOUT_ZS" is 'Zehntel Sekunden';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."STRATEGIE_AUSSCHLEUS_MOEGL" is 'Ausschleusen moeglich z.B. immer ausschleusen vom WE auf Default Ziel ';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."STRATEGIE_AUSSCHLEUS_ZIEL_ID" is 'zu welchem ELement wird ausgeschleust z.B. bei einem Konturenfehler';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."STRATEGIE_AUTO_TRANSP_ZIEL_ID" is 'zu welchem Ziel wird transportiert, wenn Palette automatisch am WE z.B. ohne Daten gestartet werden Soll.';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."STRATEGIE_DEFEKT_DEF_ZIEL_ID" is 'Ausschleusziel der einlagerpaletten wenn ein RBG,.. auf defekt gesetzt wird';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."STRATEGIE_DURCHSCHL_MOEGLICH" is 'Hauptsächlich RBG: Kann dieses Fahrzeug Durchschleusen 0=Nein 1= Ja ...';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."STRATEGIE_EINL_AUSL_VERH" is 'Strategie Verhältnis einlagerungen zu Auslagerungen';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."STRATEGIE_ERSATZ_ZIEL_ID" is 'zu welchem Ziel';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."STRATEGIE_LAGERPLATZ" is 'z.B.  RBG Ein-/Auslagerbahn Lagerplatz , RBG Verfahr. Pos. für Bedienereinstieg.';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."STRATEGIE_PKT_BELEGUNG" is 'Strategie Punkte für Belegung je Palette';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."STRATEGIE_PKT_WARTEN" is 'Strategie Punkte für Warten je Sekunde';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."STRATEGIE_PUNKTEVERGABE" is 'nach welcher Strategie Erfolgt die Punktevergabe 1= Standart, 2= TourNummer, 3= Artikel Lagerplatz';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."STRATEGIE_REIHENFOLGE_BIS" is 'Reihenfolge suche bis LTE_ReihenfolgeNr';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."STRATEGIE_REIHENFOLGE_VON" is 'Reihenfolge suche von LTE ReihenfolgeNr';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."STRATEGIE_SCANN_BETR_WAEHLEN" is 'Scannerbetriebsvorwahl möglich ';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."STRATEGIE_VERL_ST_VORG" is 'Verlade-Status vorgabe für eine Ziel Element';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."TELEGR_FC" is 'SPS Auftrags Functionscode';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."TELEGR_FE_ID_ANFANG" is 'SPS Foerder element ID (Auftrags Quellbahn bzw. Auftrags Zielbahn) Anfangsposition in Transportrichtung';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."TELEGR_FE_ID_ENDE" is 'SPS Foerder element ID (Auftrags Quellbahn bzw. Auftrags Zielbahn) Endeposition in Transportrichtung';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."TELEGR_KONTUREN_KONTROLLE" is 'Konturenkontrolle ? an dieser Position';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."TELEGR_KOPPL_NR" is 'Schnittstellennummer über die die Kommunikation zur SPS funktioniert';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."TELEGR_MELD_NR" is 'Meldungs nummer für die Fehler eingetragen wird';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."TELEGR_MT_ABMELDUNG" is 'SPS Palette abgemeldet';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."TELEGR_MT_BELEGT" is 'SPS Palette Anmeldung';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."TELEGR_MT_FREIPLATZ" is 'SPS Platz wieder frei';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."TELEGR_MT_WE" is 'SPS Palette auf WE ';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."TELEGR_PALETTEN_HOEHE" is 'Palettenhoehe an diser Position im Telegramm ?';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."TELEGR_PALETTEN_TYP" is 'Palettentyp an dieser position im  Telegramm';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."TELEGR_SPS_BEREICH_NR" is 'Gruppen nummer, logischer getrennter Bereich';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."VISU_LOGIK" is 'Logik-Name, die in der Visualisierung benutzt werden soll, um die anzuzeigenden Daten aufzubereiten.';
comment on column DIRKSPZM32.FLS_ELEMENT_CFG."ZUSATZ_LOGIK_NAMEN" is 'Zusatz Logik Namen // Kontrollscann AUfgabe Automatischer WT....';



-- sqlcl_snapshot {"hash":"d832f78f0cdfce53a9243810b8653675c70800ad","type":"COMMENT","name":"fls_element_cfg","schemaName":"dirkspzm32","sxml":""}