comment on table DIRKSPZM32.ISI_AVIS_HDR is 'VDA4913, Wareneingangsdaten / Lieferschein AVIS (Wareneingangsankündigung), LFT an Daimler AG';
comment on column DIRKSPZM32.ISI_AVIS_HDR."ABLADESTELLE" is 'Abladestelle, Entladeort der bei der Bestellung angegeben wird';
comment on column DIRKSPZM32.ISI_AVIS_HDR."ABRUF_NR" is 'N4, Abruf-Nummer, z.B. 1234';
comment on column DIRKSPZM32.ISI_AVIS_HDR."ABSCHLUSS_BESTELL_NR" is 'N12, Abschluss-Bestell-Nr. wie in der Bestellung angegeben. Sollte keine Angabe vorhanden sein, wird hier 9 eingetragen.';
comment on column DIRKSPZM32.ISI_AVIS_HDR."ANZ_PACKSTUECKE" is 'N4, Anzahl Packstücke';
comment on column DIRKSPZM32.ISI_AVIS_HDR."BEARBEITUNGS_STATUS" is '''N'' = Neu, ''U'' = Übernommen im Wareneingang, ''E'' = Erledigt';
comment on column DIRKSPZM32.ISI_AVIS_HDR."BEARB_DATUM" is 'Bearbeitungsdatum und -uhrzeit, zuletzt bearbeitet am';
comment on column DIRKSPZM32.ISI_AVIS_HDR."BESTELLER" is 'Besteller, Zeichen des Kunden';
comment on column DIRKSPZM32.ISI_AVIS_HDR."BRUTTO_GEWICHT" is 'N7, Brutto-Gewicht ohne Dezimalstelle, Ware einschl. Verpackung und LHM';
comment on column DIRKSPZM32.ISI_AVIS_HDR."DATEN_EMPF_WERK" is 'Datenempfangswerk, z.B. 10005007 für Sindelfingen';
comment on column DIRKSPZM32.ISI_AVIS_HDR."DATEN_SENDER_NR" is 'Datensendernummer, z.B. 12345678A';
comment on column DIRKSPZM32.ISI_AVIS_HDR."DOK_NR_KUNDE" is 'Dokument-Nr. Kunde';
comment on column DIRKSPZM32.ISI_AVIS_HDR."EINTREFF_DATUM_SOLL" is 'Datum und Uhrzeit, an dem die Ware bei Daimler AG angeliefert werden soll';
comment on column DIRKSPZM32.ISI_AVIS_HDR."ERSTELL_DATUM" is 'Erstellungsdatum und -uhrzeit, erstellt am';
comment on column DIRKSPZM32.ISI_AVIS_HDR."EXPORT_DATUM" is 'Datum und Uhrzeit des Exports durch Service Logic';
comment on column DIRKSPZM32.ISI_AVIS_HDR."FEHLER_CODE" is 'Host-Übertragung Fehlernummer';
comment on column DIRKSPZM32.ISI_AVIS_HDR."FEHLER_TEXT" is 'Host-Übertragung Fehlertext';
comment on column DIRKSPZM32.ISI_AVIS_HDR."FF_UEBERGABE_DATUM" is 'Frachtführer-Übergabe-Datum und Uhrzeit';
comment on column DIRKSPZM32.ISI_AVIS_HDR."FRACHTFUEHRER" is 'Frachtführer, z.B. Müller';
comment on column DIRKSPZM32.ISI_AVIS_HDR."FRANKATUR_SCHLUESSEL" is 'N2, Frankatur-Schlüssel, z.B. 01';
comment on column DIRKSPZM32.ISI_AVIS_HDR."IMPORT_DATUM" is 'Datum und Uhrzeit des Imports durch Service Logic';
comment on column DIRKSPZM32.ISI_AVIS_HDR."KONSIGNATION" is 'N8, Konsignation, ref auf ISI_Adressen ADR_ID';
comment on column DIRKSPZM32.ISI_AVIS_HDR."LADEMETER" is 'N3, Angabe der belegten Meter der Ladefläche (eine Dezimalstelle), z.B. 093';
comment on column DIRKSPZM32.ISI_AVIS_HDR."LAGERHALTER_ID" is 'Lagerhalter-Schlüssel, [blank]';
comment on column DIRKSPZM32.ISI_AVIS_HDR."LAGERORT_KUNDE" is 'Lagerort Kunde, entspricht der Anlieferstelle im Belieferungsprozess,';
comment on column DIRKSPZM32.ISI_AVIS_HDR."LIEFERANTEN_NR" is 'Lieferanten-Nummer, z,B, 12345678';
comment on column DIRKSPZM32.ISI_AVIS_HDR."LIEFERSCHEIN_DATUM" is 'Versanddatum, Datum und Uhrzeit des Lieferscheins ';
comment on column DIRKSPZM32.ISI_AVIS_HDR."LIEFERSCHEIN_NR" is 'N8, Lieferschein-Nummer';
comment on column DIRKSPZM32.ISI_AVIS_HDR."LIEFER_KENNUNG" is 'Lieferungs-Kennung, [blank]';
comment on column DIRKSPZM32.ISI_AVIS_HDR."LKW_ART_SCHLUESSEL" is 'N1, LKW-Art Schlüssel, z.B. 1';
comment on column DIRKSPZM32.ISI_AVIS_HDR."NACHRICHT_DATUM" is 'Datum und Uhrzeit der Nachricht';
comment on column DIRKSPZM32.ISI_AVIS_HDR."NACHRICHT_NR" is 'N5, Datenersteller vergibt NACHRICHT_NR. Datenersteller wiederholt Nummer des vorausgegangenen DFÜ-Laufs als NACHRICHT_NR_A';
comment on column DIRKSPZM32.ISI_AVIS_HDR."NACHRICHT_NR_A" is 'N5, Beschreibung siehe NACHRICHT_NR. Bei der ersten Übertragung ist NACHRICHT_NR_A = 00000';
comment on column DIRKSPZM32.ISI_AVIS_HDR."NACHRICHT_TYP" is 'Nachrichten Typ: Lieferschein, ...';
comment on column DIRKSPZM32.ISI_AVIS_HDR."NACHRICHT_URSPRG" is 'Ursprungsdatei, z.B. M100_r0011239.d01.txt';
comment on column DIRKSPZM32.ISI_AVIS_HDR."NACHRICHT_ZIEL" is 'Zieldatei, MB<3stelligWerk><3stelligWEZielsystem>; z.B. MB050WES';
comment on column DIRKSPZM32.ISI_AVIS_HDR."NETTO_GEWICHT" is 'N7, Netto-Gewicht ohne Dezimalstelle, Ware einschl. Verpackung aber ohne LHM';
comment on column DIRKSPZM32.ISI_AVIS_HDR."SLB_NR" is 'N8, Sendungs-Ladungs-Bezugsnummer, z.B. 12345678';
comment on column DIRKSPZM32.ISI_AVIS_HDR."SPEDITEUR_DFU_SCHLUESSEL" is 'Spediteur DFÜ-Schlüssel';
comment on column DIRKSPZM32.ISI_AVIS_HDR."SPED_DATEN_EMPF" is 'Speditionsdaten-Empfänger, z.B. 12345678';
comment on column DIRKSPZM32.ISI_AVIS_HDR."STORNO_GRUND" is 'Grund wenn STORNO';
comment on column DIRKSPZM32.ISI_AVIS_HDR."TRANSFER_STATUS" is 'Host-Übertragung Status; N=Neu, U=In Übertragung, UE=erfolgreich übertragen, F=Fehler, L=zum Löschen markiert';
comment on column DIRKSPZM32.ISI_AVIS_HDR."TRANSPORTMITTEL_INFO" is 'Transportmittel-Information, z.B. HH-DD 123';
comment on column DIRKSPZM32.ISI_AVIS_HDR."TRANSPORTMITTEL_INFO_ID" is 'Transportmittel-Info-Schlüssel, z.B. 2';
comment on column DIRKSPZM32.ISI_AVIS_HDR."TRANSPORTMITTEL_NR" is 'Transportmittel-Nr., z.B. 471112345';
comment on column DIRKSPZM32.ISI_AVIS_HDR."TRANSPORTMITTEL_SCHLUESSEL" is 'N2, Transportmittel-Schlüssel, 01 = KFZ-Kennzwichen, 02 = Bordero-Nummer, 07 = Expressgut-Nummer, 08 = Waggon-Nummer, 09 = Postpaket-Nummer, 19 = Flugnummer / Luftfrachtbrief-Nr., 11 = Schiffsname';
comment on column DIRKSPZM32.ISI_AVIS_HDR."TRANSPORT_PARTNER_NR" is 'Transportpartner-Nummer, z.B. 12345678';
comment on column DIRKSPZM32.ISI_AVIS_HDR."VERBRAUCHSSTELLE" is 'Verbrauchsstelle, wie im Abruf falls vorhanden';
comment on column DIRKSPZM32.ISI_AVIS_HDR."VERSANDART" is 'N2, Versandart: 01 = LKW (Unterlieferant), 02 = LKW Kunde, 03 = LKW Spedition, 04 = LKW Bahn, 05 = LKW eigen (Lieferant), 08 = Bahn Waggon, 09 = Postsendung, 10 = Luftfracht, 11 = Seefracht, 20 = Privater Paketdienst';
comment on column DIRKSPZM32.ISI_AVIS_HDR."VORGANG_SCHLUESSEL" is 'N2, Vorgangs-Schlüssel, z.B. 40';
comment on column DIRKSPZM32.ISI_AVIS_HDR."WAREN_EMPFAENGER_NR" is 'Waren-Empfänger-Nummer, z.B. 12345678';
comment on column DIRKSPZM32.ISI_AVIS_HDR."WERK_KUNDE" is 'N3, Werk Kunde, z.B. 050';
comment on column DIRKSPZM32.ISI_AVIS_HDR."WERK_LIEFERANT" is 'Werk Lieferant, z.B. AAA';



-- sqlcl_snapshot {"hash":"32742127dbc331efefe64131ba043822310884ff","type":"COMMENT","name":"isi_avis_hdr","schemaName":"dirkspzm32","sxml":""}