comment on table DIRKSPZM32.ISI_KOMM_ORDER is 'Kommisionieraufträge';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."ANZ_LTE" is 'Die Anzahl der LTE''s, die z.B. umetikettiert oder Umpalettiert werden sollen';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."ARTIKEL_ID" is 'Artikel, der kommissioniert/abgepackt werden soll';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."AUF_ID" is 'Verknüpfung zur Order-Pos-Tabelle, falls dies z.B. eine vorbereitende Kommissionierung für eine konkrete Order-Position ist';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."BEARB_ARBEITSPLATZ_ID" is 'Arbeitsplatz, an dem dieser Auftrag bearbeitet wird';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."BEARB_LOGIN_ID" is 'Benutzer, der diesen Auftrag bearbeitet (hat)';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."BEARB_RES_ID" is 'Resource, die diesen Auftrag bearbeitet (Stapler, Roboter, Maschine, Wickler, etc.)';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."BEARB_START_DATUM" is 'Zeitpunkt, an dem die Bearbeitung begonnen wurde';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."CHARGE_ID" is 'Falls relevant, Charge des Artikels, der kommissioniert/abgepackt werden soll';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."FA_AG" is 'Falls relevant, Fertigungs AG des Artikels, der kommissioniert/abgepackt werden soll';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."FA_UPOS" is 'Falls relevant, FE_UPOS des Artikels, der kommissioniert/abgepackt werden soll';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."FERTIG_DATUM" is 'wann wurde die Kommissionierung abegeschlossen';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."FERTIG_LOGIN_ID" is 'Benutzer, der die Kommissionierung durchgeführt und abgeschlossen hat';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."FREIGABE" is 'M=manuelle Freigabe; A=automatisch freigegeben zum Freigabedatum';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."FREIGABE_DATUM" is 'freigabe=A --> automatisch Freigeben am';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."FREIGEGEBEN_DATUM" is 'bei manueller Freigabe: Datum, an dem die Freigabe genehmigt wurde';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."FREIGEGEBEN_LOGIN_ID" is 'bei manueller Freigabe: Benutzer, der die Freigabe genehmigt hat';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."INFO_TEXT" is 'Freier Text an den Kommissionierer';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_ID" is 'Laufende Nummer';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_IST_MENGE" is 'Menge des Artikels, der kommissioniert/abgepackt worden ist';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_LGR_PLATZ" is 'Auf welchem platz wird kommissioniert bzw. soll kommissioniert werden. Neue Leer-LTE wird auf diesem Platz angelegt';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_NEU_ARTIKEL" is 'Bei komm_typ=LC, neue Artikelnummer, nach der Umetikettierung';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_NEU_CHARGE" is 'Bei komm_typ=LC, neue Charge (evtl. des neuen Artikels), nach der Umetikettierung';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_NEU_FA_AG" is 'Bei komm_typ=LC, neuer FA_AG (evtl. des neuen Artikels), nach der Umetikettierung';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_NEU_FA_UPOS" is 'Bei komm_typ=LC, neue FA_UPOS (evtl. des neuen Artikels), nach der Umetikettierung';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_NEU_LEITZAHL" is 'Bei komm_typ=LC, neue Leitzahl (evtl. des neuen Artikels), nach der Umetikettierung';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_NEU_LHM_NAME" is 'LHM-Typ des neuen LHM in den hineinkommissioniert wird (falls automatisch bei Kommissionierung angelegt)';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_NEU_LTE_HOEHE" is 'voraussichtl. Höhe der neuen LTE, auf die draufkommissioniert wird (falls automatisch bei Kommissionierung angelegt)';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_NEU_LTE_NAME" is 'LTE-Typ der neuen LTE auf die draufkommissioniert wird (falls automatisch bei Kommissionierung angelegt)';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_NEU_SERIENNR" is 'Bei komm_typ=LC, neue Seriennummer (evtl. des neuen Artikels), nach der Umetikettierung';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_SCAN_DATEN_Q" is 'Speichern des gescannten Barcodes von der Kommissionierquelle';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_SCAN_DATEN_Z" is 'Speichern des gescannten Barcodes von dem Kommissionierziel';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_SOLL_MENGE" is 'Menge des Artikels, der kommissioniert/abgepackt werden soll';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_TYP" is 'Kommissioniertyp:
KE=Kommissionierung-Entnahme;
KRE=Kommissionierung Rest-Entnahme;
KP=Kommissionierung-Picken;
LC=Label-exChange;
UP=Umpacken;
UPA=Artikelreines Umpacken;
W=Palettenwechsler;
D=reines doppeln;
ZE=Zusatzetikett (z.B. Routinglabel);
MV=Mengen-Validierung;';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_ZIEL_LGR_PLATZ" is 'Ziel-Lagerplatz für den Transport nach der Kommissionierung';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."KOMM_ZIEL_LTE_ID" is 'Falls bekannt, Ziel-LTE auf die Zusammenkommissioniert wird (Mischpalette erstellen)';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."LAM_ID" is 'Falls relevant, welche konkrete LAM soll abkommissioniert/abgepackt werden';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."LEITZAHL" is 'Falls relevant, Leitzahl des Artikels, der kommissioniert/abgepackt werden soll';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."LGR_ORT_QUELLE" is 'Falls relevant, aus welchem Lagerort sollen LTE''s für die Kommissionierung reserviert werden.';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."LHM_HOEHE_LAGE" is 'Höhe einer Lage (LHM''s)';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."LHM_MENGE" is 'Menge im Ziel (LHM) für das Zielgebinde';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."LIEFERSCHEIN_NR" is 'LieferscheinNr';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."LOGIN_ID" is 'Benutzer, der den Datensatz angelegt hat';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."LTE_ID" is 'Falls relevant, von welcher konkreten LTE soll Ware abkommissioniert/abgepackt werden';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."LTE_LHM_LAGEN" is 'Anzahl Lagen (LHM''s) je LTE ->  Anzahl der Lagen auf der Zielpalette für Packschema_aufbau Typ Artikel (ART)';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."LTE_LHM_LAGEN_QUELLE" is 'Anzahl Lagen (LHM''s) je LTE ->  Anzahl der Lagen der vollen Quellpalette';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."LTE_LHM_PRO_LAGE" is 'Anzahl LHM je Lage';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."MENGE" is 'Falls relevant, Menge des Artikels, der kommissioniert/abgepackt werden soll';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."MENGE_BASIS" is 'LKE=kleinste Einheit; LHM=ganzer LHM; LTE=ganze LTE';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."MHD" is 'Falls relevant, min. MHD des Artikels, der kommissioniert/abgepackt werden soll';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."MODUL_BEARBEITER" is 'SLS, LVS, KOMM';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."MODUL_ERZEUGER" is 'ISI, HST, LVS, ORD';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."PACKSCHEMA_KOPF_ID" is 'Zeiger auf LVS_PACKSCHEMA_KOPF';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."PACKSCHEMA_TRAEGER_ID" is 'Zeiger auf LVS_PACKSCHEMA_KOPF, in dem nur der Trägeraufbau beschrieben ist';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."PRIO" is 'Prio für die Bearbeitung';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."P_KOMM_ID" is 'Link auf übergeordneten Kommissionierauftrag';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."SERIENNR_ID" is 'Falls relevant, Seriennummer des Artikels, der kommissioniert/abgepackt werden soll';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."SOLL_DATUM" is 'bis spätestens wann soll die Kommissionierung erledigt sein';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."STATUS" is 'N=Neu;
FB=zur Bearb. Freigeg.;
B=Bearb. beg. (Ware res.);
TVK=Transp. vor Komm.;
TNK=Transp. Nach Komm.;
TVKE;
TNKE;
KA=Komm. aktiv;
KE=Komm. beEndet;
KEH=an Host übertr.;
Z=Zurückgewiesen;';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."STATUS_INFO_TEXT" is 'Kann von Prozessen oder Personen, die den aktuellen Status ändern, verwendet werden um zusätzliche Informationen abzulegen';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."S_EXT_RCV_INFO_TEXT" is 'Feld für Informationen aus dem externen System';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."S_EXT_RCV_KOMM_ID" is 'Externe Nummer (z.B. Lieferscheinnummer vom Host) für den Kommissionierauftrag';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."S_SEND_REF_ID" is 'Referenz ID aus der Sende-Schnittstelle, nachdem die Daten in die Schnittstelle eingetragen sind';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."S_SEND_TAB_NAME" is 'Name der Sende-Schnittstellentabelle';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."TRANSPORT_NACH_KOMM" is 'T=nach der Kommissionierung ist ein Transport zu einem z.B. WA erforderlich';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."TRANSPORT_VOR_KOMM" is 'T=es ist ein Transport zum Kommissionierplatz vor der Kommissionierung erfordelich; F=Kommissionierung wird direkt am Quell-Lagerplatz durchgeführt';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."TRANSP_ID_NACH_KOMM" is 'Transport ID des Transportauftrags nach der Kommissionierung';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."TRANSP_ID_VOR_KOMM" is 'Transport ID des Transportauftrags vor der Kommissionierung';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."TS" is 'Zeitstempel des Datensatzes';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."VORGANG_ID" is 'Verknüpfung zur Order-Kopf-Tabelle, falls dies z.B. eine vorbereitende Kommissionierung für eine Order ist';
comment on column DIRKSPZM32.ISI_KOMM_ORDER."ZUSATZ_ETIKETTEN_NAME" is 'Name des Zusatzetiketts für die Kommissionierung';



-- sqlcl_snapshot {"hash":"b83acd55815bee6fc57ba44d7c5337c11c4aa552","type":"COMMENT","name":"isi_komm_order","schemaName":"dirkspzm32","sxml":""}