comment on table DIRKSPZM32.ISI_FIRMA is 'Irmenstammdaten Adresse etc.';
comment on column DIRKSPZM32.ISI_FIRMA."ADRESS_ID" is '--> ISI_ADRESSEN.ADRESS_ID Adresse in der Adress ID';
comment on column DIRKSPZM32.ISI_FIRMA."ANZ_ETIKETT_JE_LTE" is 'Anzahl gleicher Etiketten die pro Palette gedruckt werden müssen';
comment on column DIRKSPZM32.ISI_FIRMA."BDE_PROD_2W" is 'Wird 2. Wahl eingegeben ''T'' = Ja, ''F'' = False';
comment on column DIRKSPZM32.ISI_FIRMA."BDE_PROD_SCHROTT" is 'Wird Schrott eingegeben ''T'' = Ja, ''F'' = False';
comment on column DIRKSPZM32.ISI_FIRMA."BDE_RUEST_2W" is 'Wird 2. Wahl eingegeben ''T'' = Ja, ''F'' = False';
comment on column DIRKSPZM32.ISI_FIRMA."BDE_RUEST_SCHROTT" is 'Wird Schrott eingegeben ''T'' = Ja, ''F'' = False';
comment on column DIRKSPZM32.ISI_FIRMA."BEZEICHNUNG" is 'Bezeichnung (Name für Statuszeile)';
comment on column DIRKSPZM32.ISI_FIRMA."DEFAULT_LANG_ID" is 'Standardsprache für einen Mandanten (die einzelnen Benutzer können auch noch individuelle Sprachen haben)';
comment on column DIRKSPZM32.ISI_FIRMA."EXT_ETIKETTEN_DRUCK" is 'Ist die Funktion für externen Etikettedruck für diese Firma freigeschaltet (NULL -> übernimmt den Wert aus ISI_SID; ''F'' -> verbietet es explizit; ''T'' -> erlaubt es wenn in ISI_SID freigeschaltet)';
comment on column DIRKSPZM32.ISI_FIRMA."FIRMA_NR" is 'Firmennummer (Ist auch die ADR_NR in der Adressentabelle)';
comment on column DIRKSPZM32.ISI_FIRMA."FW_RES_ARTIKEL" is 'Reservierung der Lagerplätze über Artikel (Achtung, FW Artikel kann auch HW sein (Arbeitsgang) darum auch FA_AG mit abspeichern';
comment on column DIRKSPZM32.ISI_FIRMA."FW_RES_CHARGE" is 'Reservierung der Lagerplätze über Charge (Chargenrein)';
comment on column DIRKSPZM32.ISI_FIRMA."FW_RES_FA_AUFTRAG" is 'Reservierung der Lagerplätze über Auftragsnummer';
comment on column DIRKSPZM32.ISI_FIRMA."FW_RES_KUNDE" is 'Reservierung der Lagerplätze über Kunde';
comment on column DIRKSPZM32.ISI_FIRMA."FW_RES_MHD" is 'Reservierung der Lagerplätze über MHD';
comment on column DIRKSPZM32.ISI_FIRMA."FW_RES_MHD_TAGE" is 'Reservierung der Lagerplätze über MHD Wie lange werden MHD''s als gleich betrachtet';
comment on column DIRKSPZM32.ISI_FIRMA."FW_RES_SERIE" is 'Reservierung der Lagerplätze über Seriennummer';
comment on column DIRKSPZM32.ISI_FIRMA."HW_RES_ARTIKEL" is 'Reservierung der Lagerplätze über Artikel auch FA_AG mit abspeichern';
comment on column DIRKSPZM32.ISI_FIRMA."HW_RES_CHARGE" is 'Reservierung der Lagerplätze über Charge (Chargenrein)';
comment on column DIRKSPZM32.ISI_FIRMA."HW_RES_FA_AUFTRAG" is 'Reservierung der Lagerplätze über Auftragsnummer';
comment on column DIRKSPZM32.ISI_FIRMA."HW_RES_KUNDE" is 'Reservierung der Lagerplätze über Kunde';
comment on column DIRKSPZM32.ISI_FIRMA."HW_RES_MHD" is 'Reservierung der Lagerplätze über MHD';
comment on column DIRKSPZM32.ISI_FIRMA."HW_RES_MHD_TAGE" is 'Reservierung der Lagerplätze über MHD Wie lange werden MHD''s als gleich betrachtet';
comment on column DIRKSPZM32.ISI_FIRMA."HW_RES_SERIE" is 'Reservierung der Lagerplätze über Seriennummer';
comment on column DIRKSPZM32.ISI_FIRMA."INFO" is 'Info / Kommentar';
comment on column DIRKSPZM32.ISI_FIRMA."LABOR_STATUS_ANBRUCH" is 'Laborstatis die bei Anbruchpaletten den ResString aus dem Wert aus RES_STRING_ANBRUCH bekommt NULL = Alle';
comment on column DIRKSPZM32.ISI_FIRMA."LHM_BARCODE_BASIS" is 'Basis der Nummer (Sequenc oder Tabellenname)';
comment on column DIRKSPZM32.ISI_FIRMA."LHM_BARCODE_KOPF" is 'Basisnummer für den Karton';
comment on column DIRKSPZM32.ISI_FIRMA."LHM_BARCODE_LAENGE" is 'Länge des Barcods für Karton icl. Kopf (Basisnummer, SID etc)';
comment on column DIRKSPZM32.ISI_FIRMA."LHM_BARCODE_TYPE" is 'Typ des Barcode für den Karton (Bsp.: CCG, VDA, NVE etc.)';
comment on column DIRKSPZM32.ISI_FIRMA."LHM_ETIKETT_FW" is 'Name des Etiketts für die Transporteinheit Fertigware';
comment on column DIRKSPZM32.ISI_FIRMA."LHM_ETIKETT_ROH" is 'Name des Etiketts für die Transporteinheit Rohstoffe';
comment on column DIRKSPZM32.ISI_FIRMA."LHM_ETIKETT_TF" is 'Name des Etiketts für die Transporteinheit TeilFertig';
comment on column DIRKSPZM32.ISI_FIRMA."LTE_BARCODE_BASIS" is 'Basis der Nummer (SEQ = Sequence LTE = LVS_LTE LHM = LVS_LTE)';
comment on column DIRKSPZM32.ISI_FIRMA."LTE_BARCODE_KOPF" is 'Basisnummer bei Cerealia 34027453 oder SID';
comment on column DIRKSPZM32.ISI_FIRMA."LTE_BARCODE_LAENGE" is 'Länge des Barcods icl. Kopf (Basisnummer, SID etc)';
comment on column DIRKSPZM32.ISI_FIRMA."LTE_BARCODE_TYPE" is 'Typ des Barcode (Bsp.: CCG, VDA, NVE etc.)';
comment on column DIRKSPZM32.ISI_FIRMA."LTE_ETIKETT_ANBRUCH" is 'Name des Etiketts für die Transporteinheit Fertigware und Halbware für Anbruchpaletten';
comment on column DIRKSPZM32.ISI_FIRMA."LTE_ETIKETT_FW" is 'Name des Etiketts für die Transporteinheit Fertigware';
comment on column DIRKSPZM32.ISI_FIRMA."LTE_ETIKETT_ROH" is 'Name des Etiketts für die Transporteinheit Rohstoffe';
comment on column DIRKSPZM32.ISI_FIRMA."LTE_ETIKETT_TF" is 'Name des Etiketts für die Transporteinheit TeilFertig';
comment on column DIRKSPZM32.ISI_FIRMA."MHD_BERECHNUNG" is 'TA= Taggenau MA= Monatsanfang ME=Monatsende  WE= Wochen Ende WA = WochenAnfang';
comment on column DIRKSPZM32.ISI_FIRMA."PROZ_ANBRUCH" is 'Prozentsatz, bis wohin eine Palette als Vollpalette gilt';
comment on column DIRKSPZM32.ISI_FIRMA."RES_STRING_ANBRUCH" is 'Reservierungsstring für Anbruchpaletten';
comment on column DIRKSPZM32.ISI_FIRMA."RW_RES_ARTIKEL" is 'Reservierung der Lagerplätze über Artikel';
comment on column DIRKSPZM32.ISI_FIRMA."RW_RES_CHARGE" is 'Reservierung der Lagerplätze über Charge (Chargenrein)';
comment on column DIRKSPZM32.ISI_FIRMA."RW_RES_FA_AUFTRAG" is 'Reservierung der Lagerplätze über Auftragsnummer';
comment on column DIRKSPZM32.ISI_FIRMA."RW_RES_LIEFERANT" is 'Reservierung der Lagerplätze über Lieferant';
comment on column DIRKSPZM32.ISI_FIRMA."RW_RES_MHD" is 'Reservierung der Lagerplätze über MHD';
comment on column DIRKSPZM32.ISI_FIRMA."RW_RES_MHD_TAGE" is 'Reservierung der Lagerplätze über MHD Wie lange werden MHD''s als gleich betrachtet';
comment on column DIRKSPZM32.ISI_FIRMA."RW_RES_SERIE" is 'Reservierung der Lagerplätze über Seriennummer';
comment on column DIRKSPZM32.ISI_FIRMA."SEP_NVE_KOPF" is 'Wenn die Seperate NVE eine LTE gefüllt werden soll ';
comment on column DIRKSPZM32.ISI_FIRMA."SID" is 'Datenbank dieser Firma';



-- sqlcl_snapshot {"hash":"21a95e5b915efeeeba27391830d604ca65f9c920","type":"COMMENT","name":"isi_firma","schemaName":"dirkspzm32","sxml":""}