comment on table DIRKSPZM32.ISI_TRANSPORT_HIST is 'Alle abgeschlossenen oder gelöschte Transporte';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."AUF_ID" is 'Auftrags ID der ISI_Order';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."AUF_ID_EXTERN" is 'host auftragsnr bei externer Beauftragung';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."CHECK_PLATZ_Q_LOGIN_ID" is 'Wurde eine Prüfung für den Quell-Platz für diesem Transport durchgeführt? NULL = Nein, Login ID = Ja';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."CHECK_PLATZ_Z_LOGIN_ID" is 'Wurde eine Prüfung für den Ziel-Platz für diesem Transport durchgeführt? NULL = Nein, Login ID = Ja';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."CHECK_WARE_LOGIN_ID" is 'Wurde eine Warenprüfung für diesem Transport durchgeführt? NULL = Nein, Login ID = Ja';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."FIRMA_NR" is 'Firmennummer id der Datenbank';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."FREIFAHRAUFTRAG" is 'F= Freifahren , N=Normaler Auftrag';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."INFO_TEXT" is 'Infotext für den Transport';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."LAM_BH_VORGANG_ID" is 'Vorgangs_ID für die Zusammenfassung von LAM-Buchungen';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."LEITZAHL" is 'Produktionsnummer wenn Eindeutig auf der ges. Palette';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."LGR_ORT_QUELLE" is 'Lagerort der quelle';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."LGR_ORT_ZIEL" is 'Lagerort des Ziels';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."LGR_PLATZ_QUELLE" is 'Quelle des Auftrags';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."LGR_PLATZ_ZIEL" is 'Ziel des Auftrags';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."LGR_PLATZ_ZIEL_CHECK_NEW" is 'Ziel des Auftrags / Zugeordnet durch lvs_check_transport_ziel';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."LGR_VERWENDUNG_QUELLE" is 'Quelle  ist  WE WA Lager, Puffer ....';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."LGR_VERWENDUNG_ZIEL" is 'Ziel ist WE WA Lager Puffer ...';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."LIEFERSCHEIN" is 'Lieferscheindaten erzeugen ''T'' = Ja, erzeugen, ''F'' = Nein, wird nicht erzeut';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."LI_NR" is 'Lieferschein Nummer';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."LI_POS_NR" is 'Lieferscheinposition -Nummer';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."LKW_NR" is 'Gruppiert meherer Touren (Vorgänge)';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."LTE_ID" is 'Transport ID LTE';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."LTE_LETZTE_BUCHUNG" is 'Letzte Buchung vor diesem Transport';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."MODUL_BEARBEITER" is 'MFR, SLS, PAP papier a la huf aus lvs_lgr_ort isi_modul';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."MODUL_ERZEUGER" is 'ISI,MFR,HST,SLS, LVS';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."PARENT_TRANSP_ID" is 'Vorgelagerter Transport';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."PRIO" is 'Priorät des Aufrags 1=klein 9=Hoch';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."PROGR_NR" is 'Programm nummer für die Bearbeitung  von Sonderaufträgen';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."P_KOMM_ID" is 'Kommissionierauftrag -> PAZ Erweiterung imm Transport - Link auf übergeordneten Kommissionierauftrag (Umpackauftrag)';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."P_KOMM_LHM_HOEHE_LAGE" is 'Kommissionierauftrag -> Höhe einer Lage (LHM''s)';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."P_KOMM_LTE_LHM_LAGEN" is 'Kommissionierauftrag -> Anzahl Lagen (LHM''s) je LTE ->  Anzahl der Lagen auf der Zielpalette für Packschema_aufbau Typ Artikel (ART)';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."P_KOMM_LTE_LHM_PRO_LAGE" is 'Kommissionierauftrag -> Anzahl LHM je Lage';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."P_KOMM_PACKSCHEMA_KOPF_ID" is 'Kommissionierauftrag -> Zeiger auf LVS_PACKSCHEMA_KOPF';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."QUELLE_LEER_PROGR_NR" is '1=Auftrag löschen';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."RES_ID" is 'Resource aus isi_resource die mit dem Transport beauftragt wird';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."SID" is 'Datenbank für Konsolidierung';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."SOLL_FERTIG_BIS" is 'Dieser Transport muss fertig sein (BIS). Un diese Uhrzeit';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."STATUS" is 'F=Frei,  Z=Zugewiesen, B=Begonnen (Resource bewegt sich zur LTE), T=LTE wird transportiert';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."TRANSPORTMITTEL_GRUPPE" is 'Gesetzt von MFR ,SLS gruppierung erst mal noch frei';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."TRANSPORTMITTEL_ID" is 'Gesetzt von MFR,SLS RFZ_1=1  oder bei Stapler aus Resource';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."TRANSPORTMITTEL_TYP" is 'gesetzt von MFR,SLS  R=RBG  S=Stapler H=Hubwagen B=Bediener';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."TRANSPORT_GRUPPE" is 'Z.B. Beladereihenfolge für einen LKW Tournummer Oetker';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."TRANSPORT_REIHENFOLGE" is 'Feste Transportreihenfolge (Setzt die PRIO-Steuerung ausser Kraft)';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."TRANSP_ID" is 'Transport ID (Sequenz)';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."TRANSP_ID_SOURCE" is 'Quell Auftrag z.B. für Automatisches Freifahren';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."TRANSP_TYP" is '''E'' EInzelauftrag ''T''=Tour ....';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."TS" is 'Timestamp Autragserzeugung';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."UML_ZIEL_RES_ID" is 'RES_ID für das Ziel ';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."USER_ID" is 'Erzeuger des Auftrags';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."VORGANG_ID" is 'Nummer um die Positionen zu Klammern Z.B. Tourennummer';
comment on column DIRKSPZM32.ISI_TRANSPORT_HIST."ZIEL_VOLL_PROGR_NR" is '1=Pause';



-- sqlcl_snapshot {"hash":"5e1809bb7d90f0c3e7cc7fbc08ccca28a3efa6cc","type":"COMMENT","name":"isi_transport_hist","schemaName":"dirkspzm32","sxml":""}