comment on table DIRKSPZM32.LVS_LGR_ORT is 'Beschreibung der Lagerorte';
comment on column DIRKSPZM32.LVS_LGR_ORT."ADRESS_ID" is 'Adressen ID zur Bestimmung wo sich der Lagerort befindet (Standort)';
comment on column DIRKSPZM32.LVS_LGR_ORT."AKT_INVENTUR_ID" is 'NULL = keine Inventur, ansonsten Inventur aktiv. ID aus LVS_INVENTUR';
comment on column DIRKSPZM32.LVS_LGR_ORT."DEFAULT_ABC" is 'ABC Typ 1= A Schnelldreher 2=B Mitteldreher 3 = C Langsamdreher';
comment on column DIRKSPZM32.LVS_LGR_ORT."DEFAULT_BREITE" is 'Vorgabebreite neuer Lagerplatz in mm';
comment on column DIRKSPZM32.LVS_LGR_ORT."DEFAULT_FLAECHEN_STELLPLATZ" is 'Ist dieser Lagerplatz ein Flächenstellplatz (dann können hier auch Spezialpaletten abgestellt werden). Siehe LTE_CFG';
comment on column DIRKSPZM32.LVS_LGR_ORT."DEFAULT_GEFAHREN_KLASSE" is 'Klasse für Gefahrenkennzeichen, Gefahrenklasse des Artikel muss <= sein';
comment on column DIRKSPZM32.LVS_LGR_ORT."DEFAULT_HOEHE" is 'Vorgabehoehe neuer Lagerplatz in mm';
comment on column DIRKSPZM32.LVS_LGR_ORT."DEFAULT_LGR_TEMP" is 'Temperatur des Lagers';
comment on column DIRKSPZM32.LVS_LGR_ORT."DEFAULT_LTE_NAMEN_CFG" is 'Vorgabe der TE die generell z.B. wenn Leer eingelagert werden dürfen';
comment on column DIRKSPZM32.LVS_LGR_ORT."DEFAULT_MAX_LTE" is 'Vorgabe Max TE je Lagerplatz';
comment on column DIRKSPZM32.LVS_LGR_ORT."DEFAULT_TIEFE" is 'Vorgabetiefe neuer Lagerplatz in mm';
comment on column DIRKSPZM32.LVS_LGR_ORT."DEFAULT_WAREN_TYPEN_CFG" is 'welche warentypen ''FW'',HW'',''RW'' darf hier hinein!';
comment on column DIRKSPZM32.LVS_LGR_ORT."DEFAULT_WERT_KLASSE" is 'Klasse für Warenwert, Wertklasse des Artikels muss <= diesem sein';
comment on column DIRKSPZM32.LVS_LGR_ORT."FIRMA_NR" is 'Firmennummer in der Datenbank';
comment on column DIRKSPZM32.LVS_LGR_ORT."HOST_LGR_ORT" is 'Lagerort im Frempsystem (HOST)';
comment on column DIRKSPZM32.LVS_LGR_ORT."KOMM_AUSWEICH_LGR_PLATZ" is 'Kommissionierlagerplatz, wenn keine Kommissionierung an diesem lgr_ort möglich ist';
comment on column DIRKSPZM32.LVS_LGR_ORT."KOMM_DIREKT_MOEGL" is 'Ist an diesem Lagerort eine Kommissionierung möglich (T = möglich, F = nicht möglich)';
comment on column DIRKSPZM32.LVS_LGR_ORT."KOMM_NEU_LTE_LGR_PLATZ" is 'Standardlagerplatz für neue LTEs bei Kommissionierung';
comment on column DIRKSPZM32.LVS_LGR_ORT."KOMM_PICKEN_MOEGL" is 'Ist an diesem Lagerort das Picken von LHMs möglich (T = möglich, F = nicht möglich)';
comment on column DIRKSPZM32.LVS_LGR_ORT."LETZTE_INVENTUR_DATUM" is 'NULL = noch keine Inventur erfolgt, ansonsten: Datum der letzten Inventur';
comment on column DIRKSPZM32.LVS_LGR_ORT."LETZTE_INVENTUR_ID" is 'NULL = noch keine Inventur erfolgt, ansonsten: Inventur anhand ID durchgeführt';
comment on column DIRKSPZM32.LVS_LGR_ORT."LETZTE_INVENTUR_LOGIN_ID" is 'NULL = noch keine Inventur erfolgt, ansonsten: Wer hat die Inventur hier durchgeführt/beaufsichtigt';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_DIM_E_TEXT" is 'Bezeichnung für den Log. Bezeichner Ebene';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_DIM_G_TEXT" is 'Bezeichnung für den Log. Bezeichner Gang';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_DIM_P_TEXT" is 'Bezeichnung für den Log. Bezeichner Platz';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_DIM_R_G_U_GEGENUEBER" is 'Liegt in diesem Lagerort Grade und Ungrade regalnimmern gegebüber';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_DIM_R_TEXT" is 'Bezeichnung für den Log. Bezeichner Regal';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_DIM_T_TEXT" is 'Bezeichnung für den Log. Bezeichner Tiefe';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_EINL_OPTI" is 'Soll an diesem Lagerort nach der WE-Scannung und Findung eiens Platz nochmal nach einem besseren gesucht werden';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_LTE_NAMEN" is 'alle LTE_NAMEN, Die in diesen Lagerort gelagert werden dürfen z.B. ''EURO'';''INDU'';''CHEP'' ;...';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_MAX_BREITE" is 'MAX-Breite des Lagerplatz in mm';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_MAX_HOEHE" is 'MAX-Hoehe des Lagerplatz in mm';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_MAX_TIEFE" is 'MAX-Tiefe des Lagerplatz in mm';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_MIN_BREITE" is 'MIN-Breite des Lagerplatz in mm';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_MIN_HOEHE" is 'MIN-Hoehe des Lagerplatz in mm';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_MIN_TIEFE" is 'MIN-Tiefe des Lagerplatz in mm';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_ORT" is 'Kurzname oder Nummer des Lagerorts';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_ORT_BLOCK_TRANS_ERLAUBT" is 'Darf eine Palette ausgelagert werden, wenn sie von einer anderen blockiert wird.';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_ORT_FUEHREND_SYSTEM" is 'Für diesen Lagerort ist ISI das führende System oder das hier bezeichnete';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_ORT_MAX_KG_PROZ" is 'Maximal darf dieser Prozentsatz in KG in Plätze der LVS_LGR.LGR_KG_GRUPPE eingelagert werden';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_ORT_MODUL" is '''MFR'',SLS'',....wer transportiert die Ware dieses Lagerorts Für ISI_TRANSPORT';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_ORT_RASTER_X" is 'Raster im mm für X-Richtung (Breite)';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_ORT_RASTER_Y" is 'Raster im mm für Y-Richtung (Tiefe)';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_ORT_TEXT" is 'Bezeichnung der Lagerorts';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_ORT_VOL_BREITE" is 'Gesamtbreite des Lagerort in mm';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_ORT_VOL_HOEHE" is 'Gesamthoehe des Lagerort in mm';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_ORT_VOL_TIEFE" is 'Gesamttiefe des Lagerort in mm';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_PLATZ_CFG" is 'Config String für die Lagerplatz Bsp.: GG.RR.PPP.EE.TT Gang Regal Platz Ebene Tiefe';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_PLATZ_ETI_PFEIL_RICHT" is 'Pfeilrichtung auf dem Lagerplatzetikett (o/u/r/l zeigt nach oben, unten, rechts oder linkks)';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_PLATZ_RAND_ABSTAND_X" is 'Abstand zum nächsten Lagerplatz in mm';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_PLATZ_RAND_ABSTAND_Y" is 'Abstand zum nächsten Lagerplatz in mm';
comment on column DIRKSPZM32.LVS_LGR_ORT."LGR_TYP" is 'BLK1, SAT1, KANAL1, KANAL_BLOCK1, REG_FACH1 .....';
comment on column DIRKSPZM32.LVS_LGR_ORT."SID" is 'Datenbank für Konsolidierung';
comment on column DIRKSPZM32.LVS_LGR_ORT."STAPLER_LS_ID" is 'ID der Staplerleitsystems';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_ABC" is 'Faktor besser, schlechter für ABC-Abgleich';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_ABSTAND_FAKTOR" is '0 = Abstand Egal 1 = Grosser Abstand Gut -1 kleiner Abstand gut Zusammenstellen';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_ART_RES" is 'Faktor besser, schlechter wenn für einen Kanal eine Artikelreservierung vorgenommen wurde';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_BREITE_RELEVANZ" is 'Faktor mit dem die freihe Breite multpliziert wird um der Lagerplatz zu bewerten
';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_FUELLGRAD_RELEVANZ" is 'Achtung: Funktioniert nur, wenn der Abstans-faktor >0 ist. Faktor mit dem der Füllgrad in Prozent multipliziert wird, wenn im Lager gleichverteilung gewünscht ist';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_GEWICHT_RELEVANZ" is 'Faktor mit dem das Differenzgewicht multpliziert wird um der Lagerplatz zu bewerten';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_HOEHE_RELEVANZ" is 'Faktor mit dem die freihe Hoehe multpliziert wird um den Lagerplatz zu bewerten';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_LGR_PLATZ_AKT_LTE" is 'Um wieviel besser wird der PLatz bei je power(LTE, 2)';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_LGR_PLATZ_VERFUEG" is 'Um wieviel besser wird der PLatz bei je Verfügbaren Platz';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_ORDER_RESERVIERUNG" is 'Um wieviel schlechter wird der PLatz bei je Order Reservierung';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_ORT_ABSTAND_FAKTOR" is 'Abstand der Lagerplätze nach LGR_ORT ';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_PLATZ_AUSL_DISPO" is 'Um wieviel schlechter wird der PLatz bei je Auslagerung';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_PLATZ_FACTOR_MAX" is 'Schlechter darf der Platz in der Bewertung nicht sein (Nur Belegung';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_PLATZ_FALSCH" is '!!! TEXT !!!!! -- Multiplikator für Kanäle die mit anderen Artikeln gefüllt sind';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_PLATZ_LEER" is 'Multiplikator für leeren Platz';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_PLATZ_MISCH_KANAL" is 'Multiplikator für Mischkanäle';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_PLATZ_MISCH_PAL" is 'Multiplikator für Kanäle mit Mischpaletten';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_PLATZ_RES_STRING" is 'Multiplikator für gleichen Reservierungsstring';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_PLATZ_R_FAKTOR" is 'Platz (X-Achse) 0 = Egal  (1) Kleine Gut (-1)Grosse Gut ';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_REGAL_HOEHE_FW" is 'Reservierung (FW) Fertigware (+1) =  von Unten nach Oben,  (-1)  Von Oben nach Unten Hohe Gut (0) Egal (Alt. C.LGR_HOEHE_FW_WERT)';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_REGAL_HOEHE_HW" is 'Reservierung (HW) Fertigware (+1) =  von Unten nach Oben,  (-1)  Von Oben nach Unten Hohe Gut (0) Egal
';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_REGAL_HOEHE_MP" is 'Reservierung (MP) Fertigware (+1) =  von Unten nach Oben,  (-1)  Von Oben nach Unten Hohe Gut (0) Egal
';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_REGAL_HOEHE_RW" is 'Reservierung (RW) Fertigware (+1) =  von Unten nach Oben,  (-1)  Von Oben nach Unten Hohe Gut (0) Egal';
comment on column DIRKSPZM32.LVS_LGR_ORT."STRAT_TIEFE_RELEVANZ" is 'Faktor mit dem die freihe Tiefe multpliziert wird um der Lagerplatz zu bewerten';
comment on column DIRKSPZM32.LVS_LGR_ORT."VERL_VORB_LGR_ORTE" is 'Lagerorte in die Verladungen aus diesem Lagerort vorbereitet werden können.';



-- sqlcl_snapshot {"hash":"0577ff2e953a2e17c22d0090ff8a4467e8ff97ca","type":"COMMENT","name":"lvs_lgr_ort","schemaName":"dirkspzm32","sxml":""}