comment on table DIRKSPZM32.LVS_LAM is 'Lager Artikel Menge (Aktueller Lagerbestand kleinste Einheit)';
comment on column DIRKSPZM32.LVS_LAM."ABNR" is 'Auftragsbestätigungsnummer des Kundenauftragsbestätigung';
comment on column DIRKSPZM32.LVS_LAM."AKT_INVENTUR_ID" is 'NULL = keine Inventur, ansonsten Inventur aktiv. ID aus LVS_INVENTUR';
comment on column DIRKSPZM32.LVS_LAM."ARTIKEL_ID" is 'Artikel ID in ISI_ARTIKEL';
comment on column DIRKSPZM32.LVS_LAM."BEST_NR" is 'Bestellnummer beim Zugang';
comment on column DIRKSPZM32.LVS_LAM."BEST_POS" is 'Bestellposition beim Zugang';
comment on column DIRKSPZM32.LVS_LAM."CHARGE_ID" is 'ID der Charge';
comment on column DIRKSPZM32.LVS_LAM."CHECK_WARE_TRANSP_ID" is 'Transport für den ein Waren-Check festgehalten wird';
comment on column DIRKSPZM32.LVS_LAM."FAE_ID" is 'Fertigungs Einheit ID';
comment on column DIRKSPZM32.LVS_LAM."FAE_ID_POSITION" is 'R = Rechts, L = Links, V = Vorne, H = Hinten, O = Oben, U = Unten';
comment on column DIRKSPZM32.LVS_LAM."FA_AG" is 'Aktueller Arbeitsgang der Leitzahl';
comment on column DIRKSPZM32.LVS_LAM."FA_UPOS" is 'Unterposition der Arbeitsgangs';
comment on column DIRKSPZM32.LVS_LAM."FIRMA_NR" is 'Firmennummer in der Datenbank';
comment on column DIRKSPZM32.LVS_LAM."HERSTELLER_KUERZEL_LISTE" is 'Liste der Hersteller als Kürzel mit Semikolon getrennt';
comment on column DIRKSPZM32.LVS_LAM."KD_ART_NR" is 'Kundenartikelnummer';
comment on column DIRKSPZM32.LVS_LAM."KUNDEN_NR" is 'Kunde für den gefertigt wurde';
comment on column DIRKSPZM32.LVS_LAM."LABOR_STATUS" is 'Laborstatus Q=Quarantäne Q-Prüfung, G= Gesperrt, F=Frei, U=Undefiniert Prüfsystem war offline, W=Warenausgangsprüfung, S=Sonderprüfung';
comment on column DIRKSPZM32.LVS_LAM."LABOR_TEXT" is 'Zusatztext aus Laborergebnis (Bsp. Ware darf nur zu einem bestimmten Kunden)';
comment on column DIRKSPZM32.LVS_LAM."LAM_ID" is 'Lager Artikel Mengen ID auf die gebucht wurde (Bestands Key)';
comment on column DIRKSPZM32.LVS_LAM."LAM_KG" is 'Aktuelles Gewicht der Waren in KG';
comment on column DIRKSPZM32.LVS_LAM."LAM_MHD" is 'Min. Haldbar bis (Datum)';
comment on column DIRKSPZM32.LVS_LAM."LAM_MHD_AUSGABE" is 'min. Haltbar bis aus LAM MHD Druck Datum,';
comment on column DIRKSPZM32.LVS_LAM."LAM_P1" is 'Parameter P1';
comment on column DIRKSPZM32.LVS_LAM."LAM_P10" is 'Parameter P10';
comment on column DIRKSPZM32.LVS_LAM."LAM_P2" is 'Parameter P2';
comment on column DIRKSPZM32.LVS_LAM."LAM_P3" is 'Parameter P3';
comment on column DIRKSPZM32.LVS_LAM."LAM_P4" is 'Parameter P4';
comment on column DIRKSPZM32.LVS_LAM."LAM_P5" is 'Parameter P5';
comment on column DIRKSPZM32.LVS_LAM."LAM_P6" is 'Parameter P6';
comment on column DIRKSPZM32.LVS_LAM."LAM_P7" is 'Parameter P7';
comment on column DIRKSPZM32.LVS_LAM."LAM_P8" is 'Parameter P8';
comment on column DIRKSPZM32.LVS_LAM."LAM_P9" is 'Parameter P9';
comment on column DIRKSPZM32.LVS_LAM."LAM_SEL1" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.LVS_LAM."LAM_SEL10" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.LVS_LAM."LAM_SEL2" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.LVS_LAM."LAM_SEL3" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.LVS_LAM."LAM_SEL4" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.LVS_LAM."LAM_SEL5" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.LVS_LAM."LAM_SEL6" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.LVS_LAM."LAM_SEL7" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.LVS_LAM."LAM_SEL8" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.LVS_LAM."LAM_SEL9" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.LVS_LAM."LAM_TEXT" is 'Zusatztext';
comment on column DIRKSPZM32.LVS_LAM."LEITZAHL" is 'Fertigungsauftrag Nr. (Leitzahl)';
comment on column DIRKSPZM32.LVS_LAM."LETZTE_INVENTUR_DATUM" is 'NULL = noch keine Inventur erfolgt, ansonsten: Datum der letzten Inventur';
comment on column DIRKSPZM32.LVS_LAM."LETZTE_INVENTUR_ID" is 'NULL = noch keine Inventur erfolgt, ansonsten: Inventur anhand ID durchgeführt';
comment on column DIRKSPZM32.LVS_LAM."LETZTE_INVENTUR_LOGIN_ID" is 'NULL = noch keine Inventur erfolgt, ansonsten: Wer hat die Inventur hier durchgeführt';
comment on column DIRKSPZM32.LVS_LAM."LGR_PLATZ" is 'Aktueller Lagerplatz';
comment on column DIRKSPZM32.LVS_LAM."LHM_C_LFD_NR" is 'laufende LHM-Nummer innerhalb der Charge (1,2,...,n)';
comment on column DIRKSPZM32.LVS_LAM."LHM_ID" is 'ID des Lagerhilfsmittel';
comment on column DIRKSPZM32.LVS_LAM."LHM_LFD_NR" is 'laufende LHM-Nummer innerhalb des Auftrags (1,2,...,n)';
comment on column DIRKSPZM32.LVS_LAM."LIEFERANT_NR" is 'Lieferantennummer';
comment on column DIRKSPZM32.LVS_LAM."LI_NR_LIEF" is 'Lieferscheinnummer (Vom Lieferanten bei der Anlieferung)';
comment on column DIRKSPZM32.LVS_LAM."LS_LOGIN_ID" is 'Login ID des Erfassers';
comment on column DIRKSPZM32.LVS_LAM."LTE_ID" is 'ID der Transporteinheit';
comment on column DIRKSPZM32.LVS_LAM."LTE_ID_LIEFERANT" is 'Packstücknummern des Lieferanten';
comment on column DIRKSPZM32.LVS_LAM."MENGE" is 'Aktuelle Menge';
comment on column DIRKSPZM32.LVS_LAM."MENGENEINHEIT_BASIS" is 'Mengeneinheit aus Menge Basis z.B. MENGENEINHEIT oder Name der LHM oder LTE';
comment on column DIRKSPZM32.LVS_LAM."MENGE_BASIS" is 'LKE = Kleinste Einheit, LHM = Name LHM, LTE = Name Transporteinheit';
comment on column DIRKSPZM32.LVS_LAM."NR_PRUEFUNG" is 'Nummer der Prüfung (Nicht der Stammsatz der die Prüfung beschreibt)';
comment on column DIRKSPZM32.LVS_LAM."ORDER_POS_AUF_ID" is 'Reserveriert für Auftrag in ISI_Order (oder -1 = für manuelle Auslagerung, -2 = für manuelle Umlagerung)';
comment on column DIRKSPZM32.LVS_LAM."OWNER_ADDRESS_ID" is 'ID in der ISI_ADRESSEN für KONSI. Ist der Wert != NULL dann ist die Adresse dieser ID Eigentümer der Ware';
comment on column DIRKSPZM32.LVS_LAM."PACKSCHEMA_KOPF_ID" is 'ID / Name des Packschemas';
comment on column DIRKSPZM32.LVS_LAM."PACKSCHEMA_LFDN" is 'Nummer (Reihenfolge) auf der Palette';
comment on column DIRKSPZM32.LVS_LAM."PROD_DATUM" is 'Zeitpunkt des Produktion';
comment on column DIRKSPZM32.LVS_LAM."QS_STATUS" is 'NULL = nicht definiert, 1 = 1. Wahl (A-Ware), 2 = 2. Wahl (B-Ware), S = Schrott, [M = Musterware, ...], ZM = Zuordnungsfehler mit Mail über DIS, Z = Zuordnungsfehler, ZMM = Zuordnung Rohmaterial Fehler mit Mail über DIS';
comment on column DIRKSPZM32.LVS_LAM."RES_ID" is 'Resourcen ID (Produktionsmaschine)';
comment on column DIRKSPZM32.LVS_LAM."RES_LOGIN_ID" is 'Login_ID für den Bearbeiter zur Erkennung der Dispo und für Druckfunktionen (Teilreservierung einer LTE)';
comment on column DIRKSPZM32.LVS_LAM."RES_MENGE" is 'Reservierte Menge für Teilentnahme';
comment on column DIRKSPZM32.LVS_LAM."RES_ZIEL_LTE_ID" is 'Reservierte Menge soll bei Auftrag auf diese LTE gepackt werden';
comment on column DIRKSPZM32.LVS_LAM."SERIE_ID" is 'ID Der Serie';
comment on column DIRKSPZM32.LVS_LAM."SID" is 'Datenbank für Konsolidierung';
comment on column DIRKSPZM32.LVS_LAM."SONST_ID_LIEFERANT" is 'Weitere ID des Lieferanten (Nicht weiter spez.) für Rückverfolgung beim Lieferanten';
comment on column DIRKSPZM32.LVS_LAM."WAREN_TYP" is 'aus ISI_ARTIKEL: RW = Rohware, HW = Teilfertig/Halbfertigware (Zwischenprodukt), FW = Fertigware, VRW = Vorabserie Rohware, VFW = Vorabserie Fertigware';
comment on column DIRKSPZM32.LVS_LAM."ZEICHNUNG" is 'Externe Zeichnung';
comment on column DIRKSPZM32.LVS_LAM."ZEICHNUNG_INDEX" is 'Zeichnungsindex';
comment on column DIRKSPZM32.LVS_LAM."ZUG_DATUM" is 'Zugangsdatum';



-- sqlcl_snapshot {"hash":"ad0e2b0c0f32fdac95869562295a4add141ab47c","type":"COMMENT","name":"lvs_lam","schemaName":"dirkspzm32","sxml":""}