comment on table DIRKSPZM32.LVS_LTE_HIST is 'Transporteinheiten';
comment on column DIRKSPZM32.LVS_LTE_HIST."ABC" is 'A = Schnell B = Mittel C = Langsam';
comment on column DIRKSPZM32.LVS_LTE_HIST."AKT_INVENTUR_ID" is 'NULL = keine Inventur, ansonsten Inventur aktiv. ID aus LVS_INVENTUR';
comment on column DIRKSPZM32.LVS_LTE_HIST."ANZ_UML" is 'Anzahl der Umlagerungen ';
comment on column DIRKSPZM32.LVS_LTE_HIST."AUTO_DEPAL" is 'Automatisches depaletieren möglich? FALSE: nicht möglich, LAGE: Nur Lagenweise depaletieren möglich, LHM: LHM weise depaletierbar, NULL: Status ist unbekannt';
comment on column DIRKSPZM32.LVS_LTE_HIST."FIRMA_NR" is 'Firmennummer in der Datenbank';
comment on column DIRKSPZM32.LVS_LTE_HIST."GEFAHREN_KLASSE" is '0 = Klein, 99 = Hoch';
comment on column DIRKSPZM32.LVS_LTE_HIST."KOMM_MENGE_KONTROLLE" is 'TK = Die Menge muss auf einem Komm-Platz kontrolliert werden, N oder TD LTE kann dierekt zum Ziel, wenn diese komplett benötigt wird';
comment on column DIRKSPZM32.LVS_LTE_HIST."LETZTE_INVENTUR_DATUM" is 'NULL = noch keine Inventur erfolgt, ansonsten: Datum der letzten Inventur';
comment on column DIRKSPZM32.LVS_LTE_HIST."LETZTE_INVENTUR_ID" is 'NULL = noch keine Inventur erfolgt, ansonsten: Inventur anhand ID durchgeführt';
comment on column DIRKSPZM32.LVS_LTE_HIST."LETZTE_INVENTUR_LOGIN_ID" is 'NULL = noch keine Inventur erfolgt, ansonsten: Wer hat die Inventur hier durchgeführt';
comment on column DIRKSPZM32.LVS_LTE_HIST."LGR_PLATZ" is 'Lagerplatz auf dem die TE steht';
comment on column DIRKSPZM32.LVS_LTE_HIST."LKW_NR" is 'Gruppiert meherer Touren (Vorgänge)';
comment on column DIRKSPZM32.LVS_LTE_HIST."LS_LOGIN_ID" is 'Login ID des Erfassers';
comment on column DIRKSPZM32.LVS_LTE_HIST."LTE_AKT_KG" is 'Aktuelles Gewicht der Waren auf dieser Transporteinheit in KG';
comment on column DIRKSPZM32.LVS_LTE_HIST."LTE_AKT_LHM" is 'Anzahl der LHM''s auf diesem LTE';
comment on column DIRKSPZM32.LVS_LTE_HIST."LTE_ETI_DRUCK_STATUS" is 'NULL = Kein Etikett gedruckt, SD= Soll Drucken (etikett muss noch gedruckt werden), D=Etikett gedruckt und vorhanden';
comment on column DIRKSPZM32.LVS_LTE_HIST."LTE_ID" is 'Transporteinheit ID (PID Paletten ID)';
comment on column DIRKSPZM32.LVS_LTE_HIST."LTE_INV_STATUS" is 'Inventurstatus';
comment on column DIRKSPZM32.LVS_LTE_HIST."LTE_LETZTE_BUCHUNG" is 'Datum und Zeit der letzten Buchung';
comment on column DIRKSPZM32.LVS_LTE_HIST."LTE_NAME" is 'Art, Name der Transporteinheit';
comment on column DIRKSPZM32.LVS_LTE_HIST."LTE_OFFSET_X" is 'X-Position Y-Position Offset zum Mittelpunkt des Lagerplatz in mm (Lagerplatzmittelpunkt)';
comment on column DIRKSPZM32.LVS_LTE_HIST."LTE_OFFSET_Y" is 'Y-Position Offset zum Mittelpunkt des Lagerplatz in mm (Lagerplatzmittelpunkt)';
comment on column DIRKSPZM32.LVS_LTE_HIST."LTE_OFFSET_Z" is 'Z Position der LTE (Absolut)';
comment on column DIRKSPZM32.LVS_LTE_HIST."LTE_STATUS" is 'Z,B. ''BS'' = Wird befüllt, ''BF'' Befüller fertig, kann transportiert werden ....';
comment on column DIRKSPZM32.LVS_LTE_HIST."LTE_VOL" is 'Volumen in m3';
comment on column DIRKSPZM32.LVS_LTE_HIST."LTE_VOLL" is 'A = Anbruch, V = Voll (Std-Menge, oder Angelieferte Menge bei Rohware)';
comment on column DIRKSPZM32.LVS_LTE_HIST."LTE_VOL_BREITE" is 'Gesamtbreite der Transporteinheit in mm';
comment on column DIRKSPZM32.LVS_LTE_HIST."LTE_VOL_HOEHE" is 'Gesamthoehe der Transporteinheit in mm';
comment on column DIRKSPZM32.LVS_LTE_HIST."LTE_VOL_TIEFE" is 'Gesamttiefe der Transporteinheit in mm';
comment on column DIRKSPZM32.LVS_LTE_HIST."MAX_TEMP" is 'maximale temperatur der ware';
comment on column DIRKSPZM32.LVS_LTE_HIST."MIN_TEMP" is 'Minimale temperatur der Ware';
comment on column DIRKSPZM32.LVS_LTE_HIST."NVE_NR" is 'Eindeutigen Nummer aus Vergabe';
comment on column DIRKSPZM32.LVS_LTE_HIST."ORDER_AUF_ID" is 'Auf_ID aus der ISI-Order';
comment on column DIRKSPZM32.LVS_LTE_HIST."ORDER_VORGANG_ID" is 'Kopf der ISI-Order, wenn Ware auf  dieser LTE  für diese Order reserviert ist sont  null';
comment on column DIRKSPZM32.LVS_LTE_HIST."PACKSCHEMA_KOPF_ID" is 'ID / Name des Packschemas';
comment on column DIRKSPZM32.LVS_LTE_HIST."RES_ARTIKEL_ID" is 'Artikel_ID als String, kann auch ''MP'' für Mischpaltette sein';
comment on column DIRKSPZM32.LVS_LTE_HIST."RES_LOGIN_ID" is 'User, für den diese LTE reserviert ist. Nicht zwingend für Lieferschein/Verladung-Order';
comment on column DIRKSPZM32.LVS_LTE_HIST."RES_MHD" is 'Gleich, solange gleiche Tage im Firmenstamm';
comment on column DIRKSPZM32.LVS_LTE_HIST."RES_STRING" is 'Lagerplatzreservierung für Bsp. Artikel, Charge oder FA + FA_AG + Charge etc.';
comment on column DIRKSPZM32.LVS_LTE_HIST."RES_STRING_STATISCH" is 'Reservierungsstring für LTE wenn null autmatische Berechnung nutzen  sonst diese';
comment on column DIRKSPZM32.LVS_LTE_HIST."RES_ZIEL_LGR_PLATZ" is 'Reservierte Ware soll zum Ziel-Lagerplatz';
comment on column DIRKSPZM32.LVS_LTE_HIST."SID" is 'Datenbank für Konsolidierung';
comment on column DIRKSPZM32.LVS_LTE_HIST."TRANSPORT_GRUPPE" is 'Beladereihenfolge für einen LKW Tournummer im MFR';
comment on column DIRKSPZM32.LVS_LTE_HIST."WAREN_TYP" is 'RW = Rohware, HW = Teilfertig/Halbfertigware (Zwischenprodukt), FW Fertigware, MP mischpalette lp leerpalette';
comment on column DIRKSPZM32.LVS_LTE_HIST."WERT_KLASSE" is '0 = Klein, 99 = Hoch';
comment on column DIRKSPZM32.LVS_LTE_HIST."WICKELPROGRAMM" is 'Wickel Programm Nr. mit der die LTE aktuell gewickelt werden soll';
comment on column DIRKSPZM32.LVS_LTE_HIST."WICKELPROGRAMM_EINL" is 'Wickel Programm Nr. wie die LTE eingelagert werden soll';
comment on column DIRKSPZM32.LVS_LTE_HIST."ZIEL_LGR_ORT" is 'Ziel Lagerort';
comment on column DIRKSPZM32.LVS_LTE_HIST."ZIEL_LGR_ORT_N_FREIF" is 'Ziel Lagerort der nach dem Freifahern wieder gesetzt werde soll';
comment on column DIRKSPZM32.LVS_LTE_HIST."ZIEL_LGR_PLATZ" is 'Ziel Lagerplatz';
comment on column DIRKSPZM32.LVS_LTE_HIST."ZIEL_LGR_PLATZ_N_FREIF" is 'Ziel Lagerplatz der nach dem Freifahern wieder gesetzt werde soll';



-- sqlcl_snapshot {"hash":"18474de6e48b7dfbdf69c0ee3bf4ff6b22c64a66","type":"COMMENT","name":"lvs_lte_hist","schemaName":"dirkspzm32","sxml":""}