comment on table DIRKSPZM32.MDE_CFG is 'MDE - Maschinendatenerfassung';
comment on column DIRKSPZM32.MDE_CFG."COMMUNICATION_MANDANT" is 'AMQ Virtual Host , Mandant, Gruppierung';
comment on column DIRKSPZM32.MDE_CFG."COMMUNICATION_QUEUE_RECEIVER" is 'AMQ ReceiveQueue';
comment on column DIRKSPZM32.MDE_CFG."COMMUNICATION_QUEUE_SENDER" is 'AMQ SendQueue';
comment on column DIRKSPZM32.MDE_CFG."COMPUTERNAME" is 'COMPUTERNAMEN auf dem die Applikation laufen soll für diese Konfig';
comment on column DIRKSPZM32.MDE_CFG."ENGINE_ID" is 'Engine number z.B. für eine Trennung';
comment on column DIRKSPZM32.MDE_CFG."FA_IST_MENGEN_INT_MS" is 'Fertigungs ist mengen Buchung in DB aus OPC Server intervall in ms';
comment on column DIRKSPZM32.MDE_CFG."FIRMA_NR" is 'Firma Nr';
comment on column DIRKSPZM32.MDE_CFG."FKT_MELDUNGEN" is '0=Aus; 1= Meldungen als Bits mit Kommt und Geht';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_0" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_1" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_10" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_11" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_12" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_13" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_14" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_15" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_16" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_17" is '0=Aus; 1= B0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_18" is '0=Aus; 1= BDE_Schlechtteile;  2=0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_19" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_2" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_20" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_21" is '0=Aus; 1= BDE_0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_22" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_23" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_24" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_25" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_3" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_4" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_5" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_6" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_7" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_8" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."FKT_ZAEHLER_9" is '0=Aus; 1= Allgemein;  2= Gut Teile;  3= Qual B Teile; 4= Schlecht Teile; 5= MicroStops; 6= Betriebszeit';
comment on column DIRKSPZM32.MDE_CFG."IS_BDE_FA_DATEN" is 'Bde Auftrags Maschinendaten verwalten';
comment on column DIRKSPZM32.MDE_CFG."IS_MELD_STAT" is 'Meldungen Status anzeigen und  loggen';
comment on column DIRKSPZM32.MDE_CFG."IS_MELD_STOER" is 'Meldungen Stoerungen anzeigen und Loggen';
comment on column DIRKSPZM32.MDE_CFG."IS_ZAEHLER_LOGGEN" is 'zaehler auslesen und loggen ';
comment on column DIRKSPZM32.MDE_CFG."IS_ZAEHL_RES_SCHICHTWECHSEL" is 'Befehl Zaehler Reset bei Schichtwechsel im BDE';
comment on column DIRKSPZM32.MDE_CFG."MDE_COM_SERVER" is 'IP und Port wenn nicht über OPC zugegriffen wird';
comment on column DIRKSPZM32.MDE_CFG."MDE_CONNECTION_TYP" is 'Kommunikationstyp ''AMQP'', ''OPC'' = OPC-server über Inat  //  SPS über ILC150 -> ''GSC_R_SD4'' SPS Programmname ';
comment on column DIRKSPZM32.MDE_CFG."MDE_ID" is 'Unikats ID der MDE';
comment on column DIRKSPZM32.MDE_CFG."MELD_CFG_NR" is 'Zeigt für Meldungen auf Tabelle MELDUNG_CFG';
comment on column DIRKSPZM32.MDE_CFG."MELD_STAT_CFG_NR" is 'Zeigt für status einträge auf die Tabelle Meldung_CFG';
comment on column DIRKSPZM32.MDE_CFG."OPC_CONNECTION_ID" is 'OPC Verbindung';
comment on column DIRKSPZM32.MDE_CFG."OPC_GRUPPE" is 'OPC  GRUPPE';
comment on column DIRKSPZM32.MDE_CFG."RES_ID" is 'Resourcen ID';
comment on column DIRKSPZM32.MDE_CFG."SID" is 'SID';
comment on column DIRKSPZM32.MDE_CFG."ZAEHLER_LOG_INT_MS" is 'Zaehler Loggen Intervall  in ms . Sollte nicht kleiner als 60*1000*15 1/4 Stunde werden 0=Aus ';



-- sqlcl_snapshot {"hash":"9d45eccf61183188a851c3d9be01b471f2835305","type":"COMMENT","name":"mde_cfg","schemaName":"dirkspzm32","sxml":""}