comment on table DIRKSPZM32.S_ERP_RCV_FA_AUF is 'Fertigungsauftraege uebergabe aus SAP';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AB_ARTIKEL" is 'Eindeutiger Artikel ID des Auftragskopf';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AB_IST" is 'Istmenge im Auftragskopf';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AB_SOLL" is 'Sollmenge im Auftragskopf';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AB_STATUS" is 'NULL = Noch nicht bearbeitet UE = Im ISIPlus übernommen L = Auftrag kann gelöscht werden F = Auftrag komplett Fertig TF = Teilfertig AR = Rüsten AP = Produktion';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AB_TEXT1" is 'Auftragskopf Text 1';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AB_TEXT2" is 'Auftragskopf Text 2';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AB_TEXT3" is 'Auftragskopf Text 3';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_ARTIKEL" is ' Artikel des Arbeitsgangs (Kann bei Zwischenprodukten die gleiche des Endprodukts sein. ISI verwaltet die produzierte Menge der zwischenschritte entsprechend). Bei Anforderungen Lack muss hier "PROD_PARAM=LACK_GRP;" eingetragen werden. (SACHNUMMER) zwischenschritte entsprechend)';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_ART_BREITE" is 'Breite';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_ART_DICKE" is 'Dicke';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_ART_DURCH" is 'Durchmesser';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_ART_LAENGE" is 'Länge';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_BEZ1" is 'Arbeitsgang Bezeichnung 1';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_BEZ2" is 'Arbeitsgang Bezeichnung 2';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_FREIGABE_ST" is 'Freigabestatus';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_IST_MG" is 'Istmenge im Arbeitsgang';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_IST_MG_B" is 'Menge B Qualität';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_IST_RUESTEN" is 'Menge beim Rüsten';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_IST_SCHROTT" is 'Menge Schrott';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_LOS_MG" is 'Sollmenge in diesem AG die als Produktionsmenge zur Maschiene gesendet werden soll (Teilmenge für dieses Produktionslos)';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_PROD_FREI" is 'Y = Freigegeben für Produktion, N = Nur Planung';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_SOLL_MG" is 'Sollmenge im Arbeitsgang';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_STATUS" is 'N = Noch nicht bearbeitet F = Auftrag komplett Fertig TF = Teilfertig AR = Rüsten AP = Produktion';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_TEXT1" is 'Arbeitsgang Text 1';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_TEXT2" is 'Arbeitsgang Text 2';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_TEXT3" is 'Arbeitsgang Text 3';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AG_UEBERLAPPEN" is 'Anzahl die fertig sein müssen, um den
                  nächsten AG zu beginnen
nächsten AG zu beginnen';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."ANZ_MITARBEITER" is 'Anzahl Mitarbeiter';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."ANZ_ROHSTOFFE" is 'Anzahl der benötigten Drähte';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AUFTRAG" is 'Aufragsnummer (PLEIT)';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AUF_ID" is 'eindeutige Sequenz-Nummer';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."AUSGEF_ENDE" is 'AUSGEFÜHRTES ENDE';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."BEST_NR_KUNDE" is 'Bestellnummer des Kunden';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."CHARGE" is 'Vorgabe CHARGE';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."EINSATZ" is 'Einsatzgewicht';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."ENDE_GEPL" is 'Geplanter Ende Termin in dd.mm.yyyy';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."ENDE_IST" is 'Echter Ende Termin in dd.mm.yyyy';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."EXT_ARBEITS_ANWEISUNG" is 'URL zur Arbeitsanweisung';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."FA_AG" is 'Arbeitsgang zur Leitzahl aus SAP';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."FA_UPOS" is 'Unterposition für Gruppenarbeit';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."FIRMA_NR" is 'Mandant z.B. 01';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."FREMD_ZEICHNUNG" is 'Externe Zeichnung';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."GEWICHT" is 'Gewicht';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."KATEGORIE" is 'Kategorie z.B. SAMPLE, Nachschreiber, ...';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."KENZ_LHM_DRUCK" is 'Etikettendruck je Karton ''T'' = Ja drucken';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."KUNDEN_AB" is 'AB Nummer des Kundenauftrags';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."KUNDEN_AB_POS" is 'AB Positionsnummer des Kundenauftrags';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."KUNDEN_AB_TEXT" is 'Beschreibender Text zum  Kundenauftrags';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."KUNDEN_AB_UPOS" is 'AB Unterposition des Kundenauftrags';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."KUNDEN_AB_WECHSEL_RUESTZEIT" is 'Rüstzeit die entsteht, wenn die Kunden_AB wechselt (Rüstzeit wird als FHM gespeichert)';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."KUNDEN_NR" is 'Kundennummer aus Adressen';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."LEAD_LEITZAHL" is 'Leitzahl des Vorgängerauftrags';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."LEITZAHL" is 'Leitzahl aus SAP (KLEIT)';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."LHM_MENGE" is 'Menge im LHM (Packmittel)';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."LHM_NAME" is 'Hilfsmittelname (Kiste, Karton, etc.) Bsp.: K600';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."LTE_MENGE" is 'Menge im LTE (Palette)';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."LTE_NAME" is 'Name der Transporteinheit / Palette Gitteboxstapel etc';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."LUECKENFUELLER" is 'Lückenfüller ''F'' False (Nein) (Zwischenplanen) ''T'' = Ja

';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."MASCHINE" is 'Eindeutiger Maschinen ID Z.B. M36';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."MAX_TAK_AUSF_ZEIT" is 'Maximale Takt Ausfallzeit';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."MAX_TAK_ZEIT" is 'Maximale Takt Zeit';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."MIN_TAK_ZEIT" is 'Minimale Takt Zeit';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."NUTZEN" is 'Nutzen';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."PRIMAER_LEITZAHL" is 'Leitzahl des Primärauftrag';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."PRIORITAET" is 'Priorität des Fertigungsauftrags';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."PROD_PARAM" is 'Mögliche Lacke eintragen Beispiel: LACK_GRP=CAB-200_V1,CAB-200_V3; (CAB-200), Bei den V-Sätzen Drillleiter o.ä. die Anzahl der benötigten Vorprodukte ANZ_VOR_AG=45; oder bei Rohstoffen (Materialanforderung) AG 1 ANZ_MA_AG=1-3; (3 Vorgezogene Drähte), RES_ALTEERNATIVEN=F10-001_12345,F10-002,F10-003,...;, Maschine -> F10-001 _ 12345 Minuten';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."PROD_ZEIT_GEPL" is 'Produktionzeit geplant';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."PROD_ZEIT_IST" is 'Produktionzeit ist';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."RCV_AG_IST_MG" is 'Bereits gefertigte Menge in diesem AG die zum HOST gesendet wurde';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."RCV_AG_IST_MG_B" is 'Angefalle Menge in B-Qualität für diesen AG die zum HOST gesendet wurde';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."RCV_AG_IST_MG_RUESTEN" is 'Angefalle Menge beim Rüsten und Anfahren für diesen AG die zum HOST gesendet wurde';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."RCV_AG_IST_MG_SCHROTT" is 'Angefalle Schrottmenge für diesen AG die zum HOST gesendet wurde';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."RCV_PROD_ZEIT_IST" is 'Angefallene netto Produktionszeit in Minuten die zum HOST gesendet wurde';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."RCV_RUEST_ZEIT_IST" is 'Angefallene Rüstzeit in Minuten die zum HOST gesendet wurde';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."RCV_STOER_ZEIT_IST" is 'Angefallene Ausfallzeiten in Minuten die zum HOST gesendet wurde';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."RUEST_ZEIT_GEPL" is 'Rüstzeit geplant';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."RUEST_ZEIT_IST" is 'Rüstzeit ist';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."SATZART" is 'MA = Materialanforderung VR = Verrichten';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."SCHROTT" is 'Schrottgewicht';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."SEQ_NR" is 'Sequenz-Nummer, für das Zielprodukt auf der Fertigungslinie Montage - Ab DB31';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."SID" is 'SID';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."START_BATCH_BY_ORDER_START" is 'Dieser Batch wird gestartet, wenn der AG auf der Maschine angemeldet wird';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."START_GEPL" is 'Geplanter Start Termin in dd.mm.yyyy';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."START_IST" is 'Echter Start Termin in dd.mm.yyyy';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."STOER_ZEIT_GEPL" is 'Unterbrechungszeit geplant';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."STOER_ZEIT_IST" is 'Unterbrechungszeit ist';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."TERM_BEST" is 'Bestätigter Termin in dd.mm.yyyy hh24:mi:ss';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."TERM_WUNSCH" is 'Wunschtermin in dd.mm.yyyy hh24:mi:ss';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."TRANSP_ZEIT" is 'Transportzeit für die Lieferung zum Kunden in STD';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."TS" is 'TimeStamp Erzeugt in der Schnittstelle';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."TSC" is 'TimeStamp geändert in der Schnittstelle';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."VERBRAUCH" is 'Gewicht Verbraucht';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."VORGANGSQUALIFIKATION" is 'Qualifikation, die das Personal zur Bedienung des Vorgangs benötigt';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."ZEICHNUNG" is 'Zeichnung';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."ZEICHNUNGNAME" is 'Zeichnungsname (*.TIF)';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."ZEICHNUNG_INDEX" is 'Zeichnungsindex';
comment on column DIRKSPZM32.S_ERP_RCV_FA_AUF."ZEIT_EINHEIT" is 'Benötigte Zeit je Einheit';



-- sqlcl_snapshot {"hash":"c59182ef644e51acb37d5744c9895263f66dc422","type":"COMMENT","name":"s_erp_rcv_fa_auf","schemaName":"dirkspzm32","sxml":""}