comment on table DIRKSPZM32.S_ERP_RCV_ARTIKEL is 'Artikelstamm uebergabe aus SAP';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."ABC" is 'A = Schnell B = Mittel C = Langsam';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."AKTIV" is 'Status Aktiv T = Artikelnummer ist gültig, F = Artikelnummer ist ungültig';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."ARTIKEL" is 'Artikelnummer aus Schnittstelle';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."ARTIKEL_FUER_KUNDE" is 'ADRESS_ID aus ISI_ADRESSEN';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."ARTIKEL_FUER_KUNDE_ETIKETT" is 'Kundennummer für Etikettendruck zur Auswahl einenes Etiketts';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."ARTIKEL_P1" is 'Parameter P1 Gleitmittel r31pt_smpt323';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."ARTIKEL_P10" is 'Parameter P10';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."ARTIKEL_P2" is 'Parameter P2 Tellergewicht für Etikettendruck r31pt_smpt333';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."ARTIKEL_P3" is 'Parameter P3';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."ARTIKEL_P4" is 'Parameter P4';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."ARTIKEL_P5" is 'Parameter P5';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."ARTIKEL_P6" is 'Parameter P6';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."ARTIKEL_P7" is 'Parameter P7';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."ARTIKEL_P8" is 'Parameter P8';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."ARTIKEL_P9" is 'Parameter P9';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."BESCHAFFUNGS_KOSTEN" is 'Kosten für Fremdbezug';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."BEZEICHNUNG1" is 'Bezeichnung 1';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."BEZEICHNUNG2" is 'Bezeichnung 2 Textobjekt im SAP Zeile 1
';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."BEZEICHNUNG3" is 'Bezeichnung 3 Textobjekt im SAP Zeile 2
';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."BREITE" is 'Breite des Artikels in mm';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."B_DATUM" is 'Buchungszeitpunkt als String';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."CREATED_DATE" is 'Erstelldatum und Zeitstempel wann der Datensatz kreiert wurde';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."CREATED_LOGIN_ID" is 'Id des Benutzers der diesen Datensatz erstellt hat';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."DURCH" is 'Durchmesser';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."EAN" is 'EAN je kleinster Einheit (z.B. Je Becher, Päckchen, Stück etc.)';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."FIRMA_NR" is 'Firmen Nr. z.b. 1';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."GEFAHREN_KLASSE" is '0 = Klein, 99 = Hoch';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."GEWICHT" is 'Gewicht in Gramm je Mengeneinheit';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."HERSTELL_KOSTEN" is 'Herstell';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."HOEHE" is 'Höhe des Artikels in mm';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LABOR_VORG_STATUS" is 'U = Unfrei (Muss noch geprüft werden), F = Frei (Kann geliefert werden), G = Gesperrt (Geprüft und gesperrt)';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LAENGE" is 'Länge des Artikels in mm';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LAM_SEL1" is 'Parameter zusätzliche Selectionsparameter als Default';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LAM_SEL10" is 'Parameter zusätzliche Selectionsparameter als Default';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LAM_SEL2" is 'Parameter zusätzliche Selectionsparameter als Default';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LAM_SEL3" is 'Parameter zusätzliche Selectionsparameter als Default';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LAM_SEL4" is 'Parameter zusätzliche Selectionsparameter als Default';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LAM_SEL5" is 'Parameter zusätzliche Selectionsparameter als Default';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LAM_SEL6" is 'Parameter zusätzliche Selectionsparameter als Default';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LAM_SEL7" is 'Parameter zusätzliche Selectionsparameter als Default';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LAM_SEL8" is 'Parameter zusätzliche Selectionsparameter als Default';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LAM_SEL9" is 'Parameter zusätzliche Selectionsparameter als Default';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LAST_CHANGE_DATE" is 'Änderungsdatum und Zeitstempel wann der Datensatz zuletzt geändert wurde';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LAST_CHANGE_LOGIN_ID" is 'Id des Benutzers der diesen Datensatz zuletzt geändert hat';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LAUFRICHTUNG" is 'Ist das Teil Laufrichtungsgebunden? Null=noch nicht spezifiziert! M=mit Bindung, O=ohne Bindung, E=egal (Montage Reifenflanke innen/aussen egal)';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LHM_EAN" is 'EAN für LHM';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LHM_GEWICHT_KG" is 'LHM Gewicht incl. Verpackung';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LHM_MENGE" is 'LHM = Kleinste Gebindemenge';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LHM_NAME" is 'Name des LHM z.B. K600 = Karton 600 aus LVS_LHM_CFG';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LHM_TARA" is 'LHM TARA ist das Taragewicht für die Verwiegung (Übergabe an die Waage)';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LTE_BREITE_MAX" is 'Max Breite incl. Überstand';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LTE_EAN" is 'EAN für eine Transporteinheit';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LTE_GEWICHT_KG" is 'Max Gewicht der Transporteinheit (Gilt nur für Artikelreine Ttransporteinheit)';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LTE_HOEHE_LAGE" is 'Höhe einer Lage (LHM''s)';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LTE_HOEHE_MAX" is 'Max Höhe incl. Transporteinheit';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LTE_LHM_LAGEN" is 'Anzahl Lagen (LHM''s) je LTE';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LTE_LHM_MENGE" is 'Anzahl LHM je Transporteinheit';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LTE_LHM_PRO_LAGE" is 'Anzahl LHM je Lage';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LTE_MENGE" is 'Menge je Mengeneinheit pro. Transporteinheit';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LTE_NAME" is 'EURO = Europalette, INDU = INDU-Palette, CHEPEURO = Chep-Europalette ... aus LVS_LTE_CFG';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."LTE_TIEFE_MAX" is 'Max Tiefe incl. Überstand';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."MATERIALART" is 'Material z.B. Zur für findung der Rohdichte aus ROHSTOFF_MATERIALART';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."MAX_LAGER_TEMP" is 'Maximale Temperatur im Lager';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."MENGENEINHEIT" is 'Mengeneinheit STK = Stück, KG = Kilogramm, L = Liter, M = Meter, M2, M3, PCK = Päckchen';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."MHD_TAGE" is 'Min. Haldbar in Tagen';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."MIN_LAGER_TEMP" is 'Minimale Temperatur im Lager';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."MIN_MHD_TAGE_AUSL" is 'Mindest MHD-Tage für Auslagerung';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."MIN_MHD_TAGE_MS" is 'Mindest MHD-Tage für die Weiterverarbeitung';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."PACK_VORSCHR" is 'Verpackungsvorschrift';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."PREIS_GLEITEND" is 'Preis gleitend in EUR';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."PREIS_STANDARD" is 'Standardpreis in EUR';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."REIFE_ZEIT_TAGE" is 'Reifezeit in Tagen   0,5 = 12 Stunden';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."SID" is 'SID Mandant z.B. 01
';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."VOLUMEN_CM3" is 'Volumen in CM3';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."WAREN_GRUPPE" is '1=Ring 2=Ventilteller 3=VT Ring 20=Tech 30=SPÜ 40=FLVT60=Mat';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."WAREN_TYP" is 'RW = Rohware, HW = Teilfertig/Halbfertigware (Zwischenprodukt), FW Fertigware';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."WERT_KLASSE" is '0 = Klein, 99 = Hoch';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."WIEDER_BESCH" is 'Wiederbeschaffungszeit in Tagen';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."ZEICHNUNG" is 'Externe Zeichnung';
comment on column DIRKSPZM32.S_ERP_RCV_ARTIKEL."ZEICHNUNG_INDEX" is 'Zeichnungsindex (quasi Variante des Artikels)';



-- sqlcl_snapshot {"hash":"ae94769551dbd6f708d39924a889652fb7274f91","type":"COMMENT","name":"s_erp_rcv_artikel","schemaName":"dirkspzm32","sxml":""}