comment on table DIRKSPZM32.S_SEND_BEW is 'Bewegungsdaten aus ISIPlus';
comment on column DIRKSPZM32.S_SEND_BEW."AKTION" is 'AV = Status in Vorbereitung AA = Status Angefangen AR = Status Rüsten  AP = Status Produktion UE = Im ISIPlus übernommen L = Position im ISIPlus gelöscht F = Position komplett Fertig TF = Position ist Teilfertig STB = Störung Beginn STG = Störung begründen STE = Störung Ende WEI = Zugang Intern (z.B. Produktion) WAI = Abgang Intern (z.B. Maschine) WEE = Zugang Extern (Warenanlieferung) WAE = Abgang Extern (Versand von Ware) WUI = Umlagerung Intern WUE = Umlagerung Extern BAG = Bestandsabgleich INV = Inventur FRE = Freigeben SPR = Sperren';
comment on column DIRKSPZM32.S_SEND_BEW."ARBEITSPLATZ_ID" is 'Arbeitsplatz der Versands bei Auslieferung';
comment on column DIRKSPZM32.S_SEND_BEW."ARTIKEL" is 'Artikelnummer';
comment on column DIRKSPZM32.S_SEND_BEW."AUF_ID" is 'eindeutige Sequenz-Nummer in Tabelle (S_RES...) oder Sequenz-Nummer aus ISIPlus wenn TABELLE = NULL';
comment on column DIRKSPZM32.S_SEND_BEW."BRUTTO_KG" is 'Brutto KG Gewicht für Rückmeldung im Lieferschein (LIF)';
comment on column DIRKSPZM32.S_SEND_BEW."B_DATUM" is 'Buchungszeitpunkt';
comment on column DIRKSPZM32.S_SEND_BEW."CHARGE" is 'Charge des Materials';
comment on column DIRKSPZM32.S_SEND_BEW."ERR_NR" is 'Fehlernummer z.B. 1 = LTE nicht vorhanden2 = LTE schon disponiert3 = Artikelnr fehlt';
comment on column DIRKSPZM32.S_SEND_BEW."EXT_LIEF_NR" is 'Externe Lieferscheinnummer bei Anlieferungen';
comment on column DIRKSPZM32.S_SEND_BEW."EXT_LIEF_POS" is 'Externe Lieferscheinposition bei Anlieferungen';
comment on column DIRKSPZM32.S_SEND_BEW."FA_AG" is 'Arbeitsgang';
comment on column DIRKSPZM32.S_SEND_BEW."FA_UPOS" is 'Unterposition';
comment on column DIRKSPZM32.S_SEND_BEW."FIRMA_NR" is 'Mandant z.B. 01';
comment on column DIRKSPZM32.S_SEND_BEW."HERKUNFT" is '"ISI" immer konstant';
comment on column DIRKSPZM32.S_SEND_BEW."IST_BESTAND" is 'IST_BESTAND für BAG oder INV';
comment on column DIRKSPZM32.S_SEND_BEW."LABOR_STATUS" is 'Laborstatus Q=Quarantäne Q-Prüfung, G= Gesperrt, F=Frei, U=Undefiniert Prüfsystem war offline, W=Warenausgangsprüfung, S=Sonderprüfung';
comment on column DIRKSPZM32.S_SEND_BEW."LAGERORT" is 'Lagerort im HOST';
comment on column DIRKSPZM32.S_SEND_BEW."LAGERPLATZ" is 'Lagerplatz im ISI';
comment on column DIRKSPZM32.S_SEND_BEW."LAM_AG" is 'AG aus LAM (Zwischenprodukt)';
comment on column DIRKSPZM32.S_SEND_BEW."LAM_BH_ID" is 'ID der Buchung';
comment on column DIRKSPZM32.S_SEND_BEW."LAM_BH_TYP" is 'LA, LZ oder LU Lagerabgang, Zugang oder Umlagerung';
comment on column DIRKSPZM32.S_SEND_BEW."LAM_ID" is 'ID aus LVS_LAM';
comment on column DIRKSPZM32.S_SEND_BEW."LAM_SEL1" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.S_SEND_BEW."LAM_SEL10" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.S_SEND_BEW."LAM_SEL2" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.S_SEND_BEW."LAM_SEL3" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.S_SEND_BEW."LAM_SEL4" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.S_SEND_BEW."LAM_SEL5" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.S_SEND_BEW."LAM_SEL6" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.S_SEND_BEW."LAM_SEL7" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.S_SEND_BEW."LAM_SEL8" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.S_SEND_BEW."LAM_SEL9" is 'Parameter zusätzliche Selectionsparameter';
comment on column DIRKSPZM32.S_SEND_BEW."LEITZAHL" is 'Leitzahl aus FA_Auftrag';
comment on column DIRKSPZM32.S_SEND_BEW."LHM_NR" is 'Nummer des Lagerhilfsmittel (Barcode)';
comment on column DIRKSPZM32.S_SEND_BEW."LTE_NAME" is 'Art, Name der Transporteinheit';
comment on column DIRKSPZM32.S_SEND_BEW."LTE_NR" is 'Nummer der Transporteinheit (Barcode)';
comment on column DIRKSPZM32.S_SEND_BEW."MA_ID" is 'Maschinen ID aus HOST';
comment on column DIRKSPZM32.S_SEND_BEW."MA_LAST_S_GRUND" is 'Letzter Status Grund (Vor diesen aktuelle Status)';
comment on column DIRKSPZM32.S_SEND_BEW."MA_STATUS" is 'Maschinenstatus P = Produktion U = Unterbrechung';
comment on column DIRKSPZM32.S_SEND_BEW."MA_S_GRUND" is 'Störgrundnummer';
comment on column DIRKSPZM32.S_SEND_BEW."MENGE" is '1.Wahl Stück (LVS / BDE) oder Störgrund';
comment on column DIRKSPZM32.S_SEND_BEW."MENGE_B" is 'B Qualität Stück (Nicht für Euscher)';
comment on column DIRKSPZM32.S_SEND_BEW."ORDER_POS_AUF_ID" is 'Reserveriert für Auftrag in ISI_Order (oder -1 = für manuelle Auslagerung, -2 = für manuelle Umlagerung)';
comment on column DIRKSPZM32.S_SEND_BEW."PERS_NR" is 'Personalnummer des Benutzers (Bei integriertem PZM wir die Personalnumme und die Kontaktdaten von PZM übersteuert (Trigger im PZM)';
comment on column DIRKSPZM32.S_SEND_BEW."PRODZEIT_IST" is 'Produktionszeit in Minuten';
comment on column DIRKSPZM32.S_SEND_BEW."PROD_ZEIT_ERF" is 'Erfasste netto Produktionszeit in Minuten - Aus Anmeldungen in BDE_PROD_KOPF_MA - Mitarbeiterstunden';
comment on column DIRKSPZM32.S_SEND_BEW."RES_ID" is 'Res_id der Erzeugermaschine';
comment on column DIRKSPZM32.S_SEND_BEW."RUESTZEIT_IST" is 'Rüstzeit in Minuten (Produktionsfertigmeldung)';
comment on column DIRKSPZM32.S_SEND_BEW."RUEST_ZEIT_ERF" is 'Erfasste Rüstzeit in Minuten - Aus Anmeldungen in BDE_PROD_KOPF_MA - Mitarbeiterstunden';
comment on column DIRKSPZM32.S_SEND_BEW."R_MENGE" is 'Menge Rüsten 1.Wahl Stück (Nicht für Euscher)';
comment on column DIRKSPZM32.S_SEND_BEW."R_MENGE_B" is 'Menge Rüsten B Qualität Stück (Nicht für Euscher)';
comment on column DIRKSPZM32.S_SEND_BEW."R_SCHROTT" is 'Schrottmenge beim Rüsten in Stück';
comment on column DIRKSPZM32.S_SEND_BEW."SCHROTT" is 'Schrottmenge in Stück';
comment on column DIRKSPZM32.S_SEND_BEW."SEND_ID" is 'ID, mit der diese Bewegung versendet wurde';
comment on column DIRKSPZM32.S_SEND_BEW."SERIE" is 'Seriennummer des Materials';
comment on column DIRKSPZM32.S_SEND_BEW."SPER_GRUND" is 'Sperr- oder Schrottgrund aus LAM. LABOR_TEXT';
comment on column DIRKSPZM32.S_SEND_BEW."STATUS" is 'NULL = Im HOST noch nicht Übernommen UE = HOST hat den Satz übernommen A = HOST hat Angefangen F = HOST ist Fertig L = ISIPlus kann den Eintrag Löschen, SB/SE/SW = Schicht Beg./Ende/Wechsel, RS/RE/PS/PE = Auftrag Start/Ende Rüsten Produktion, SG = Statusgrund gewechselt';
comment on column DIRKSPZM32.S_SEND_BEW."STOERZEIT_IST" is 'Störzeit in Minuten (Produktionsfertigmeldung)';
comment on column DIRKSPZM32.S_SEND_BEW."TABELLE" is 'NULL = Keine Referenz zu HOST Tabellen sonst Tabellenname';
comment on column DIRKSPZM32.S_SEND_BEW."TEXT" is 'Rückgabetext';
comment on column DIRKSPZM32.S_SEND_BEW."USER_NAME" is 'Username aus ISI_User';
comment on column DIRKSPZM32.S_SEND_BEW."ZLAGERORT" is 'Ziellagerort im HOST';
comment on column DIRKSPZM32.S_SEND_BEW."ZLAGERPLATZ" is 'Ziellagerplatz im ISI';



-- sqlcl_snapshot {"hash":"eadb35e4d385b84022f2253918a6f97e0db3c0e7","type":"COMMENT","name":"s_send_bew","schemaName":"dirkspzm32","sxml":""}